### ISSUE TITLE
Featurerequest: mediafoundation

### ISSUE THREAD

**Issue by Glog78** [Matoking/protontricks#1]
Thank you for providing an updated version of protontricks. Since winetricks doesn't have a way to install mediafoundation into a prefix i was wondering if you maybe could include it.

Some needed informations ->
a.) http://www-pc.uni-regensburg.de/systemsw/win7/sp1/index.htm
b.) https://github.com/tonix64/python-installcab
c.) https://lutris.net/files/tools/dll/mfplat/x64/mfplat.dll & https://lutris.net/files/tools/dll/mfplat/x32/mfplat.dll

Thank you for the hard work.

**Comment by Matoking** [comment]
I don't think it makes sense to implement custom installation verbs like this in protontricks itself. This would be better done upstream in Winetricks or as its own standalone script. A quick search reveals there's already [an issue about this on Winetricks' repository](https://github.com/Winetricks/winetricks/issues/1132).

However, it would make sense to add an optional parameter to run an arbitrary command in the scope of the game's installation directory (let's call it `-c` or `--command`); this would make it easier to run bleeding edge fixes that haven't been added to Winetricks yet.

With that, we could create a standalone script called `install_mfplat.py` for installing mfplat.dll which could then be run as an one-liner like this:

```
$ protontricks -c 'wget github.com/install_mfplat.py; chmod +x install_mfplat.py; ./install_mfplat.py' <GAME_ID>
```

**Comment by Matoking** [comment]
I've added a `--command` / `-c` flag [in the development branch](https://github.com/Matoking/protontricks/commit/b90769f6563fa1a60737255b82bd43dbe8a9ff6d). The command configures the relevant environment variables, so it should work fine for custom scripts.

I might take a look at making a standalone shell script for mfplat installation at a later time, but I'll leave this issue open for the time being.

**Comment by Glog78** [comment]
thank you alot for the work! 
One additional idea: Wouldn't it make sense to addtional exporting a WINE Variable to adjust the path? example: export PATH={PathtoProtonWine}:$PATH

this way you can easy get an interactive environment -> protontricks -c /bin/bash AppID 

Also for the documentation you might want to add that the right "$WINE" is the right way to use the variable in scripts because of the spaces in the variable.

**Comment by Matoking** [comment]
I wrote a script that _should_ install mfplat for Steam games. It's available as a GitHub gist [here](https://gist.githubusercontent.com/Matoking/2017eeffc1cee82f4797530c67707437). I don't have a game that requires mfplat to run to test myself, so your mileage may vary.

In short, you can use the script like this:

```
protontricks -c "wget https://gist.githubusercontent.com/Matoking/2017eeffc1cee82f4797530c67707437/raw/install_mfplat.sh; chmod +x install_mfplat.sh; ./install_mfplat.sh 64 Binaries;" <APPID>
```

The script has only two parameters, the first of which is the architecture (`32` if it's 32-bit, `64` if it's 64-bit) and the output directory (in the example it's `Binaries`, so if you had a game installed in `/SteamLibrary/steamapps/common/GameName/`, the mfplat.dll would be copied into `/SteamLibrary/steamapps/common/GameName/Binaries/mfplat.dll`. **You want the mfplat.dll to be placed into the same directory as the game's .exe file.**

---

> One additional idea: Wouldn't it make sense to addtional exporting a WINE Variable to adjust the path? example: export PATH={PathtoProtonWine}:$PATH

Makes sense. I'll look into adding this later.

**Comment by Matoking** [comment]
I've created a wiki page for the mfplat installation script (and possibly other scripts in the future) [here](https://github.com/Matoking/protontricks/wiki/Custom-scripts).

Since there hasn't been any activity on this issue for a while and the script to install mfplat already exists, I'm closing the issue for now.
