### ISSUE TITLE
GUI Error..

### ISSUE THREAD

**Issue by chillabis** [Matoking/protontricks#10]
I'm using Ubuntu 18.04.2 LTS.
I followed and installed everything using pipx.
The gui starts but i can't choose steamlibrary, the only buttons that works is "Ok" and "Cancel".
After that the gui shutsdown and giving me this:

Traceback (most recent call last):
  File "/home/chillabis/.local/bin/protontricks", line 11, in <module>
    load_entry_point('protontricks==1.2', 'console_scripts', 'protontricks')()
  File "/home/chillabis/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/cli.py", line 170, in main
    steam_app = select_steam_app_with_gui(steam_apps=steam_apps)
  File "/home/chillabis/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/gui.py", line 27, in select_steam_app_with_gui
    appid = int(appid)
ValueError: invalid literal for int() with base 10: '

**Comment by Matoking** [comment]
This looks like it could be happening because you have installed Proton games through Steam, but haven't launched any of them yet. In this case, protontricks asks you to select a Steam game from an empty dropdown list, failing like this.

I've pushed an update to master that should fix this issue. Please check if it works. You can upgrade to it manually with this command:
`pipx upgrade --spec git+https://github.com/Matoking/protontricks.git protontricks`

You'll need to have git installed. If you don't have it, you can run:
`sudo apt install git`

**Comment by chillabis** [comment]
It worked after starting a game.. Tho the game refuses to start now after the update...

Got this before winetricks-gui started:
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

So uh yeah i can't play any game now..

**Comment by Matoking** [comment]
> It worked after starting a game.. Tho the game refuses to start now after the update...
> 
> Got this before winetricks-gui started:
> You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
> 
> So uh yeah i can't play any game now..
> 
> Edit: Testing installing other games.. I'll update again soon

Proton 4.2 has a bug that means you have to install it differently for the time being. See [here](https://twitter.com/Plagman2/status/1110665993590759425) for details.

The warning about the 64-bit wineprefix is normal and can be ignored.

**Comment by chillabis** [comment]
Nevermind, it's from my end.. ubuntu is bullying again.
Anyway the new version works, and i must say they released a new version of Proton today 4.2-1
