### ISSUE TITLE
KeyError: 'LibraryFolders'

### ISSUE THREAD

**Issue by StackDoubleFlow** [Matoking/protontricks#105]
**Describe the bug**
Using protontricks fails when trying to open the gui.

**To Reproduce**
1. Run command `protontricks --gui -v`
2. Command fails and error is displayed

**Expected behavior**
The gui opens successfully.

**System:**
 - Distro: Arch Linux
 - Protontricks version: protontricks (1.5.2.dev6+gae43d27)
 - Steam version: Steam Beta Update

**Additional context**

```
[stack@stackdesktop ~]$ protontricks --gui -v
protontricks (INFO): Found Steam directory at /home/stack/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/stack/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.5.2.dev6+gae43d27', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 177, in main
    steam_lib_paths = get_steam_lib_paths(steam_path)
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 630, in get_steam_lib_paths
    library_folders = parse_library_folders(folders_vdf_path.read_text())
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 614, in parse_library_folders
    Path(value) for key, value in vdf_data["LibraryFolders"].items()
KeyError: 'LibraryFolders'
```

Here is the contents of my libraryfolders.vdf:
```
"libraryfolders"
{
	"contentstatsid"		"-8740190098608779810"
	"1"
	{
		"path"		"/windows/LinuxSteam"
		"label"		""
		"mounted"		"1"
		"contentid"		"6038198704498239866"
	}
}

```

**Comment by Matoking** [comment]
The new Steam beta came with multiple breaking changes: many VDF fields are now lowercase and the structure of `libraryfolders.vdf` is now different. I've pushed changes to `vdf_all_lowercase` branch that should hopefully resolve all the new issues.

You can install and test the fixes by installing Protontricks using pipx:

```
$ sudo pacman -S python-pipx
$ pipx install --force git+https://github.com/Matoking/protontricks.git@vdf_all_lowercase
```

You may need to reopen the terminal before the installation is detected. Also, `/usr/bin/protontricks` might override the pipx installed version of Protontricks, so you may need to uninstall the AUR version before you can test the fix, or run `~/.local/bin/protontricks` instead.

Could you check whether this lets you run Protontricks properly again?

**Comment by StackDoubleFlow** [comment]
Yes, this seems to work great. Thank you!

**Comment by Matoking** [comment]
Great, thanks for the quick confirmation!
