### ISSUE TITLE
FileNotFoundError with Proton-6.10-GE-1 (Glorious Eggroll)

### ISSUE THREAD

**Issue by malinkb** [Matoking/protontricks#106]
This happens with afik, Proton 6.5+ versions, as /dist/bin is replaced with /files/bin and perhaps other changes as well. See attachment for error log
[protontricks-error-log.txt](https://github.com/Matoking/protontricks/files/6607212/protontricks-error-log.txt)

**Comment by Matoking** [comment]
Do you have the latest version of Protontricks installed (check with `protontricks --version`)? This issue should be fixed starting with Protontricks 1.5.0.

**Comment by malinkb** [comment]
You're right. I didn't have the latest version of Protontricks installed. With the latest version it works as it should. Should have checked that closer before reporting
