### ISSUE TITLE
AttributeError: module 'protontricks.cli' has no attribute 'main'

### ISSUE THREAD

**Issue by MartinX3** [Matoking/protontricks#115]
**Describe the bug**
It's not posible to run protontricks

**To Reproduce**
1. Run command `protontricks`
2. Command fails and error is displayed

**Expected behavior**
A working application

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks version: 1.6.0
 - Steam version: newest non beta
**Additional context**
```
$ protontricks -v
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.6.0', 'console_scripts', 'protontricks')())
  File "/usr/bin/protontricks", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'protontricks.cli' has no attribute 'main'
```

**Comment by Matoking** [comment]
`protontricks.cli.main` function doesn't exist anymore as of 1.6.0, so it seems like you might have an older installation of Protontricks alongside the newer 1.6.0 one, and those two are getting mixed up.

I assume you've installed either `protontricks` or `protontricks-git` from AUR? In that case, try running the following commands to delete any existing installations and then reinstalling:

```
$ <aur-helper> -R protontricks/protontricks-git  # Uninstall Protontricks from AUR
$ pip uninstall --user protontricks  # Uninstall local pip installation, if any
$ sudo pip uninstall protontricks  # Uninstall system-wide pip installation, if any
$ pipx uninstall protontricks # Uninstall pipx installation, if any
$ <aur-helper> -S protontricks/protontricks-git  # Reinstall Protontricks from AUR
```

If that doesn't help, we might get a better clue of where Python is looking for Protontricks by running the following command:

```
$ python3 -c "import pkg_resources; print(repr(pkg_resources.get_distribution('protontricks')))"
```

In my system it lists `/usr/lib/python3.9/site-packages` as the source; any other directory is likely an old leftover.

**Comment by MartinX3** [comment]
Yes, I use protontricks from AUR. :)

```
$ sudo pip uninstall protontricks
Found existing installation: protontricks 1.5.1
Uninstalling protontricks-1.5.1:
  Would remove:
    /usr/lib/python3.9/site-packages/protontricks-1.5.1-py3.9.egg-info
Proceed (y/n)? y
  Successfully uninstalled protontricks-1.5.1

```

```
$ python3 -c "import pkg_resources; print(repr(pkg_resources.get_distribution('protontricks')))"
protontricks 1.6.0 (/usr/lib/python3.9/site-packages)
```

Fixed, many thanks! :)
