### ISSUE TITLE
cant get to install protontricks

### ISSUE THREAD

**Issue by captaincupcakes** [Matoking/protontricks#124]
hello.....

every time i try to run proton tricks to run stuff i get:

Traceback (most recent call last):

File "/home/captaincupcakes/.local/bin/protontricks", line 5, in <module>

from protontricks.cli import main

ModuleNotFoundError: No module named 'protontricks'

yet everytime i want to install it it says its already installed...is there a command to run so i can give you guys more details.cause this all i have....thanks in advance

**Comment by Matoking** [comment]
What installation method are you trying to use? What distro are you using? 

Did it work before? Assuming it worked before, you can try to uninstall any existing installation and then reinstall. In your case, you could try the following:

```
$ pipx uninstall protontricks # Uninstall protontricks using pipx, if available
$ pip uninstall protontricks # User-specific pip installation
```

and then try reinstalling using whatever method you used before.

**Comment by captaincupcakes** [comment]
im using this guide
https://simpler-website.pages.dev/html/2021/1/protontricks

and im on linux mint 20.2
and it has never worked...i tried the pipx command you mentioned and got this

`/home/captaincupcakes/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/util.py", line 165, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/captaincupcakes/.local/pipx/shared/bin/python -m pip
--disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
Pipx Internal Error: cannot find package {root_req.name!r} metadata.`

also tried the pip command as well but i get a protontricks is not installed error

thank you for taking your time

**Comment by Matoking** [comment]
The system Python installation might have been updated, making the existing pipx environment incompatible.

You could start try running `pipx reinstall-all`, which should hopefully solve the problem. If that doesn't work, you could try running `rm -rf ~/.local/pipx/shared` instead.

After that, try installing Protontricks again.

**Comment by captaincupcakes** [comment]
tried `pipx reinstall-all`

got this in return 

`/home/captaincupcakes/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/util.py", line 165, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/captaincupcakes/.local/pipx/shared/bin/python -m pip
--disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
/home/captaincupcakes/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/util.py", line 165, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/captaincupcakes/.local/pipx/shared/bin/python -m pip
--disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
/home/captaincupcakes/.local/pipx/shared/bin/python: No module named pip
Failed to upgrade shared libraries
Traceback (most recent call last):
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/shared_libs.py", line 113, in upgrade
    subprocess_post_check(upgrade_process)
  File "/home/captaincupcakes/.local/lib/python3.8/site-packages/pipx/util.py", line 165, in subprocess_post_check
    raise PipxError(
pipx.util.PipxError: '/home/captaincupcakes/.local/pipx/shared/bin/python -m pip
--disable-pip-version-check install -q --upgrade pip setuptools wheel' failed
Pipx Internal Error: cannot find package {root_req.name!r} metadata.
The following package(s) failed to reinstall: protontricks
`
trying the rm command and see how it goes

**Comment by captaincupcakes** [comment]
nvm rm didnt work either....sorry to make your spend time here but im beating my head rn...

**Comment by Matoking** [comment]
At this point it might be better to try uninstalling pipx completely:

```
$ pip uninstall pipx
$ rm -r ~/.local/pipx
```

After that install `pipx` from the distro's package repository instead. It should be available since you're running Linux Mint:

```
$ sudo apt install pipx
$ pipx ensurepath
$ pipx install protontricks
```

**Comment by captaincupcakes** [comment]
thanks...that did the trick

**Comment by Matoking** [comment]
Good to hear that, I'll close this issue since the problem appears to be resolved.
