### ISSUE TITLE
PackageNotFoundError: protontricks

### ISSUE THREAD

**Issue by FlavienFe** [Matoking/protontricks#129]
After installing protontricks (first with chaotic-aur then aur, same result) I get this only message, for any command option that i put:

`% protontricks --gui
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.6.2', 'console_scripts', 'protontricks')())
  File "/usr/bin/protontricks", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: protontricks`
here it was for protontricks --gui but it does the same for protontricks 252950 vcrun2017, or any command option.
same behaviour after uninstalling and installing the AUR package protontricks

I'm on arch linux kernel 5.15.6-arch2-1

**Comment by Matoking** [comment]
Arch recently updated to Python 3.10, which means you will need to rebuild Python packages that you installed from AUR. This depends on the AUR helper you're using, but in my case I used the following commands for paru:

```
paru --rebuild -S python-vdf protontricks
```

This Reddit post might also be useful:
