### ISSUE TITLE
any help? can't install wmp11 - copying gdiplus.dll from the cache to syswow64 doesn't work

### ISSUE THREAD

**Issue by TPO100Cofficial** [Matoking/protontricks#130]
**Describe the bug**
i'm trying to install wmp11 because apparently? that makes a game i'm trying to run on proton work

**To Reproduce**
steps to reproduce the behavior:
1. run command `protontricks 1304550 wmp11`
2. command errors out, output ends with:
```
Executing load_gdiplus 
Executing cabextract -q -d /home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/temp -L -F x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll /home/akira/.cache/winetricks/win7sp1/windows6.1-KB976932-X86.exe
Executing cp /home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/temp/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll /home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/syswow64/gdiplus.dll
cp: cannot create regular file '/home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/syswow64/gdiplus.dll': Permission denied
------------------------------------------------------
Note: command cp /home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/temp/x86_microsoft.windows.gdiplus_6595b64144ccf1df_1.1.7601.17514_none_72d18a4386696c80/gdiplus.dll /home/akira/Documents/Gaming/Steam/steamapps/compatdata/1304550/pfx/dosdevices/c:/windows/syswow64/gdiplus.dll returned status 1. Aborting.
```
i'm not exactly sure what this means, because:
i already have a gdiplus.dll located at `/home/akira/.steam/debian-installation/steamapps/common/Proton - Experimental/files/lib/wine`, which is what the filepath in the error log links to
it could possibly be a problem to do with symlinks...?

**System (please complete the following information):**
 - Distro: Linux Mint 20.2 (Cinnamon)
 - Protontricks version: protontricks 1.6.2
 - Steam version: Latest, Not Beta

**Comment by Matoking** [comment]
This seems to be an upstream Winetricks issue. However, it looks like a pull request was recently merged that may fix this issue:

https://github.com/Winetricks/winetricks/pull/1847

You could try installing the development version of Winetricks and see if that solves the issue. You can check the instructions here:

https://github.com/Winetricks/winetricks#installing

**Comment by TPO100Cofficial** [comment]
hey, i found out, it works if you just use a different link than the official microsoft one used by protontricks and wine
that one's dead, but there's an archive.org one that does work
