### ISSUE TITLE
Proton tricks couldn't find steam installation directory

### ISSUE THREAD

**Issue by Mostafa-Sherif-12** [Matoking/protontricks#132]
// Full bug text {
    Protontricks was closed due to the following error:

Steam installation directory could not be found.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.6.5.
Flatpak version is too old (<1.12.1) to support sub-sandboxes. Disabling bwrap. --no-bwrap will be ignored.
}

// Additional information {
    - My steam installation directory is the default one !
    - System info {
Operating System: Kubuntu 20.04
KDE Plasma Version: 5.18.5
KDE Frameworks Version: 5.68.0
Qt Version: 5.12.8
Kernel Version: 5.11.0-44-generic
OS Type: 64-bit
}   
}

**Comment by Matoking** [comment]
Try running the following command to grant access to the `~/.steam` directory:

```
flatpak override --user --filesystem=~/.steam com.github.Matoking.protontricks
```

Can you check if that gets it working? If so, the issue would be due to missing Flatpak filesystem permissions.

**Comment by Mostafa-Sherif-12** [comment]
Yes, it worked just fine after running this terminal command [ flatpak override --user --filesystem=~/.steam com.github.Matoking.protontricks ]
Thanks a lot !

**Comment by Matoking** [comment]
Great, I've updated the default permissions for the Flatpak application to include `~/.steam`, which should be updated on Flathub in a few hours.

I'll close this issue for now.
