### ISSUE TITLE
Cannot download dotnet472 using protontricks

### ISSUE THREAD

**Issue by FelipeMelon** [Matoking/protontricks#134]
I have no idea why this bug occurs and tried searching it up everywhere

1) First I ran the command  "protontricks 261550 dotnet472" to install it
2) I get this error: error: app/com.github.Matoking.protontricks/x86_64/master not installed

Expected output: Installing dotnet

System:
 - Linux Mint 20.3
 - Protontricks installation method: Pipx
 - Protontricks version: in whatever protontricks command I am getting the same error as above
 - Steam version: n/a

I tried uninstalling, reinstalling and nothing worked. I tried using the pipx and pip. I am trying to install this dependency for Bannerlord mods

**Comment by Matoking** [comment]
You've installed Protontricks using pipx, so you don't need to add a Flatpak specific alias.

* Open the `.bashrc` file in your home directory using a text editor of your choice. If you're using the terminal, `nano ~/.bashrc` might work.
* Remove the line starting with `alias protontricks=`
* Exit and save the file (Ctrl+X if you're using nano)
* Close and reopen the terminal

After you've done this, the Protontricks command should work properly.

---

Alternatively, you can remove the pipx installation and install Protontricks from Flathub instead, in which case your alias might start working. In this case, just remember to add permission to any additional Steam library locations [as instructed here](https://github.com/Matoking/protontricks#flatpak-recommended).

**Comment by FelipeMelon** [comment]
> You've installed Protontricks using pipx, so you don't need to add a Flatpak specific alias.
> 
> * Open the `.bashrc` file in your home directory using a text editor of your choice. If you're using the terminal, `nano ~/.bashrc` might work.
> * Remove the line starting with `alias protontricks=`
> * Exit and save the file (Ctrl+X if you're using nano)
> * Close and reopen the terminal
> 
> After you've done this, the Protontricks command should work properly.
> 
> Alternatively, you can remove the pipx installation and install Protontricks from Flathub instead, in which case your alias might start working. In this case, just remember to add permission to any additional Steam library locations [as instructed here](https://github.com/Matoking/protontricks#flatpak-recommended).

Thank you very much! It did indeed solve my issue.
