### ISSUE TITLE
Dont show games from addition steam library

### ISSUE THREAD

**Issue by savegame** [Matoking/protontricks#137]
**Describe the bug**
Its show games only from  $HOME/.steam/debian-installation, but i have two separate steam libraries on separate hdd

**To Reproduce**
1. just move one of your proton games to another library, outside home dir 
2. run proton tricks, it not show your game

**Expected behavior**
It should show all games from all steam folders 

**System (please complete the following information):**
 - Distro: Ubuntu 21.10 (Pop!_OS)
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.7.1.dev0+g12df681.d20220213
 - Steam version: 1642451672

P.S. maybe i miss some options for protin tricks? how i can run it with additional steam library path?

**Comment by Matoking** [comment]
Protontricks for Flatpak is sandboxed and only has access to the Steam installation path by default. See [here for instructions](https://github.com/flathub/com.github.Matoking.protontricks/#configuration):

> In order to grant access to other directories, you can use the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) graphical utility or the [flatpak override](https://docs.flatpak.org/en/latest/flatpak-command-reference.html?highlight=override#flatpak-override) command (eg. `flatpak override --user --filesystem=<PATH> com.github.Matoking.protontricks`) to grant access to other directories.
>
> For example, to grant access to `/mnt/MySSD/SteamLibrary`, you can run the following command:
>
> ```
> flatpak override --user --filesystem=/mnt/MySSD/SteamLibrary com.github.Matoking.protontricks
> ```

Ideally, Protontricks would ask for the necessary permissions automatically, but that doesn't appear to be possible with Flatpak right now.

**Comment by savegame** [comment]
thanks, its work good now!
