### ISSUE TITLE
How would you add gallium nine to all of steam? 

### ISSUE THREAD

**Issue by tatsujb** [Matoking/protontricks#14]
I have a script that installs the steam game 9420 (supreme commander forged alliance) and configures it to work in tandem with it's unofficial (but crushingly prevalent) multiplayer client : (FAF)

https://github.com/tatsujb/installFAFscript

I used to use

https://github.com/popsUlfr/Proton

for a gallium nine versio nof proton but people tell me now you can get Gallium with protontricks.

**Comment by Matoking** [comment]
You can install Gallium Nine using the command `protontricks <appid> galliumnine`. It was added into winetricks back in February, so depending on your distribution you might have to update winetricks using another method first.

**Comment by tatsujb** [comment]
```
pipx upgrade protontricks
```
would do it right?

**Comment by Matoking** [comment]
> ```
> pipx upgrade protontricks
> ```
> 
> would do it right?

That only updates protontricks. You'll need to update winetricks differently depending on your distro, [see here for instructions](https://github.com/Winetricks/winetricks#installing).

**Comment by tatsujb** [comment]
once you have an up to date protontricks under /usr/bin, then `protontricks 9420 galliumnine` would work?

**Comment by Matoking** [comment]
> once you have an up to date winetricks under /usr/bin, then `protontricks 9420 galliumnine` would work?

Yes. To prevent possible conflicts, you should remove the existing Winetricks installation first.
