### ISSUE TITLE
protontricks does not work on Valve Steam Deck

### ISSUE THREAD

**Issue by hifihedgehog** [Matoking/protontricks#141]
I followed the instructions outlined here and at this link (https://www.reddit.com/r/SteamDeck/comments/t5a012/protontricks_for_steam_deck/hz7ixgv/?utm_medium=web2x&context=3&utm_source=reddit) to get protontricks in Flatpak form working. However, I am receiving the following error:

```
Protontricks was closed due to the following error:

Proton installation could not be found!

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.4.
Found Steam directory at /home/deck/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: redacted
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
No compatibility tool found in config.vdf. Have you enabled Steam Play for all titles under Steam settings?
Active Proton installation could not be found automatically.
```

And yes, I have also enabled Steam Play for all titles under Steam settings.

**Comment by Matoking** [comment]
Protontricks 1.8.1 has been released with a fix to Proton detection. The new version should be available on Flathub in a few hours.

The Steam Deck version of Steam uses Steam Deck compatibility profiles to determine the Proton version to use, which Protontricks didn't parse until now. Protontricks also uses the stable version of Proton as the default Proton installation in case no configuration is found whatsoever, as that appears to be what Steam defaults to as well.

Please reopen this issue if there are still any issues after updating Protontricks.
