### ISSUE TITLE
command cabextract -q -d ... returned status 1. Aborting.

### ISSUE THREAD

**Issue by agoodfellow123** [Matoking/protontricks#144]
**Describe the bug**
I'm trying to run Rise of Nations: Extended Edition but It seems that cabextract having problems to access required dll's, probably due to permissions. Here is the last output of protontricks before crashing:

`warning: Note: command cabextract -q -d /mnt/Elements/SteamLibrary/steamapps/compatdata/287450/pfx/dosdevices/c:/windows/syswow64 -L -F dmband.dll /mnt/Elements/SteamLibrary/steamapps/compatdata/287450/pfx/dosdevices/c:/windows/temp/dxnt.cab returned status 1. Aborting.`

**To Reproduce**
1. Run command `protontricks 287450 directmusic`
2. Command fails and error is displayed

**Expected behavior**
RoN: EE to run with sound.

**System (please complete the following information):**
 - Distro: Manjaro Linux
 - Protontricks installation method: AUR
 - Protontricks version: protontricks (1.8.1)
 - Steam version: Not beta

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**
https://pastebin.com/ZW7DH2gf

**Comment by Matoking** [comment]
This appears to be a duplicate of #97. Winetricks has a bug where some verbs don't work nicely with prefixes created by Proton, which is being tracked upstream at Winetricks/winetricks#1648. That thread also mentions a workaround, which does involve modifying the `winetricks` script itself.

**Comment by EstorOG** [comment]
Found an awful workaround for this without editing the winetricks script.
I changed the access permissions of the proton folder to "Can View Modify Content" for the owner, group and others.
So if you want to use proton-ge, have it properly installed and have chosen it for the game under Compatibility but winetricks errors out (when using protontricks) then do what i said previously. It worked for me somehow.

Also sorry im not a developer or anything, just found this shitty workaround by accident. Running Manjaro KDE on my pc and Endeavour OS with KDE on my laptop.

**Comment by xDieymirx** [comment]
still isn't working, your workaround no longer works as of now.

Executing cabextract -q -d /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact -L -F *_xact_*x86* /home/sean/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact -L -F *_x3daudio_*x86* /home/sean/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact -L -F *_xaudio_*x86* /home/sean/.cache/winetricks/directx9/directx_Jun2010_redist.exe
Executing cabextract -q -d /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64 -L -F xactengine*.dll /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact/*.cab
/home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact/*.cab: No such file or directory

warning: Note: command cabextract -q -d /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/syswow64 -L -F xactengine*.dll /home/sean/.local/share/Steam/steamapps/compatdata/489830/pfx/dosdevices/c:/windows/temp/_xact/*.cab returned status 1. Aborting.
