### ISSUE TITLE
pressure-vessel-launch missing from SteamLinuxRuntime_soldier

### ISSUE THREAD

**Issue by 4parthy** [Matoking/protontricks#146]
**Describe the bug**
Protonricks expects pressure-vessel-launch binary but it is missing from my SteamLinuxRuntime_soldier.

**To Reproduce**
1. Run command `protontricks <ID> corefonts`
2. Command fails and error is displayed
```sh
warning: /home/user/.cache/protontricks/proton/Proton Experimental/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "/home/user/.cache/protontricks/proton/Proton Experimental/bin/wine: line 155: /home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/pressure-vessel-launch: No such file or directory" 
```

**Expected behavior**
No error.

**System (please complete the following information):**
 - Distro: Arch Linux 5.17.5
 - Protontricks installation method: community package
 - Protontricks version: 1.8.1
 - Steam version: Beta 

**Additional context**
It fails with any protontricks command that uses pressure-vessel-launch binary, e.g.: protontricks --gui will fail as well. 

I could work around this error creating a link to steam-runtime-launch-client.

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**
Happy to provide this if necessary.

**Comment by Matoking** [comment]
The `pressure-vessel-launch` was renamed to `steam-runtime-launch-client` in the beta version of Steam Linux Runtime. I've updated Protontricks to check for both names which should fix the issue. Since you're using Arch, you can install protontricks-git from AUR to get your installation working again.

**Comment by alkaris2** [comment]
Protontricks still complains about this that the `pressure-vessel-launch` doesn't exist. This is from the AUR btw...

**Comment by ulysse42** [comment]
same here, using `cp steam-runtime-launch-client pressure-vessel-launch` in `/home/user/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/` solved the issue.

**Comment by Matoking** [comment]
**Please install `protontricks-git` instead of `protontricks` if you're using AUR, or use another installation method.**

The `protontricks` package on AUR is outdated and still on 1.8.1. That package is maintained by a community member who appears to be inactive.

**Comment by italoghost** [comment]
Thanks, @Matoking, that solved the problem!
