### ISSUE TITLE
Unable to execute winetricks desktop,gui, or cli

### ISSUE THREAD

**Issue by billybublitz** [Matoking/protontricks#147]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/home/gamer/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/home/gamer/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/cli/main.py", line 215, in main
    steam_apps = get_steam_apps(
  File "/home/gamer/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 1122, in get_steam_apps
    steam_apps += get_custom_windows_shortcuts(steam_path=steam_path)
  File "/home/gamer/.local/pipx/venvs/protontricks/lib/python3.10/site-packages/protontricks/steam.py", line 1025, in get_custom_windows_shortcuts
    appid = shortcut_data["appid"] & 0xffffffff
TypeError: unsupported operand type(s) for &: 'str' and 'int'

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/gamer/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/gamer/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 22380
Multiple compatdata directories found for app 784080
Currently logged-in Steam user: myaccount

**Comment by billybublitz** [comment]
I will try this on Monday. Thank you.

May 4, 2022 12:04:02 PM Janne Pulkkinen ***@***.***>:

**Comment by billybublitz** [comment]
/home/gamer/.steam/steam/userdata/<user id>/config/shortcuts.vdf, When going to this path and opening shortcuts.vdf
I did not find <user ID>. What I did find is alot of the shortcuts were imported links from lutris. 

I removed via the gui these applications. Now its pretty much blank. The OG error is gone now. So it does not like apps brought into steam via lutis is would seem.

So its kinda working.. protontricks --gui works now.

Now the next problem is the gui or cli does not see the app i'm actually trying to use the wrapper for.

STEAM_DIR="/home/gamer/.steam/debian-installation" protontricks 205710 d3dx9

Steam app with the given app ID could not be found.

The gui does not have it as well. I am going to try and put it on the same media as the other games quick.

**Comment by billybublitz** [comment]
Reinstalled application to same media ssd. protontricks cannot see this application. I can see my other apps though?

**Comment by billybublitz** [comment]
Oops have to open the app at least once. I did not do this with reinstall. So yea this issue is fixed. It ended up being links added into steam via lutris causing this issue.

Thanks again for the help.

**Comment by Matoking** [comment]
Thanks for finding the root cause, I was able to reproduce the same issue with Lutris' Steam shortcuts. I've pushed a fix to master.

The fix is available immediately by installing the development version, but I'll look into releasing a new version soon-ish.
