### ISSUE TITLE
Error trying to install dotnet472

### ISSUE THREAD

**Issue by hogcycle** [Matoking/protontricks#150]
**Describe the bug**
I'm trying to get Assetto Corsa working with Content Manager following [this guide](https://gist.github.com/ANBAL534/4f1693536f17b75ebcc8016e0d4cc071). When I try and run the mentioned protontricks command, it errors with status 5 - user selected 'Cancel'. Before I added --no-background-wineserver, it would hang.

**To Reproduce**
1. Run command `protontricks --no-background-wineserver 244210 -q dotnet472
2. Command fails and error 5 is displayed

**Expected behavior**
I expect protontricks to install dotnet472 in the directory specified.

**System (please complete the following information):**
 - Distro: PopOS! 22.04
 - Protontricks installation method: pipx
 - Protontricks version: 1.8.2
 - Steam version: Regular non-beta version installed through apt.
**Additional context**

The compatdata/244210 folder is in ~/fast/SteamLibrary/steam, but it seems to detect it fine. 

protontricks (INFO): Found Steam directory at /home/nate/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/nate/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 3 Steam library folders
protontricks (WARNING): Couldn't determine the currently logged-in Steam user. Custom shortcuts won't be detected.
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): User has configured app Proton version (CompatToolMapping): proton_5
protontricks (INFO): User has configured default Proton version (CompatToolMapping): proton_experimental
protontricks (INFO): Found active compatibility tool: Proton 5.0
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/nate/.cache/protontricks/proton/Proton 5.0/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Starting bwrap launcher process: /home/nate/.cache/protontricks/proton/Proton 5.0/bin/bwrap-launcher
protontricks (INFO): Attempting to run command ['/usr/bin/winetricks', '-q', 'dotnet472']
protontricks - bwrap-launcher 237654: Following directories will be mounted inside container: /boot /etc /home /lib32 /libx32 /lost+found /media /mnt /opt /root /sbin /srv /tmp
protontricks - bwrap-launcher 237654: Using temporary directory: /tmp/protontricks-dxw7tmw2
/home/nate/.cache/protontricks/proton/Proton 5.0/bin/bwrap-launcher: line 83: /run: Is a directory
/home/nate/.cache/protontricks/proton/Proton 5.0/bin/bwrap-launcher: line 83: exec: /run: cannot execute: Is a directory
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411-next - sha256sum: 60df3c20d0c2213703fe74d68ae586aed112fafac918020118054ab63c86f921 with wine-5.0-655-g2409bd1 and WINEARCH=win64
Executing w_do_call dotnet472
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet472 
------------------------------------------------------
warning: This package (dotnet472) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 241192: Checking for running wineserver instance
protontricks - wine64 241192: Found running wineserver instance with PID 237731
protontricks - wine64 241192: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 241192: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 241192: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 241192: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet462
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet462 
------------------------------------------------------
warning: This package (dotnet462) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 243342: Checking for running wineserver instance
protontricks - wine64 243342: Found running wineserver instance with PID 237731
protontricks - wine64 243342: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 243342: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 243342: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 243342: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet461
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet461 
------------------------------------------------------
warning: This package (dotnet461) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 245492: Checking for running wineserver instance
protontricks - wine64 245492: Found running wineserver instance with PID 237731
protontricks - wine64 245492: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 245492: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 245492: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 245492: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet46
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet46 
------------------------------------------------------
warning: This package (dotnet46) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 247642: Checking for running wineserver instance
protontricks - wine64 247642: Found running wineserver instance with PID 237731
protontricks - wine64 247642: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 247642: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 247642: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 247642: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet45
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet45 
------------------------------------------------------
warning: This package (dotnet45) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 249806: Checking for running wineserver instance
protontricks - wine64 249806: Found running wineserver instance with PID 237731
protontricks - wine64 249806: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 249806: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 249806: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 249806: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet40
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet40 
------------------------------------------------------
warning: This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
------------------------------------------------------
warning: dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
Executing w_do_call remove_mono
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
protontricks - wine64 251958: Checking for running wineserver instance
protontricks - wine64 251958: Found running wineserver instance with PID 237731
protontricks - wine64 251958: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 251958: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 251958: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 251958: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call winxp
Executing mkdir -p /home/nate/fast/SteamLibrary/steamapps/compatdata/244210
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_winxp 
protontricks - wine 254642: Checking for running wineserver instance
protontricks - wine 254642: Found running wineserver instance with PID 237731
protontricks - wine 254642: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine 254642: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine 254642: Starting Wine process directly, Steam runtime: legacy
protontricks - wine 254642: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

The operation completed successfully
Setting Windows version to winxp
Executing /home/nate/.cache/protontricks/proton/Proton 5.0/bin/wine regedit /S C:\windows\Temp\set-winver.reg
protontricks - wine 254797: Checking for running wineserver instance
protontricks - wine 254797: Found running wineserver instance with PID 237731
protontricks - wine 254797: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine 254797: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine 254797: Starting Wine process directly, Steam runtime: legacy
protontricks - wine 254797: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

Executing /home/nate/.cache/protontricks/proton/Proton 5.0/bin/wine64 regedit /S C:\windows\Temp\set-winver.reg
protontricks - wine64 254951: Checking for running wineserver instance
protontricks - wine64 254951: Found running wineserver instance with PID 237731
protontricks - wine64 254951: Copying env var from running wineserver: WINEESYNC=1
protontricks - wine64 254951: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wine64 254951: Starting Wine process directly, Steam runtime: legacy
protontricks - wine64 254951: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

------------------------------------------------------
warning: Running /home/nate/.cache/protontricks/proton/Proton 5.0/bin/wineserver -w. This will hang until all wine processes in prefix=/home/nate/fast/SteamLibrary/steamapps/compatdata/244210/pfx terminate
------------------------------------------------------
protontricks - wineserver 255104: Checking for running wineserver instance
protontricks - wineserver 255104: Found running wineserver instance with PID 237731
protontricks - wineserver 255104: Copying env var from running wineserver: WINEESYNC=1
protontricks - wineserver 255104: Copying env var from running wineserver: WINEFSYNC=1
protontricks - wineserver 255104: Starting Wine process directly, Steam runtime: legacy
protontricks - wineserver 255104: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

Executing cd /home/nate/.cache/winetricks/dotnet40
Executing /home/nate/.cache/protontricks/proton/Proton 5.0/bin/wine dotNetFx40_Full_x86_x64.exe /q /c:install.exe /q
protontricks - wine 255336: Checking for running wineserver instance
protontricks - wine 255336: Setting default env: WINEFSYNC=1
protontricks - wine 255336: Setting default env: WINEESYNC=1
protontricks - wine 255336: Starting Wine process directly, Steam runtime: legacy
protontricks - wine 255336: LD_LIBRARY_PATH set to /home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib:/home/nate/fast/SteamLibrary/steamapps/common/Proton 5.0/dist/lib64:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_32:/home/nate/.steam/root/ubuntu12_32/steam-runtime/pinned_libs_64:/usr/lib/x86_64-linux-gnu/libfakeroot:/lib/i386-linux-gnu:/usr/local/lib:/usr/lib/x86_64-linux-gnu/pipewire-0.3/jack:/lib/x86_64-linux-gnu:/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/i386-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib/x86_64-linux-gnu:/home/nate/.steam/root/ubuntu12_32/steam-runtime/lib:/home/nate/.steam/root/ubuntu12_32/steam-runtime/usr/lib

esync: up and running.
0034:fixme:msvcrt:_configure_wide_argv (1) stub
0034:fixme:msvcrt:_initialize_wide_environment stub
0078:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0058), starting debugger...
003c:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
003c:err:service:process_send_start_message pipe connect failed
003c:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
0024:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0024:fixme:process:SetProcessDEPPolicy (3): stub
0024:fixme:clusapi:OpenCluster ((null)) stub!
0024:fixme:clusapi:ClusterOpenEnum (DEADBEEF, 4) stub!
0024:fixme:clusapi:ClusterEnum (DEADBEEF, 0, 0031F920, 00655F90, 261) stub!
0024:fixme:clusapi:ClusterCloseEnum (DEADBEEF) stub!
0024:fixme:clusapi:CloseCluster (DEADBEEF) stub!
------------------------------------------------------
warning: exit status 5 - user selected 'Cancel'
------------------------------------------------------
protontricks (INFO): Terminating launcher process 237654
protontricks (INFO): Launcher process terminated

**Comment by Matoking** [comment]
I checked and Protontricks shouldn't hang when background wineserver is in use, nor should it automatically use background wineserver in this case. I've pushed a fix to `fix_bwrap_launcher` fix which you can install like this:

```
$ pipx install --force git+https://github.com/Matoking/protontricks.git@fix_bwrap_launcher
```

Can you check if that fixes the issue with the hang?

---

As for the dotnet472 installation specifically, you will have to delete the prefix as instructed in the guide (delete the prefix, start the game in Steam to ensure the prefix is created, then run Protontricks) and then try the installation again.

**Comment by Matoking** [comment]
I've tested and pushed the bwrap fix to master. Feel free to reopen the issue if you're still encountering the problem, though it may be out of scope for Protontricks depending on the exact cause.

**Comment by hogcycle** [comment]
hey sorry for the late response, I'm just coming back to this now. Going to try it with the new patch and get back to you on that.

**Comment by hogcycle** [comment]
same issue on version 1.9.0, "exit status 5 - user selected 'Cancel'" error after a fresh start and a new 244210 folder. logs look to be the same at a glance.
