### ISSUE TITLE
flatpak on steamdeck not working

### ISSUE THREAD

**Issue by cimba007** [Matoking/protontricks#152]
After selecting a game in the GUI an error regarding 64 but pops up and nothing after this.

**Comment by Matoking** [comment]
The "You are using a 64-bit WINEPREFIX" error is expected and can be ignored.

If nothing pops up after that warning (there should be a dialog with error logs if Protontricks crashed), then we'll need to run Protontricks in desktop mode. Once you're in desktop mode, open Konsole and run the following command:

```
flatpak run com.github.Matoking.protontricks -v --gui
```

Once the command either crashes or hangs, copy the output here.

**Comment by cimba007** [comment]
`(deck@steamdeck ~)$ flatpak run com.github.Matoking.protontricks -v --gui
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.4.
protontricks (INFO): Found Steam directory at /home/deck/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/deck/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: c***.de
protontricks (INFO): Found 8 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): User has configured app Proton version (CompatToolMapping): proton_experimental
protontricks (INFO): Found active compatibility tool: Proton Experimental
protontricks (INFO): Active compatibility tool is a Proton installation
protontricks (INFO): Using separately installed Steam Runtime: Steam Linux Runtime - Soldier
protontricks (INFO): Running Steam Runtime using bwrap containerization.
If any problems arise, please try running the command again using the `--no-bwrap` flag and make an issue report if the problem only occurs when bwrap is in use.
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version.
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Starting bwrap launcher process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/bwrap-launcher
protontricks (INFO): Starting wineserver keepalive process: /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton Experimental/bin/wineserver-keepalive
protontricks (INFO): Attempting to run command ['/app/bin/winetricks', '--gui']
protontricks - bwrap-launcher 15: Following directories will be mounted inside container: /app /etc /home /sbin /tmp
protontricks - bwrap-launcher 15: Using temporary directory: /tmp/protontricks-rh2ee9qi
protontricks - wineserver-keepalive 16: Starting wineserver-keepalive process...

(process:45): Gtk-WARNING **: 23:11:06.521: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 23:11:06.522: Failed to load module "canberra-gtk-module"
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/deck/.steam/steam/steamapps/compatdata/3507367410
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------

(process:1718): Gtk-WARNING **: 23:11:15.160: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 23:11:15.163: Failed to load module "canberra-gtk-module"

** (zenity:1718): WARNING **: 23:11:15.300: AT-SPI: Could not obtain desktop path or name


** (zenity:1718): WARNING **: 23:11:15.313: AT-SPI: Could not obtain desktop path or name


** (zenity:1718): WARNING **: 23:11:15.314: atk-bridge: get_device_events_reply: unknown signature

** (zenity:1718): WARNING **: 23:11:15.314: atk-bridge: get_device_events_reply: unknown signature

** (zenity:1718): WARNING **: 23:11:15.314: atk-bridge: GetRegisteredEvents returned message with unknown signature

** (zenity:1718): WARNING **: 23:11:15.327: AT-SPI: Could not obtain desktop path or name


** (zenity:1718): WARNING **: 23:11:15.327: atk-bridge: get_device_events_reply: unknown signature

** (zenity:1718): WARNING **: 23:11:15.327: atk-bridge: get_device_events_reply: unknown signature

** (zenity:1718): WARNING **: 23:11:15.328: atk-bridge: GetRegisteredEvents returned message with unknown signature
Using winetricks 20220411 - sha256sum: 69856050cfe9d97902dfd68c1ad42a10a4be0fe76660744126d7e3ed75610495 with wine-7.0 and WINEARCH=win64

(process:2638): Gtk-WARNING **: 23:11:23.753: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 23:11:23.756: Failed to load module "canberra-gtk-module"
This option is not available. Please see --help for all possible usages.
protontricks (INFO): Terminating wineserver keepalive process 16
protontricks (INFO): Terminating launcher process 15
protontricks (INFO): Launcher process terminated
protontricks - wineserver-keepalive 16: Cleanup finished, goodbye!
(deck@steamdeck ~)$ 

`

**Comment by cimba007** [comment]
Now it's working after reverting 
Regional settings, formats back to default (c)

**Comment by Matoking** [comment]
Good to hear that, closing the issue.
