### ISSUE TITLE
[Feature Request] Add an obvious and easy way to list all apps/prefixes from the command line

### ISSUE THREAD

**Issue by IBNobody** [Matoking/protontricks#155]
Currently, there is no obvious way to list all apps on the command line like their is with the GUI.

There is a way to list all apps (`protontricks -s .`), but it is not obvious that the command accepts regular expression wildcards.

I would like to propose one of the following:

1. Update the search help to indicate that . can be used as a wildcard. `Search for game(s) with the given name, or use . to list all games`
2. Update the search command to default to running  with a . if no search args are given.
3. Add a -l / --list command that does something similar to search.

**Comment by Matoking** [comment]
Good point, I've added the `-l/--list` flag to list all apps. For now you'll have to install the development version, though I'll look into publishing a new version once I've looked into a few other active issues.

**Comment by HalJordan** [comment]
Why reinvent the wheel too much? If you can just list all, system utilities like awk/grep and the like can easily search what you provide.

**Comment by Matoking** [comment]
`protontricks -s <name>` is a long established command and not very complex to maintain. Removing it would break backwards compatibility and cause user confusion, which I don't think would be a good trade-off.

I also suspect many Protontricks users are casual users, and not accustomed to Linux concepts such as pipes and common utilities such as `grep`. For comparison, `protontricks -s hypnospace outlaw` does what the user expects without any issues, while `protontricks -l | grep hypnospace outlaw` doesn't, and the reason why would not be apparent to a beginner.
