### ISSUE TITLE
How to access protontricks-launch in a flatpak install

### ISSUE THREAD

**Issue by rockerbacon** [Matoking/protontricks#160]
Is there a way to execute protontricks-launch using the flatpak package? I couldn't find any documentation on how to do it.

**Comment by Matoking** [comment]
Yes, `flatpak-run` accepts the `--command` parameter, meaning the following will do the trick:

```
flatpak run --command=protontricks-launch com.github.Matoking.protontricks <rest of the command here>
```

You can also open EXE files with "Protontricks Launcher" when using graphical file managers.

I've updated the Flatpak instructions accordingly.

**Comment by Valkyrien04** [comment]
Sorry to Necro this issue but this setting has disappeared from the flatpak install instructions and should be re-added
