### ISSUE TITLE
Cannot find installed, launched, and Proton-compatible Steam game

### ISSUE THREAD

**Issue by alex-dumas** [Matoking/protontricks#162]
**Describe the bug**
I installed this version of protontricks using flatpak. When I try to ask it to search for my game (Fallout New Vegas) it can't find it, saying "Steam app with the given app ID could not be found". I also tried using the search with just a letter from the game's name and even that didn't work.

I know the game is Proton-compatible, I'm using a compatible version of Proton, I've launched the game at least once, and I've used `flatpak override` to give it access to the steam library folder the game is in. 

**To Reproduce**
1. Run command `protontricks -s Fallout`
2. Command fails and error is displayed

**Expected behavior**
I expect the search to be able to find Fallout New Vegas.

**System (please complete the following information):**
 - Distro: PopOS 22.04
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.9.0
 - Steam version: not participating in the beta

**Additional context**

I'm using protontricks in the context of using the linux Mod Organizer 2 installer found here: https://github.com/rockerbacon/modorganizer2-linux-installer

```
$ protontricks -v -s F
protontricks (INFO): Running inside Flatpak sandbox, version 1.12.7.
protontricks (INFO): Found Steam directory at /home/alexis/.var/app/com.valvesoftware.Steam/data/Steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/alexis/.var/app/com.valvesoftware.Steam/data/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-pictures', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-music', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-videos', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-download', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-documents', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-desktop', ignoring.
protontricks (INFO): Currently logged-in Steam user: christopher_dumas
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
Found no games.

NOTE: A game must be launched at least once before Protontricks can find the game.
```

**Comment by alex-dumas** [comment]
My game is in `/home/{user}/storage/SteamLibrary/`

**Comment by Matoking** [comment]
Protontricks prioritizes the Flatpak version of Steam, so if you have installed Steam using Flatpak and also using your distro's package manager, it will look for games installed by Steam Flatpak.

Does the following command find the correct library folder?

```
$ STEAM_DIR=/home/<user>/.steam/steam protontricks -v -s F
```

**Comment by alex-dumas** [comment]
> Protontricks prioritizes the Flatpak version of Steam, so if you have installed Steam using Flatpak and also using your distro's package manager, it will look for games installed by Steam Flatpak.
> 
> Does the following command find the correct library folder?
> 
> ```
> $ STEAM_DIR=/home/<user>/.steam/steam protontricks -v -s F
> ```

Yes, it does! Even though I don't actually have the flatpak version of steam installed I'm pretty sure. Huh. Let me just add that environment variable to my shell config and see if that makes everything work.

**Comment by alex-dumas** [comment]
Now the installer still eventually crashes, but at a much later point and with no obvious/visible error in the terminal.

**Comment by alex-dumas** [comment]
Turns out I was aliasing `wine64` to use a specific prefix. With that taken out, the installer runs perfectly!

**Comment by Matoking** [comment]
This isn't the first time this has caused confusion. I went ahead and made a small change so that Protontricks prints a warning when multiple Steam directories are found, instructing the user how to change it if the first one isn't the correct one.
