### ISSUE TITLE
Cannot run protontricks for Steins; Gate 0 on steam deck

### ISSUE THREAD

**Issue by ramarivera** [Matoking/protontricks#165]
**Describe the bug**
Cannot run protontricks for Steins; Gate 0 on steam deck (using protontricks (1.9.1))

**To Reproduce**
1. Run command `protontricks -f --gui`
2. Pick Steins Gate 0
3. Error shows up

**Expected behavior**
Winetricks window to show up

**System (please complete the following information):**
 - Distro:  Arch Linux
 - Protontricks installation method: Flatpak, latest (test) version due to normal version not working on deck
 - Protontricks version: 1.9.1
 - Steam version: Beta

**Additional context**
```
/home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/GE-Proton7-31/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "protontricks - wine 444: Found Steam Runtime launch client at /home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier/pressure-vessel/bin/steam-runtime-launch-client
protontricks - wine 444: Checking for running wineserver instance
protontricks - wine 444: Setting default env: WINEFSYNC=1
protontricks - wine 444: Setting default env: WINEESYNC=1
protontricks - wine 444: Starting Wine process using 'pressure-vessel-launch'
/bin/bash: /usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/libtinfo.so.6: no version information available (required by /bin/bash)
protontricks - wine 461: Starting Wine process inside the container
protontricks - wine 461: Appending to LD_LIBRARY_PATH: /home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-31/files/lib:/home/deck/.local/share/Steam/compatibilitytools.d/GE-Proton7-31/files/lib64:" 
```

**Comment by Matoking** [comment]
Sorry for the late reply.

Can you try again with 1.9.2? There were a few bugs in the old version causing crashes that could well explain this crash.

If that doesn't fix it, please run again `protontricks -v --gui` and copy the full log.

**Comment by ramarivera** [comment]
Thanks! Working now with 1.9.2
