### ISSUE TITLE
Unable to run winecfg on Steam Deck

### ISSUE THREAD

**Issue by Dwismas** [Matoking/protontricks#166]
I am trying to mod a game through Bepinex following this guide: https://docs.bepinex.dev/articles/advanced/proton_wine.html
When I try to select "run winecfg", the window closes, and then reopens. I am assuming that the winecfg window breaks in some way and the previous window reopens in response.
FYI I am using an alternative build with D-Bus enabled through Flatseal to get this to work on the Deck (https://github.com/flathub/com.github.Matoking.protontricks/pull/31#issuecomment-1234733878)

Steps to reproduce the behavior: (I am using the gui)
1. Open Protontricks
2. Select any game
3. Select default wine prefix
4. Select "run winecfg"
5. Watch the window close and reopen

**Expected behavior**
I should be able to see and configure winecfg

**System (please complete the following information):**
 - Distro: SteamOS 3.3.1
 - Platform: Steam Deck
 - Steam version: Steam Deck Stable

**Comment by Matoking** [comment]
Copying relevant comment from #164:

> > So winecfg and the gui worked. Regedit, explorer, taskmanager just return to the previous menu. Maybe my issue is the test build didn't completely download? 2mb of 16. All in the Gist: https://gist.github.com/guymanley/8abbcffcd87f408d2c516d89f9b71187 I used the discover app to remove protontricks before replacing test builds.
> > I should clarify, the gist shows me installing the test build you posted lastly twice because I thought it failed the first time and uninstalled via discover, which is not shown in the gist. When the same behavior happened on the 2nd attempt to install, I just decided to move on with testing. I was able to edit a dll in Resident Evil 4 HD and remove the launch command override that did the same function so winecfg at least is working. Not sure how much else is not working.
> 
> I was able to reproduce the issue on Proton 7.0, but not Proton 6.3 using the following method:
> 
> ```
> # Open two terminal emulators.
> # On the first one, open a Windows command prompt, and leave it open. This will ensure a wineserver process is left open.
> $ protontricks -v --no-background-wineserver -c bash APPID
> $ wine cmd.exe 
> 
> # On the second one, open Winetricks GUI as normal, then select winecfg, close it, and open winecfg again.
> # It should crash with the same error.
> $ protontricks -v --no-background-wineserver APPID --gui
> ```
> 
> My guess is it's related to the recent Steam Runtime update since `--no-bwrap` also fixes the issue, but I'll have to look into this more. Protontricks 1.9.0 and non-Flatpak environment also trigger the same error.

**Comment by Matoking** [comment]
I've looked into this issue and managed to reproduce it on just Steam Runtime Soldier + Proton 7.0, which leads me to believe it's a bug with either of the two projects. I've submitted an upstream bug report here:

https://github.com/ValveSoftware/steam-runtime/issues/529

**Comment by MattyXarope** [comment]
> I've looked into this issue and managed to reproduce it on just Steam Runtime Soldier + Proton 7.0, which leads me to believe it's a bug with either of the two projects. I've submitted an upstream bug report here:
> 
> [ValveSoftware/steam-runtime#529](https://github.com/ValveSoftware/steam-runtime/issues/529)

is there a workaround meanwhile?

**Comment by Matoking** [comment]
> > I've looked into this issue and managed to reproduce it on just Steam Runtime Soldier + Proton 7.0, which leads me to believe it's a bug with either of the two projects. I've submitted an upstream bug report here:
> > [ValveSoftware/steam-runtime#529](https://github.com/ValveSoftware/steam-runtime/issues/529)
> 
> is there a workaround meanwhile?

You can disable bwrap using `--no-bwrap`, which prevents bwrap based Steam Runtime from being used.

**Comment by RadiantMorningstar** [comment]
WHY HAS THIS CRIPPLING ISSUE GONE UNFIXED FOR OVER A MONTH??????

**Comment by Matoking** [comment]
I've investigated the issue a few times, and determined some things:

* The issue can be reproduced on Ubuntu 22.04, but not on Ubuntu 21.10. I've tried bisecting the issue further by looking at the package versions on both distros, determining which have changed and testing corresponding older packages on Arch Linux, but I haven't been able to pinpoint the broken package this way.
  * I made a list of packages on both systems and ran them through Kompare to determine the differences; you can find the package lists [here](https://gist.github.com/Matoking/999df185b4ca68bca00f864aec2378d6).
  * I'll try to look into bisecting the issue in a different way. Installing an older Arch in an VM using [Arch Linux Archive](https://wiki.archlinux.org/title/Arch_Linux_Archive#How_to_restore_all_packages_to_a_specific_date) and gradually upgrading the packages to newer versions might help bisect the issue better when multiple packages are involved.
* The issue happens regardless of the desktop environment, so probably related to the X11 compositor or related components.

Any help with this would be appreciated.

**Comment by Matoking** [comment]
This has been fixed in 1.10.3 by disabling `background-wineserver` by default. While this increases Wine command launch time somewhat, the launch time seems to have improved to a point where it's no longer a problem: 10 seconds for `protontricks <appid> good` with `background-wineserver` vs 20 seconds without, most of it spent in Winetricks startup.

The background Wineserver also seems to be responsible for the problem with broken output, although I haven't been able to determine exactly why. In any case, disabling it by default seems to be a no-brainer at this point considering these two longstanding issues.
