### ISSUE TITLE
Protontricks refuses to start

### ISSUE THREAD

**Issue by Espio419** [Matoking/protontricks#170]
All I get is this lousy error on the Flatpak installation with Linux Mint 21

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.9/site-packages/protontricks/cli/util.py", line 148, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/app/lib/python3.9/site-packages/protontricks/cli/main.py", line 228, in main
    steam_apps = get_steam_apps(
  File "/app/lib/python3.9/site-packages/protontricks/steam.py", line 1106, in get_steam_apps
    if not path.is_dir():
  File "/usr/lib/python3.9/pathlib.py", line 1439, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.9/pathlib.py", line 1232, in stat
    return self._accessor.stat(self)
PermissionError: [Errno 13] Permission denied: '/media/denton/2nd Disk/SteamLibrary'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.12.7.
Found Steam directory at /home/denton/.local/share/Steam
Using Steam directory at /home/denton/.local/share/Steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/denton/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders

**Comment by Matoking** [comment]
Have you added the directory to the list of allowed directories per these [Flatpak-specific instructions](https://github.com/flathub/com.github.Matoking.protontricks#configuration):

> By default, Protontricks only has access to the Steam installation directory. You will need to add filesystem permissions for additional Steam library locations, and other directories when running external EXEs.
> 
> In order to grant access to other directories, you can use the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) graphical utility or the flatpak override command (eg. `flatpak override --user --filesystem=<PATH> com.github.Matoking.protontricks`) to grant access to other directories.
>
> For example, to grant access to `/mnt/MySSD/SteamLibrary`, you can run the following command:
>
> `flatpak override --user --filesystem=/mnt/MySSD/SteamLibrary com.github.Matoking.protontricks`

Protontricks should warn in case it lacks permission to one of the Steam library folders. Please check if adding it manually fixes the issue.

**Comment by Espio419** [comment]
> Have you added the directory to the list of allowed directories per these [Flatpak-specific instructions](https://github.com/flathub/com.github.Matoking.protontricks#configuration):
> 
> > By default, Protontricks only has access to the Steam installation directory. You will need to add filesystem permissions for additional Steam library locations, and other directories when running external EXEs.
> > In order to grant access to other directories, you can use the [Flatseal](https://flathub.org/apps/details/com.github.tchx84.Flatseal) graphical utility or the flatpak override command (eg. `flatpak override --user --filesystem=<PATH> com.github.Matoking.protontricks`) to grant access to other directories.
> > For example, to grant access to `/mnt/MySSD/SteamLibrary`, you can run the following command:
> > `flatpak override --user --filesystem=/mnt/MySSD/SteamLibrary com.github.Matoking.protontricks`
> 
> Protontricks should warn in case it lacks permission to one of the Steam library folders. Please check if adding it manually fixes the issue.

Adding the directory doesn't make a difference. I fixed it by deleting that Steam library folder through Steam since it was empty.
