### ISSUE TITLE
protontricks (WARNING): Unknown Flatpak file system permission

### ISSUE THREAD

**Issue by minimeee** [Matoking/protontricks#180]
**Describe the bug**
I've installed `protontricks` through `Flatpak 1.12.7`  on my ubuntu 22.04 installation and every command starts with the following warnings:
```
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-pictures', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-music', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-videos', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-download', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-documents', ignoring.
protontricks (WARNING): Unknown Flatpak file system permission 'xdg-desktop', ignoring.
```
What do they mean and how can I get rid of them? I couldn't find anything helpful on the internet.

**To Reproduce**
1. Run any `protontricks` command

**Expected behavior**
No warnings.

**System (please complete the following information):**
 - Distro: Ubuntu 22.04
 - Protontricks installation method: flatpak
 - Protontricks version: `1.9.2`

**Comment by Matoking** [comment]
The warnings can be safely ignored. Protontricks doesn't support some of the filesystem permissions Flatpak has, but in practice this is not a problem unless you modify the application's permissions manually. In this case Protontricks wouldn't be able to detect that it has permission to access the directory, and instead prompt to grant access to the directory a second time.

I'll probably make the warning less noisy and fix the missing support, as it's confusing and not very helpful at the moment.

**Comment by minimeee** [comment]
> I'll probably make the warning less noisy and fix the missing support, as it's confusing and not very helpful at the moment.

And also, on my system the warnings are longer than the actual output of `protontricks -l`. Fixing this would be nice :+1:

**Comment by Matoking** [comment]
Fix has been pushed to master and will be included in the release.
