### ISSUE TITLE
Found no games. You need to launch a game at least once before Protontricks can find it.

### ISSUE THREAD

**Issue by Bboy486** [Matoking/protontricks#181]
[protontricks.txt](https://github.com/Matoking/protontricks/files/9986144/protontricks.txt)
Using default Steam Runtime at /home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Unknown Flatpak file system permission 'xdg-pictures', ignoring.
Unknown Flatpak file system permission 'xdg-music', ignoring.
Unknown Flatpak file system permission 'xdg-videos', ignoring.
Unknown Flatpak file system permission 'xdg-download', ignoring.
Unknown Flatpak file system permission 'xdg-documents', ignoring.
Unknown Flatpak file system permission 'xdg-desktop', ignoring.
Couldn't determine the currently logged-in Steam user. Custom shortcuts won't be detected.

**Comment by Matoking** [comment]
You seem to have installed the Flatpak version of Steam, while you should already have Steam installed since you're on a Steam Deck. Protontricks defaults to the Flatpak version if it is available.

If that's the case, you should be able to uninstall it using the Discover app store.

**Comment by Bboy486** [comment]
Hi. 

I'm using the default steam OS as I haven't made changes to steam. So I'm not sure I'm following the issue. There is no steam installed in the discover store.

**Comment by Matoking** [comment]
The following message seems to state the opposite:

```
Found multiple Steam directories. If you want to select a specific installation, use STEAM_DIR environment variable to set the correct directory:
$ STEAM_DIR=<path> protontricks <appid> <command>
The following Steam directories were found:
 /home/deck/.var/app/com.valvesoftware.Steam/.local/share/Steam
 /home/deck/.local/share/Steam
```

To be fair, the message isn't as prominent as it should be, and it would be a better idea to prompt the user with a dialog instead of requiring that the user change the environment variable manually on the command line. I'll look into improving this.

**Comment by Bboy486** [comment]
Thank you. I am not sure why it is staying that. Is there a way to have it look at the installed steam locations or not have this be a blocker? Since I didn't install a flatpak for steam I am at a lose how to proceed

**Comment by Matoking** [comment]
I'm working on an improvement for Protontricks where it will prompt you to select the installation in case multiple are found. The current command-line solution isn't very user friendly.

For now, if you don't have the Flatpak version of Steam installed (looks to be very likely), you can remove the directory yourself. If you're using the desktop mode, you can open the Dolphin file manager, click the header and then enter the following path:

```
/home/deck/.var/app
```

You should then see `com.valvesoftware.Steam` among the directories. Delete it or rename it to something else, and Protontricks should now detect only one installation.

**Comment by Bboy486** [comment]
Thanks. That worked!

**Comment by Matoking** [comment]
Glad to hear the problem was solved.

I've implemented a selection dialog for the Steam installation when multiple installations are found. I've pushed it to master, and it should be available in the next release.

**Comment by Bboy486** [comment]
Would that include when you have your steam games moved on the SD card as well as the SSD?
