### ISSUE TITLE
SyntaxError: Invalid file magic number with protontricks from AUR

### ISSUE THREAD

**Issue by CygnusTerminal** [Matoking/protontricks#189]
**Describe the bug**
Whenever i select a game from protontricks --gui or directly doing protontricks appid winecfg, it fails with `SyntaxError: Invalid file magic number`

**To Reproduce**
1. Run command `protontricks appid winecfg`
2. Command fails and error is displayed

**Expected behavior**
I expect protontricks to open winecfg for the game i am trying to tweak.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: AUR
 - Protontricks version: protontricks (1.10.1.dev1+g11eb97e)
 - Steam version: Beta

**Additional context**
protontricks (INFO): Found Steam directory at /home/voivod/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/voivod/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Currently logged-in Steam user: soulsofblack5
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.10/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/protontricks/cli/main.py", line 328, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 756, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 544, in find_steam_compat_tool_app
    appinfo_sections = [
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 544, in <listcomp>
    appinfo_sections = [
  File "/usr/lib/python3.10/site-packages/protontricks/steam.py", line 452, in iter_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

**Comment by noxinias** [comment]
Hello soulsofblack/cygnus, I ran into this issue exactly the same time you did tonight. I was able to resolve it by returning to Steam stable version rather than beta, it appears the format of vdf has changed and the magic isn't valid any more. I tried to make it ignore the magic, but later on issue with structure size occurs, and will need a update later on if this beta change goes to live.

**Comment by cameronbosch** [comment]
Can confirm this is also happening with the Steam Deck. Exactly the same "magic number" error. Is there an ETA on the fix? (No pressure.)

**Comment by rptorres22** [comment]
just chiming in as i got this same error. happens with any game selected (non-steam games and steam games).

**Comment by CygnusTerminal** [comment]
> Hello soulsofblack/cygnus, I ran into this issue exactly the same time you did tonight. I was able to resolve it by returning to Steam stable version rather than beta, it appears the format of vdf has changed and the magic isn't valid any more. I tried to make it ignore the magic, but later on issue with structure size occurs, and will need a update later on if this beta change goes to live.

Hi, thanks for chiming in! I will go back to Stable for the time being, thanks for your help!

**Comment by Matoking** [comment]
The new Steam beta introduced a new version of appinfo.vdf.

1.10.1 has been released with a fix. The Flatpak app should receive this update shortly.
