### ISSUE TITLE
Change steam library location

### ISSUE THREAD

**Issue by yes714** [Matoking/protontricks#190]
Hi, I got an permission error when using a steam library on a disk that was mounted in 'media' made using ubuntu disk management tool, I deleted this mount/partition and make a manual one with fstab record, but now when I run protontricks I get the same error because it is still looking for the old location on ' media' .
How can I change the location to the new steam library? Thank you

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 181, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 1003, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 214, in from_appmanifest
    prefix_path = find_appid_proton_prefix(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 582, in find_appid_proton_prefix
    if prefix_path.is_dir():
  File "/usr/lib/python3.10/pathlib.py", line 1305, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "/usr/lib/python3.10/pathlib.py", line 1097, in stat
    return self._accessor.stat(self, follow_symlinks=follow_symlinks)
PermissionError: [Errno 13] Permission denied: '/media/user/002809D22809C81C/SteamLibrary/steamapps/compatdata/228980/pfx'

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/user/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/user/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 5 Steam library folders
Steam library folder /media/user/002809D22809C81C1/SteamLibrary not found. Protontricks might not have access to the directory.

**Comment by yes714** [comment]
I found the solution, find the file "libraryfolders.vdf" in /.steam/steam/steamapps and remove the old references.

**Comment by Matoking** [comment]
I've updated Protontricks to handle missing permissions more gracefully in several places, which makes sense since Steam ignores inaccessible library folders as well. The fix will be available in a future release.
