### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by sputniktr02** [Matoking/protontricks#2]
Hi, i am getting an error when i try to launch winecfg for games. Protontricks can find games when i search them but gives following error when i try to launch winecfg or winetricks gui:

> user@user-pc:~$ protontricks -s stalker

> Found the following games:
S.T.A.L.K.E.R.: Call of Pripyat (41700)
S.T.A.L.K.E.R.: Clear Sky (20510)
S.T.A.L.K.E.R.: Shadow of Chernobyl (4500)
To run protontricks for the chosen game, run:
$ protontricks APPID COMMAND
NOTE: A game must be launched at least once before protontricks can find the game.

> user@user-pc:~$ protontricks 41700 winecfg

> Traceback (most recent call last):
File "/usr/local/bin/protontricks", line 11, in <module>
load_entry_point('protontricks==1.1.1+3.g06c86eb', 'console_scripts', 'protontricks')()
File "/usr/local/lib/python3.6/dist-packages/protontricks/cli.py", line 137, in main
steam_path=steam_path, steam_apps=steam_apps, appid=args.appid)
File "/usr/local/lib/python3.6/dist-packages/protontricks/steam.py", line 293, in find_proton_app
steam_path=steam_path, steam_apps=steam_apps, appid=appid)
File "/usr/local/lib/python3.6/dist-packages/protontricks/steam.py", line 254, in find_steam_proton_app
proton_appid = re.search(appid_regex, appinfo).group(2)
AttributeError: 'NoneType' object has no attribute 'group'

- My games are located on 2 external libraries.
- I have winetricks installed.
- My os is Kubuntu 18.10

**Comment by Matoking** [comment]
Hi,

What is the output when running the command `protontricks -v 41700 winecfg`?

Have you set a custom Proton version for this specific game, or are you using a global Proton version? You can find the Proton version in use through Steam's menu bar: Steam -> Settings -> Steam Play -> Run other titles with.

**Comment by sputniktr02** [comment]
@Matoking  Yes i was using a custom build of Proton, disabling it and selecting an official version solved the problem. Is there a way to use custom Proton versions with Protonticks? Thanks for your help.

**Comment by Matoking** [comment]
Custom Proton versions should be supported by Protontricks, meaning there's a bug with Protontricks if Steam can run the game fine with a custom Proton version, but Protontricks can't detect it properly.

Do you have the custom Proton installed in `/home/<username>/.steam/steam/compatibilitytools.d/<custom Proton name>`? Is there a `compatibilitytool.vdf` file inside that directory, or is there a different `vdf` file inside the parent directory `/home/<username>/.steam/steam/compatibilitytools.d` instead? In either case, can you post the content of the `vdf` file?

**Comment by sputniktr02** [comment]
Custom Proton that i am using is located in:

`/home/username/.steam/steam/compatibilitytools.d/wine-proton/`

![screenshot_20190219_174745](https://user-images.githubusercontent.com/31340272/53023695-c5bc2700-346e-11e9-8672-cec123e3c166.jpg)


**compatibilitytool.vdf** is in that directory

Here is the content of .vdf:

```
"compatibilitytools"
{
  "compat_tools"
  {
    "proton-localbuild" // Internal name of this tool
    {
      // Can register this tool with Steam in two ways:
      //
      // - The tool can be placed as a subdirectory in compatibilitytools.d, in which case this
      //   should be '.'
      //
      // - This manifest can be placed directly in compatibilitytools.d, in which case this should
      //   be the relative or absolute path to the tool's dist directory.
      "install_path" "."

      // For this template, we're going to substitute the display_name key in here, e.g.:
      "display_name" "Proton 4.0 Unofficial"

      "from_oslist"  "windows"
      "to_oslist"    "linux"
    }
  }
}
```
I just renamed display name for better readability.

**Comment by Matoking** [comment]
Alright, I'm pretty sure I found the issue. Please install the latest version and see if the command works now.

**Comment by sputniktr02** [comment]
@Matoking Yes it is working now, however i needed to reboot my pc after updating Protontricks, it was showing the same error when i first tried, then i noticed it was still showing the older version of Protontricks.

Thanks, that was quick :)

**Comment by Matoking** [comment]
Great, thanks for the help. :+1:
