### ISSUE TITLE
Running protontricks returns "Steam installation directory could not be found."

### ISSUE THREAD

**Issue by xray-tango** [Matoking/protontricks#203]
**Describe the bug**
A few days ago protontricks crashed while installing dotnet for a pfx. 
As a result it is no longer able to to locate my steam installation directory, even if i manually point it to it.
I have tried to fully reinstall steam by deleting everything except my common and workshop folders and i have tried to run every available version of protontricks but i still get the same error 

**Expected behavior**
protontricks recognizing the steam installation directory and working as usual

**System**
 - Distro: Up to date 2+ year old Manjaro installation
 - Protontricks installation method: pacman package, aur package and pip installation all produce this bug
 - Protontricks version: 1.10.1
 - Steam version: opted out of all beta

**Additional context**

running "-v" does not produce any extra log.
Running the flatpak version of both steam and protontricks works fine, however it's extremely inconvenient to juggle the pfx folder between steam installations.

I don't know what else to add, I've been trying to find the cause of this problem for over 3 days with no luck.

**Comment by Matoking** [comment]
Protontricks will try to find Steam installations from the following directories:

```
~/.steam/steam/steamapps
~/.steam/steam/SteamApps
~/.local/share/Steam/steamapps
~/.local/share/Steam/SteamApps
```

Do any of these directories exist on your system? If not, where is the `steamapps` directory located? Given that you're on Manjaro, I would expect the directories be the same as on my Arch installation.

**Comment by xray-tango** [comment]
as it turns out the last steam beta named my steamapps folder "Steamapps" with a capital S and every other character lower case. This was the cause of my problem.
Maybe try to add "Steamapps" in the list of folders that is checked.

**Comment by Matoking** [comment]
I tested this a bit, and while it doesn't look like Steam itself creates directories exactly with the `Steamapps` capitalization, it treats that (as well as any other variation) without any issues, as long as it's the only directory in that location. I've fixed the directory detection to take this into account.
