### ISSUE TITLE
Can't seem to install dotnet40 + dotnet48

### ISSUE THREAD

**Issue by SonicdomXD** [Matoking/protontricks#206]
Hello, this is my first time describing an issue on this platform so I will try my best to make sure things make sense.

So there I was, trying to install mods for Sonic Frontiers on my steam deck (for some reason). It told me that I needed to install dotnet40 and dotnet48, but for some reason I got this message

You are running winetricks-20220411, latest upstream is winetricks-20230212

It also says that I should update using my distribution's package manager, --self-update, or manually

I then proceeded with the process, but then it just stopped

I'm not sure what I can do with this, and I am not a linux expert (even though I own a steam deck, so take that with a grain of salt).

If there is a way of fixing this issue, please let me know. Thank you.

From, a steam deck user who has no idea on what he is doing

P.S: I also happened to contact the mono does not appear to be installed error

P.P.S: Here is my full report: 

------------------------------------------------------
warning: You are running winetricks-20220411, latest upstream is winetricks-20230212!
------------------------------------------------------
------------------------------------------------------
warning: You should update using your distribution's package manager, --self-update, or manually.
------------------------------------------------------
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20220411 (protontricks) - sha256sum: 5e3bfa65413d539e07e4f3de3dabb7357586ef05a44c004cb261473e8dd144f9 with wine-5.0-655-g2409bd1 and WINEARCH=win64
Executing w_do_call dotnet48
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet48 
------------------------------------------------------
warning: This package (dotnet48) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
grep: warning: stray \ before /
Executing w_do_call remove_mono
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
fsync: up and running.
007c:err:module:map_image Could not map section .rsrc, file probably truncated
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0064), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call dotnet40
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_dotnet40 
------------------------------------------------------
warning: This package (dotnet40) may not fully work on a 64-bit installation. 32-bit prefixes may work better.
------------------------------------------------------
------------------------------------------------------
warning: dotnet40 does not yet fully work or install on wine.  Caveat emptor.
------------------------------------------------------
grep: warning: stray \ before /
Executing w_do_call remove_mono
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_remove_mono 
fsync: up and running.
0084:err:module:map_image Could not map section .rsrc, file probably truncated
0084:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 006c), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
------------------------------------------------------
warning: Mono does not appear to be installed.
------------------------------------------------------
Executing w_do_call winxp
Executing mkdir -p /home/deck/.local/share/Steam/steamapps/compatdata/1237320
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0088:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
------------------------------------------------------
warning: You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Executing load_winxp 
fsync: up and running.
007c:err:module:map_image Could not map section .rsrc, file probably truncated
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0064), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
The operation completed successfully
Setting Windows version to winxp
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 5.0/bin/wine regedit C:\windows\Temp\set-winver.reg
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
fsync: up and running.
007c:err:module:map_image Could not map section .rsrc, file probably truncated
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0064), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 5.0/bin/wine64 regedit C:\windows\Temp\set-winver.reg
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
fsync: up and running.
007c:err:module:map_image Could not map section .rsrc, file probably truncated
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0064), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
------------------------------------------------------
warning: Running /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 5.0/bin/wineserver -w. This will hang until all wine processes in prefix=/home/deck/.local/share/Steam/steamapps/compatdata/1237320/pfx terminate
------------------------------------------------------
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
Executing cd /home/deck/.var/app/com.github.Matoking.protontricks/cache/winetricks/dotnet40
Executing /home/deck/.var/app/com.github.Matoking.protontricks/cache/protontricks/proton/Proton 5.0/bin/wine dotNetFx40_Full_x86_x64.exe
fsync: up and running.
007c:err:module:map_image Could not map section .rsrc, file probably truncated
007c:err:ntoskrnl:ZwLoadDriver failed to create driver L"\\Registry\\Machine\\System\\CurrentControlSet\\Services\\wineusb": c0000142
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"wineusb" failed to start: 1114
wine: Call from 0x7bc8be3c to unimplemented function ntoskrnl.exe.RtlPcToFileHeader, aborting
wine: Unimplemented function ntoskrnl.exe.RtlPcToFileHeader called at address 000000007BC8BE3C (thread 0064), starting debugger...
0034:err:service:process_send_command service protocol error - failed to read pipe r = 0  count = 0!
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"nsiproxy" failed to start: 1053
0034:err:service:process_send_start_message pipe connect failed
0034:fixme:service:scmdatabase_autostart_services Auto-start service L"NDIS" failed to start: 1053
00e4:err:module:map_image Could not map section .rsrc, file probably truncated
0024:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
0024:fixme:process:SetProcessDEPPolicy (3): stub
0024:fixme:clusapi:OpenCluster ((null)) stub!
0024:fixme:clusapi:ClusterOpenEnum (DEADBEEF, 4) stub!
0024:fixme:clusapi:ClusterEnum (DEADBEEF, 0, 0031F920, 0064D0D0, 261) stub!
0024:fixme:clusapi:ClusterCloseEnum (DEADBEEF) stub!
0024:fixme:clusapi:CloseCluster (DEADBEEF) stub!
------------------------------------------------------
warning: exit status 5 - user selected 'Cancel'
------------------------------------------------------
(1)(deck@steamdeck ~)$ 0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000017
0080:fixme:plugplay:pdo_pnp_dispatch Unhandled function 00000002

p.p.p.s: to replicate this, type in this command (requires sonic frontiers or any other game and compatdata using proton 5.0-10): protontricks --no-background-wineserver 1237320 --force dotnet48

**Comment by SonicdomXD** [comment]
Update: it seems to be kinda fixed when i change the beta channel to preview, but I'll have to wait until both are installed

**Comment by SonicdomXD** [comment]
Update numero due: Dotnet 40 is installed, now i wait for dotnet48.

**Comment by SonicdomXD** [comment]
Final update: both seem to be installed, so this issue is no longer relevant. If you too are having this issue, just change your beta channel to preview, at least thats how it got solved for me. It could be different for you.

**Comment by solitudealma** [comment]
> Final update: both seem to be installed, so this issue is no longer relevant. If you too are having this issue, just change your beta channel to preview, at least thats how it got solved for me. It could be different for you.最终更新：两者似乎都已安装，因此此问题不再相关。如果您也遇到此问题，只需将您的测试频道更改为预览即可，至少这就是我解决问题的方法。对你来说可能会有所不同。

how to install, i want to install [this](https://github.com/Aira-Sakuranomiya/CleanFlashInstaller). can you help me?
