### ISSUE TITLE
Can't find steam library

### ISSUE THREAD

**Issue by fuzunspm** [Matoking/protontricks#212]
**Describe the bug**
Protontricks won't find the directory with and error of:

```
╰─$  export STEAM_DIR=/mnt/SVAULT/SteamLibrary/ && protontricks -c 'wine /home/username/Downloads/2022_TTRS_1.exe' 365960

protontricks (ERROR): $STEAM_DIR was provided but didn't point to a valid Steam installation.
Steam installation directory could not be found.
```

**System (please complete the following information):**
 - Distro:Arch
 - Protontricks installation method: Aur package
 - Protontricks version: protontricks (1.10.2)
 - Steam version: Latest Beta as of 2023-03-24

**Comment by Matoking** [comment]
You appear to be configuring a path to a Steam library instead of the Steam installation directory. Steam installation directory is usually located at `~/.steam/steam` and contains configuration files, binaries and other files besides the installed Steam apps in the `steamapps` directory.
