### ISSUE TITLE
protontricks (WARNING): Current Steam Runtime not recognized by Protontricks.

### ISSUE THREAD

**Issue by n00btube3D** [Matoking/protontricks#220]
**Describe the bug**
Not technically a bug, but worth attention.
Proton 8.0 now uses Steam Linux Runtime Sniper, which triggers this warning.

**To Reproduce**
1. Run `protontricks $APPID winecfg` for example, warning will show up.

**Expected behavior**
No warnings show.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: AUR Git Package
 - Protontricks version: `protontricks (1.10.3.dev1+g124fc7a)`
 - Steam version: (Beta)
![image](https://user-images.githubusercontent.com/54535183/232745859-f66675fe-11a1-4aef-b34c-e2417322f608.png)

**Comment by Matoking** [comment]
The development version on `master` has been updated to recognize the new runtime properly and the warning will disappear in the next release.

The warning is purely cosmetic; the new runtime introduces no changes in the executables Protontricks uses.
