### ISSUE TITLE
protontricks is messing up line formatting and prevents interacting with the shell

### ISSUE THREAD

**Issue by abc-mikey** [Matoking/protontricks#223]
**Describe the bug**
when running winetricks (as per default) through protontricks the output on the cli is messed up (no line breaks) also the shell doesn't seem to respond to key presses including ^C, ^Z etc.

NOTE I'm running protontricks via flatpak but do not believe that this is the cause of the issue.

**To Reproduce**
1. Run command `flatpak run com.github.Matoking.protontricks 1091500 vcrun2022`
2. Output appears without linebreaks and when prompted to press "Y" you are unable to interact, including pressing ^C.

**Expected behavior**
Proper output and interaction. This can be achieved by running the following commands, each inside one another:

1. `flatpak run --command=bash com.github.Matoking.protontricks`
2. `protontricks -c bash <APPID>`
3. `winetricks vcrun2022`

**System (please complete the following information):**
 - Distro: opensuse tubleweed
 - Protontricks installation method: flatpak
 - Protontricks version: protontricks (1.10.2)
 - Steam version: not beta, package version: 1682708537

**Additional context**

Tested with multiple terminals (`alacritty`, `gnome-terminal`), multilpe shells (`bash`, `fish`) multiple wms (`gnome-shell`, `sway`) and multiple display servers (`x11`, `wayland`) with same results. 

**Screenshots**

![Screenshot from 2023-04-29 13-35-14](https://user-images.githubusercontent.com/2983924/235300443-a66f9c6a-1728-42a4-9319-023c1220cd8e.png)

**Comment by Matoking** [comment]
I haven't nailed down what exactly causes the messed up output (something to do with the Pressure Vessel tools?), but using the `--no-background-wineserver` flag seems to do the job as a workaround.

(Ignore the related commit, I made a typo in one of my attempts to fix the issue which didn't actually fix the issue, only crashed the script before it could run whatever causes the garbage output to be eventually printed.)

**Comment by Matoking** [comment]
Fixed in 1.10.3 by disabling `background-wineserver` by default.

**Comment by Termuellinator** [comment]
I'm encountering the exact same issue with 1.11.0 on Arch right now while trying to install vcrun2019. `--force` and `--no-background-wineserver` make no difference unfortunately :/

The workaround mentioned in OP doesn't work either.

**Comment by hw-claudio** [comment]
still same issue in the latest protontricks flatpak protontricks (1.11.1),

 flatpak info com.github.Matoking.protontricks

Janne Pulkkinen - A simple wrapper that does winetricks things for Proton
enabled games

          ID: com.github.Matoking.protontricks
         Ref: app/com.github.Matoking.protontricks/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.11.1
     License: GPL-3.0
      Origin: flathub
  Collection: org.flathub.Stable
Installation: user
   Installed: 65.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 99009ef46ff672675aa766d1e7c516d5e035cd0568b714788b9d16dd3c0a2e4f
      Parent: 8c0f79e09273ee805509103ccb52cc16f9ab10f23a21520b8303b59bc5731923
     Subject: Update to 1.11.1 (b7ef80ec)
        Date: 2024-02-21 05:59:40 +0000

command attempted:

flatpak run com.github.Matoking.protontricks (appid) vcrun2019

**Comment by PgLoLo** [comment]
Same problem on flatpak protontricks 1.11.1

**Comment by mdeguzis** [comment]
Same issue on 1.12.0 Flatpak.
