### ISSUE TITLE
protontricks fails with a "Proton installation could not be found!"

### ISSUE THREAD

**Issue by Delta-official** [Matoking/protontricks#225]
**Describe the bug**
protontricks fails to find a proton installation

**To Reproduce**
1. run `protontricks --gui`
2. choose a game
3. protontricks fails with a `Proton installation could not be found!`

**Expected behavior**
everything working as expected

**System (please complete the following information):**
 - Distro: arch
 - Protontricks installation method: aur
 - Protontricks version: `protontricks (1.10.3.dev3+g1d03f02)`
 - Steam version: beta

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**
```
protontricks (INFO): Found Steam directory at /home/delta/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/delta/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: darkuss55
protontricks (INFO): Shortcut S.T.A.L.K.E.R. Shadow of Chernobyl (3458771400) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
protontricks (INFO): Shortcut 律動のぱらいぞVer1_0_0.exe (3656649275) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
protontricks (INFO): Found 4 Steam shortcuts running using Steam compatibility tools
protontricks (INFO): Using 'zenity' as GUI provider
protontricks (INFO): User has configured default Proton version (CompatToolMapping): proton_8
protontricks (ERROR): Could not find configured Proton installation!
protontricks (ERROR): Active Proton installation could not be found automatically.
Proton installation could not be found!
```

**Comment by Delta-official** [comment]
turns out steam didn't install proton 8 yet, it worked after i tried to launch the game and it installed proton

**Comment by Matoking** [comment]
For what it's worth, my Steam installation had a similar issue with Steam having uninstalled Proton 7 recently for some reason despite it being the default Proton for other titles in Steam settings. Launching a game with Proton 7 would lead to it getting reinstalled, however.

If this becomes a common issue, the error message could be adjusted to double-check that the Proton installation is actually installed.
