### ISSUE TITLE
output is broken

### ISSUE THREAD

**Issue by Dandraghas** [Matoking/protontricks#227]
**Describe the bug**
For some reason when protontricks installs any component, its output is messed up.

**To Reproduce:**
1. Run command `protontricks --force dotnet48`
2. See that output is not readable

**Expected behavior**
Output should be clean and easy to read.

**System (please complete the following information):**
 - Distro: Fedora 38
 - Protontricks installation method: dnf package
 - Protontricks version: 1.10.2
 - Steam version: Steam beta client may 4th update

**Screenshots:** 
![image](https://user-images.githubusercontent.com/91272905/236469708-1d2e7a1a-9415-4ebf-9595-cfb086f6c7e1.png)

**Additional context**
its not only affect protontricks output but after protontricks finished other command line components(like powerlevel10k, or any cli tool) is broken

**Comment by Matoking** [comment]
Fixed in 1.10.3 by disabling `background-wineserver` by default.
