### ISSUE TITLE
"Protontricks was closed due to the following error"

### ISSUE THREAD

**Issue by LividLiquid** [Matoking/protontricks#236]
**Describe the bug**
Launches, allows me to select game, then crashes with error message.

**To Reproduce**
1.) Launch Protontricks
2. Select Game

**Expected behavior**
Program launches

**System (please complete the following information):**
 - Distro: Ubuntu 22.0.4
 - Protontricks installation method: Have tried Apt, Discover, and Snap Store.
 - Protontricks version: 1.7.0
 - Steam version: 1687386907

Error Message: 

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/protontricks/cli/util.py", line 143, in wrapper
    return cli_func(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/protontricks/cli/main.py", line 214, in main
    proton_app = find_proton_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 624, in find_proton_app
    tool_app = find_steam_compat_tool_app(
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 537, in find_steam_compat_tool_app
    tool_appid = get_tool_appid(compat_tool_name, appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 418, in get_tool_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/usr/lib/python3/dist-packages/protontricks/steam.py", line 385, in get_appinfo_sections
    raise SyntaxError("Invalid file magic number")
SyntaxError: Invalid file magic number

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/lividliquid/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
Using default Steam Runtime at /home/lividliquid/.steam/root/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 1 Steam library folders
Currently logged-in Steam user: lividliquid@yahoo.com
Found 2 Steam shortcuts running using Steam compatibility tools
Using 'zenity' as GUI provider

**Comment by Matoking** [comment]
You need to update your Protontricks to at least version 1.10.1.

Since Ubuntu only updates their packages semiannually (apart from security fixes) in releases (eg. Ubuntu 23.04 is the latest, 22.10 is the previous release), it's recommended to install Protontricks from Flathub or using pipx instead. You can check the instructions [here](https://github.com/Matoking/protontricks/tree/master#flatpak-recommended).

**Comment by LividLiquid** [comment]
Thank you. That worked. Boy howdy, those repositories are always, always, always out of date.

Took me an embarrassingly long time to learn this lesson.
