### ISSUE TITLE
Protontricks completely broken but only when trying to run against native non-flatpak steam install

### ISSUE THREAD

**Issue by gardotd426** [Matoking/protontricks#240]
**Describe the bug**
When trying to run **any** protontricks command, the GUI opens and asks me to select between my flatpak and system installations of Steam. Selecting Flatpak and clicking OK works as expected, while clicking Native and then OK crashes protontricks with a python-vdf error:

```
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.10.3', 'console_scripts', 'protontricks')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 1265, in get_steam_apps
    steam_apps += get_custom_windows_shortcuts(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 1115, in get_custom_windows_shortcuts
    vdf_data = lower_dict(vdf.binary_loads(content))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vdf/__init__.py", line 314, in binary_loads
    return binary_load(BytesIO(b), mapper, merge_duplicate_keys, alt_format, raise_on_remaining)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vdf/__init__.py", line 420, in binary_load
    raise SyntaxError("Binary VDF ended at offset %d, but there is more data remaining" % (fp.tell() - 1))
SyntaxError: Binary VDF ended at offset 589526, but there is more data remaining
```

**To Reproduce**
1. Be on the latest master of both protontricks and python-vdf
2. Run `protontricks --gui` and select the native install
3. Command fails and error is displayed

**Expected behavior**
Protontricks works

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks installation method: Tried manual from source, chaotic-aur and regular AUR. 
 - Protontricks version:  1.10.3
 - Steam version: Beta
 
**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -v 42 faudio` instead and copy the output here.

`protontricks -v --gui`:

```
protontricks (INFO): Found Steam directory at /home/matt/nvme/steamroot
protontricks (INFO): Found Steam directory at /home/matt/.var/app/com.valvesoftware.Steam/.local/share/Steam
protontricks (INFO): Using 'yad' as GUI provider
protontricks (INFO): Using default Steam Runtime at /home/matt/nvme/steamroot/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 7 Steam library folders
protontricks (INFO): Multiple compatdata directories found for app 1237970
protontricks (INFO): Multiple compatdata directories found for app 1449560
protontricks (INFO): Multiple compatdata directories found for app 961940
protontricks (INFO): Multiple compatdata directories found for app 397540
protontricks (INFO): Currently logged-in Steam user: gardotd426
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.10.3', 'console_scripts', 'protontricks')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 32, in cli
    main(args)
  File "/usr/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/cli/main.py", line 241, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 1265, in get_steam_apps
    steam_apps += get_custom_windows_shortcuts(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/protontricks/steam.py", line 1115, in get_custom_windows_shortcuts
    vdf_data = lower_dict(vdf.binary_loads(content))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vdf/__init__.py", line 314, in binary_loads
    return binary_load(BytesIO(b), mapper, merge_duplicate_keys, alt_format, raise_on_remaining)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/vdf/__init__.py", line 420, in binary_load
    raise SyntaxError("Binary VDF ended at offset %d, but there is more data remaining" % (fp.tell() - 1))
SyntaxError: Binary VDF ended at offset 589526, but there is more data remaining
```

**Comment by kalash222222** [comment]
have the same issue here even tried reinstalling arch just for this error

**Comment by kalash222222** [comment]
i got similar problem as yours even tried reinstalling arch if ya find fix for it please share it

**Comment by Matoking** [comment]
Have you possibly added Steam shortcuts using a third-party tool? Protontricks uses ValvePython/vdf library to parse VDF files, and by default it causes a crash if the VDF file has additional data after the VDF data should have ended, in this case `~/.local/share/Steam/userdata/STEAM_USER_ID/config/shortcuts.vdf`.

Thankfully, we can disable this check which _should_ fix this problem. I've pushed a fix to `ignore_remaining_vdf` branch; you can test it by installing Protontricks using pipx like so (make sure you install pipx using instructions [here](https://github.com/Matoking/protontricks#pipx)):

```
$ pipx install --force git+https://github.com/Matoking/protontricks.git@ignore_remaining_vdf

# Test if the fix works
$ ~/.local/bin/protontricks -v --gui
```

Also, could you run the following command to check out how large the VDF file is; if it's considerably larger than the offset where the VDF parser stopped reading the file, it might be something else other than the case of a faulty VDF accidentally writing some unnecessary footer or forgetting to truncate the file. Replace `STEAM_USER_ID` with your user ID; it's the other numeric directory inside `userdata` other than `0`:

```
$ ls -l ~/.local/share/Steam/userdata/STEAM_USER_ID/config/shortcuts.vdf
```

In any case, if the slightly malformed VDF file is being created by a third party tool, it should ideally be fixed upstream to prevent other possible problems.

**Comment by gardotd426** [comment]
I have no shortcuts at all, that file doesn't even exist.

**Comment by gardotd426** [comment]
Okay yes using that branch allows it to run. What's weird is that I've never modified any shortcuts for any Steam apps, only non-Steam stuff added as non-Steam games.

**Comment by Matoking** [comment]
I've pushed the fix to master.

You can uninstall the pipx version by running `pipx uninstall protontricks` and install `protontricks-git` from AUR to install the fix before the next Protontricks release.
