### ISSUE TITLE
How do you run the "Protontricks app shortcut" from terminal?

### ISSUE THREAD

**Issue by nick123456789025** [Matoking/protontricks#242]
I want to run a non-steam game through the steam version of proton but every time I launch it launches in wine from terminal, if I run it from the EXE itself it will run through proton tricks but it doesn't work through terminal. Is there a command for this functionality? And if there isn't, you should add it. I think it would be a good feature.

**Comment by Matoking** [comment]
`protontricks-launch` has been around for roughly two years with this use case in mind, and it's also what the app shortcut uses behind the scenes. It was intended to be public but I never documented in the README for some reason. Whoops!

I've updated the README with these two examples:

```
protontricks-launch <EXE>
protontricks-launch --appid <APPID> <EXE>
````

**Comment by nick123456789025** [comment]
Thank you.
