### ISSUE TITLE
find_proton_app() rejects non‐official Proton versions

### ISSUE THREAD

**Issue by Freso** [Matoking/protontricks#26]
~~It is possible to install custom Proton versions to `compatibilitytools.d` (incl. ones that are not Proton at all, like [boxtron](https://github.com/dreamer/boxtron)) in the base Steam directory—e.g., `~/.local/share/Steam/compatibilitytools.d/`. However it seems like `protontricks` will just blanket ignore these versions even if given directly via `$PROTON_VERSION`:~~
https://github.com/Matoking/protontricks/blob/b1c3cdf1c25c48fc27210d1b043cab87e834e22e/src/protontricks/steam.py#L441-L442

It will also not accept them without explicitly requesting it. See:
```
~> env PROTON_VERSION='proton_tkg_4.13.r0.g3f06c18b.din-fo4' protontricks 377160 winecfg
protontricks (ERROR): $PROTON_VERSION was set but matching Proton installation could not be found.
Proton installation could not be found!
~> protontricks 377160 winecfg
protontricks (ERROR): Could not find the Steam Play manifest in appinfo.vdf
protontricks (ERROR): Could not find Proton's App ID from appinfo.vdf
protontricks (ERROR): Active Proton installation could not be found automatically.
Proton installation could not be found!
~> ls ~/.local/share/Steam/compatibilitytools.d/
proton_tkg_4.11.r6.gfbb8eac8/  proton_tkg_4.12.1.r14.gc95aae10.din/  proton_tkg_4.12.1.r27.g2394b080.din-fo4/  proton_tkg_4.13.r0.g3f06c18b.din-fo4/
```

**Comment by Freso** [comment]
Hm. Seems like it was simply that `$PROTON_VERSION` wants the display name and it now actually works fine. I guess the issue is just when `$PROTON_VERSION` isn’t specified. Should I open a new issue or rename this one?

**Comment by Matoking** [comment]
I wasn't paying enough attention when changing the VDF parsing in 1.2.3 and broke detection of custom Proton installations in the process. Whoops.

I've pushed a fix to master now.

**Comment by Freso** [comment]
Thanks!
