### ISSUE TITLE
Protontricks cannot find Proton installation

### ISSUE THREAD

**Issue by DavidTagt** [Matoking/protontricks#260]
**Describe the bug**
I run protontricks (the flatpack and the AUR version) and only one game is shown in the list, even though i have several installed, but selecting that game still results in this error 

**To Reproduce**
1. run protontricks flatpack (--gui is implied i think)
2. The list of detected games is displayed.
   2a. The list is incomplete, but i dont know if that is a separate issue
3. Selecting a game yields this error message.

**Expected behavior**
running protontricks GUI i expect protontricks to discover my SteamLibraries and display the games inside them.  

**System (please complete the following information):**
 - Distro: EndeavourOS (Arch based)
 - Protontricks installation method: Flatpak, but I've tried the AUR as well to the same effect.
 - Protontricks version: 1.15.4.
 - Steam version: check if you're running Steam beta; No beta. Steam package version 1.0.0.78-2

**Additional context**

[bug reports protontricks.txt](https://github.com/Matoking/protontricks/files/13256736/bug.reports.protontricks.txt)

I've included the messages in this file. I've run the flatpak "normally" via gui, and also launched with -v flag. Same output, just differently styled. 

I've checked some other issues on here and i think it might be KDE and Perl locale related. I've recently had trouble setting the Perl locales, so i dunno it might be a clue.

**Comment by Matoking** [comment]
The log includes these warnings:

```
protontricks (WARNING): Steam library folder /SSDs/NVME/SteamLibrary not found. Protontricks might not have access to the directory.
protontricks (WARNING): Steam library folder /SSDs/SSekunDary/SteamLibrary not found. Protontricks might not have access to the directory.
```

Are the games installed in those locations? Since you're using Flatpak, you'll have to manually add permissions using Flatseal (graphical utility) or using the `flatpak` command. Protontricks should also prompt you to run a command to add the necessary permissions, though the dialog also includes button to ignore it permanently so that the permissions are not prompted for the same location(s) again.

In any case, can you try [these instructions](https://github.com/flathub/com.github.Matoking.protontricks#configuration) and see if that fixes the issue?

**Comment by DavidTagt** [comment]
ah yes, i get those errors even though i have added these locations to the flatpak, via the command that displays at launch with protontricks, like you mentioned (and it is very helpful, thank you! i've just broken it :P)  and through Flatseal to no effect.

I have 4 libraries, 1 in my home drive (but this one have no games) and 3 on various SSDs. The game it finds is the one not mentioned in the error messages, but i have more games installed on that drive either way so its still wrong. The drives mentioned in the error messages are (quite predictable) also wrong.
Whats funny though is that protontricks expects the drives to be in CAPS when they are lowercase in file manager and flatseal.
 
The AUR package still had these issues however, so is there like a common config or something i should clear perhaps? Maybe check my $PATH or something?

**Comment by DavidTagt** [comment]
I've tried GPT for like 7 minutes and it is as confused you and I am, well like I am at least. 

I've launched steam more than once, I've launched a game more than once, wine and winetricks is installed, proton is installed.

The only none standard thing is have 
```
export LC_MESSAGES=sv_SE.UTF-8
export LC_COLLATE=sv_SE.UTF-8
```


in my .zshrc, because of a bug/error with KDE and locales. Does that matter in any way?

**Comment by Matoking** [comment]
> I have 4 libraries, 1 in my home drive (but this one have no games) and 3 on various SSDs. The game it finds is the one not mentioned in the error messages, but i have more games installed on that drive either way so its still wrong. The drives mentioned in the error messages are (quite predictable) also wrong.

Protontricks looks up the list of library folders in `/home/davidt/.local/share/Steam/steamapps/libraryfolders.vdf`. Does that file contain the correct library folders?

There's a chance your Steam installation is located elsewhere in which case Protontricks is finding the wrong installation.

> Whats funny though is that protontricks expects the drives to be in CAPS when they are lowercase in file manager and flatseal.

Which part of the path is lowercase exactly? Linux filesystems are case-sensitive by default and Protontricks uses the path names as they're reported by Steam. I reckon Flatseal should work correctly despite this?

You could probably try adding `/SSDs` to the list of allowed fileystems in Flatseal, or even temporarily enabling all filesystem access to see if that solves the issue.

**Comment by DavidTagt** [comment]
Ah great!

> Protontricks looks up the list of library folders in /home/davidt/.local/share/Steam/steamapps/libraryfolders.vdf. Does that file contain the correct library folders?

No there was something wrong there! I pasted the path from file manager into the .vdf file and that solved it. The paths were in caps there, so something was wrong with the .vdf file. 

Excellent! Thank you so much for your help! 🙏😁
