### ISSUE TITLE
"Only Flatpack releases of Protontricks are supported on SteamOS"

### ISSUE THREAD

**Issue by Razatop** [Matoking/protontricks#262]
**Describe the bug**
When trying to install [MO2 for Linux](https://github.com/rockerbacon/modorganizer2-linux-installer/releases/tag/4.4.0) I get the error

"Only Flatpack releases of Protrontricks are supported on SteamOS. Please install Protontricks through the discover app store"

**Expected behavior**
Should start the script and allow me to install the project

**System (please complete the following information):**
 - Distro: SteamOS
  - Protontricks installation method: Flatpak
 - Protontricks version: 1.10.2 & 1.10.5
  - Steam version: Steam Beta
**Additional context**
 Have allowed write perms with Flatseal
 
 Still very new to linux. Would love some help!

**Comment by JackYansongLi** [comment]
I had the same issue. Did you solve it?
