### ISSUE TITLE
Protontricks closed due to error after attempting to open

### ISSUE THREAD

**Issue by SnugglezPanda** [Matoking/protontricks#264]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 149, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 264, in main
    steam_app = select_steam_app_with_gui(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/gui.py", line 325, in select_steam_app_with_gui
    appid2icon = _get_appid2icon(steam_apps, steam_path=steam_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/gui.py", line 93, in _get_appid2icon
    with Image.open(original_icon_path) as img:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/PIL/Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/home/deck/.local/share/Steam/appcache/librarycache/976730_icon.jpg'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.14.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 1364780
Multiple compatdata directories found for app 2180100
Multiple compatdata directories found for app 1493710
Multiple compatdata directories found for app 1086940
Multiple compatdata directories found for app 1172470
Currently logged-in Steam user: otakubo1
Found 1 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/appcache/librarycache/1172470_icon.jpg has unusual size, resizing
App icon /home/deck/.local/share/Steam/appcache/librarycache/1086940_icon.jpg has unusual size, resizing
App icon /home/deck/.local/share/Steam/appcache/librarycache/1401590_icon.jpg has unusual size, resizing
App icon /home/deck/.local/share/Steam/appcache/librarycache/1240440_icon.jpg has unusual size, resizing

I am very new to this and do not understand a thing of what to do please help.

I've installed protontricks via the discover store. This error just pops up when I attempt to open it.

**Comment by Matoking** [comment]
What version of Protontricks do you have installed? Protontricks cannot read the game icon and is crashing instead of simply skipping the icon. This was a problem in 1.10.4 but should be fixed in 1.10.5.

You can check the version in Discover store -> _Installed_ tab. Alternatively, you can run the command `flatpak run com.github.Matoking.protontricks --version`.

**Comment by SnugglezPanda** [comment]
This is weird, I have in installed via the discover store but it's saying it's not installed 
app/com.matoking.protontricks/x84_64/master not installed

**Comment by SnugglezPanda** [comment]
Do I open it from the console all the time now?

**Comment by Matoking** [comment]
No, you don't need to. You'll have to ensure Protontricks 1.10.5 is installed first to rule out the previously fixed issue, though.

Have you reinstalled Protontricks and checked that it is version 1.10.5?
