### ISSUE TITLE
Proton Experimental not found by protontricks 

### ISSUE THREAD

**Issue by alizeegagnon** [Matoking/protontricks#267]
**Describe the bug**
After choosing Cyberpunk in the protontricks GUI, the app reports that no active Proton installation was found. However, Proton Experimental is installed on my system. **I ended up solving it while writing the post, but wanted to post in case someone ran into the same issue !**

**To Reproduce**
1. Run command `protontricks -v --gui`
2. select Cyberpunk from the list 
3. Proton could not be found, full error log pasted below

**Expected behavior**
I've never used the app before (maybe Winetricks a long while ago ?), I assume it should find the Proton install and proceed to other stuff

**System (please complete the following information):**
 - Distro: Arch Linux, using Wayland + Sway
 - Protontricks installation method: through the Aur, installed today
 - Protontricks version: 1.10.5
 - Steam version: No Beta Choosen, latest through multilib

**Additional context**

This is on a fresh install of Linux. The only game installed through Steam is currently Cyberpunk. I have not installed Proton GE. Steam chose to install Proton Experimental for the game, there is no other Proton version installed through it, I did not specify any compatibility tool to use, apart from enabling Steam Play. The game itself runs fine, I just want to mod it.

I have followed the steps in this issue:   #136 
- I did try to delete appinfo.vdf, then have Steam recreate it. It did not solve the bug.
- When I generated a readable version of it through 
`python -c "from pathlib import Path; import pprint; from protontricks.steam import get_appinfo_sections; pprint.pprint(get_appinfo_sections(Path('/home/alz/.steam/steam/appcache/appinfo.vdf')))" > ~/appinfo-output.txt`
I did find a listing for proton_experimental in the compat_tools section. I can paste more if needed.
- config.vdf did not mention proton at all: `cat config.vdf | grep -i proton` gives no result

I also looked at other issues, like #225. I can confirm that Proton Experimental is installed at `~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental`. No other issue I could find seemed to fit mine.

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

`~> protontricks -v --gui
protontricks (INFO): Found Steam directory at /home/alz/.local/share/Steam
protontricks (INFO): Using default Steam Runtime at /home/alz/.local/share/Steam/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: :sunglasses: 
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Using 'zenity' as GUI provider
protontricks (INFO): No compatibility tool found by reading Steam configuration. Using stable version of Proton as fallback.
protontricks (ERROR): Could not find configured Proton installation!
protontricks (ERROR): Active Proton installation could not be found automatically.
Proton installation could not be found!`

### I actually managed to solve this myself 

`export PROTON_VERSION="Proton Experimental"` did the trick !

**Comment by Matoking** [comment]
Researched this issue a bit more. Turns out Steam has a set of default Proton versions for around 18 games in the Steam Play manifest in `~/.steam/steam/appcache/appinfo.vdf`, including Cyberpunk 2077 which has a comment remarking that Proton Experimental is used by default for DualSense support. Protontricks didn't read these settings previously, leading it to either detect the wrong Proton version or fail to find one entirely.

---

**I've pushed a fix to `fix_app_mapping_detection` branch**. Since you're on Arch Linux, you could build it from `protontricks-git` in AUR. Change the `source` line in `PKGBUILD` to:

```
source=('git+https://github.com/Matoking/protontricks.git#branch=fix_app_mapping_detection')
```

You can also use pipx with the following command:

```sh
pipx install --force git+https://github.com/Matoking/protontricks.git@fix_app_mapping_detection
```

Can you check that the fixed version detects Proton Experimental correctly?
