### ISSUE TITLE
flatpak: cabextract workaround

### ISSUE THREAD

**Issue by rml0** [Matoking/protontricks#27]
I stumbled upon a game that has gold reports on protondb, but requires protontricks modifications. Therefore I followed the steps in the wiki to get that set up. I came across the same problems as in #25, but that has since been solved. Then, the problem was that cabextract was missing. 

The wiki states that the flatpak version of steam does not include some libraries used by winetricks.

## Workaround
The solution I found was adding it manually:

### Compile latest
```
git clone https://github.com/kyz/libmspack.git
cd libmspack/cabextract
./autogen.sh
```
/usr/local/bin is read-only inside the flatpak, adding the prefix becomes necessary
```
./configure --prefix=$HOME/.local
```
gcc (requirement) is not present in the flatpak, the compilation needs to be made outside
```
make
```
### Install it inside the flatpak
```
cd ..
mv cabextract $HOME/.var/app/com.valvesoftware.Steam
flatpak run --command=bash com.valvesoftware.Steam
cd cabextract
make install
exit
```
### Add path to PATH as env
The last step is to add the binary located in .local/bin to the command. As it is the same location as the protontricks binary, the path to it is no longer necessary, changing the alias in the .bashrc file to:
```
alias protontricks-flat='flatpak run --env=WINETRICKS=$HOME/winetricks --env=STEAM_RUNTIME=0 --env=PATH=$PATH:$HOME/.local/bin --command=protontricks com.valvesoftware.Steam'
```
---
I suppose adding other libraries would be similar, but I haven't had the need yet.

@Matoking I dunno if you want this in the wiki or not, as its kinda specific to cabextract and might be clutter for people that don't require it.

Either way, if someone comes looking for an answer, I hope this points them in the right direction!

**Comment by Matoking** [comment]
I feel like adding these instructions to the wiki would mean a lot more maintenance load down the line. Compiling and installing these packages already involves plenty of steps, and that's assuming the user has the required dependencies and environment for compiling the software. And that's [only one of multiple dependencies](https://github.com/Winetricks/winetricks/blob/master/src/winetricks#L27) that might not exist in the sandbox.

I'll close this issue but keep the discussion open.
