### ISSUE TITLE
Virtual Desktop enabled games fail to display.

### ISSUE THREAD

**Issue by Blayer98** [Matoking/protontricks#275]
**Bug in Question**
If you enable Virtual Desktop through winecfg, any game with it enabled may fail to display at all. Winecfg and Explorer will also no longer open on the affected prefix.

Using PROTON_LOG=1 on any game using a Virtual Desktop reveals the following errors:

“err:winediag:nodrv_CreateWindow Application tried to create a window, but no driver could be loaded.”
“err:winediag:nodrv_CreateWindow L”The explorer process failed to start.””

**To Reproduce**

1: use protontricks on any game, this includes non-Steam games.
2: select the prefix to use and then select “open winecfg”.
3: Go to the “Graphics” tab and select “Enable Virtual Desktop”.
4: Apply the changes and close winecfg.
5: Re-open winecfg, explorer, or any game that has the Virtual Desktop option enabled.

**Expected behavior**
The game should run for a few seconds before closing without displaying an error, although this could be different per game.

Winecfg and Explorer, after applying the virtual desktop changes, will no longer open in the affected prefix at all, unless the virtual desktop option is disabled via “Change settings”.

**System (please complete the following information):**
 - Distro: SteamOS 3.5.7 (Arch Linux with Plasma)
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.0
 - Steam version: Steam Deck Stable
 - Protontricks Wine version: 8.0

**Additional context**
Enabling the Virtual Desktop setting through “Change settings” should also cause the same effect until it is disabled.

This bug appeared in June 2023 for Wine Staging and was fixed and solved in August 2023.
https://bugs.winehq.org/show_bug.cgi?id=55085

**Comment by Matoking** [comment]
This issue seems unrelated to Protontricks. Or does it work if you use the `--no-bwrap`  flag?

I had a quick look at [Valve's Wine fork](https://github.com/ValveSoftware/wine) and the fix mentioned in the WineHQ bug report doesn't appear to be included.

**Comment by Blayer98** [comment]
I’m not sure how to use —no-bwrap, I only use the newest Proton versions. I figured it was an issue with Protontricks since you have to activate Virtual Desktop with it I would have thought, would it be better to make an issue on Valve’s Proton or Wine GitHub repos?

**Comment by Blayer98** [comment]
Edit: ok I just attempted to use —no-bwrap but I still get the same issues.
