### ISSUE TITLE
protontricks error code - help?

### ISSUE THREAD

**Issue by rumble000** [Matoking/protontricks#278]
I keep getting an error message when trying to open protontricks. I have not yet used it. When I first opened it, I got an error and it gave me a code to put into konsole. I did. I am still getting error. 

Here is what it says:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 244, in main
    steam_apps = get_steam_apps(
                 ^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 1313, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 265, in from_appmanifest
    required_tool_appid = _get_required_tool_appid(install_path)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 290, in _get_required_tool_appid
    tool_manifest_content = tool_manifest_path.read_text()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1058, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [Errno 5] Input/output error: '/run/media/deck/0836c9b2-9a2a-4bd9-b829-2b303c3b4480/steamapps/common/Borderlands 3/toolmanifest.vdf'

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.14.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders

Any idea what to do to fix? Thanks.

**Comment by Matoking** [comment]
I'm guessing you have a microSD card in your Deck? "Input/output error" seems to suggest there are problems with it, though it's hard to say what exactly. Does it work correctly with your Steam Deck otherwise?

**Comment by rumble000** [comment]
Yes, I am using an SD card. It does work otherwise normally with the steam deck. Though, weirdly I did nothing and the issue resolved itself. Today I tried opening the program a few times and it seems to be working. No idea what the problem was. But truly appreciate your reply!

**Comment by Matoking** [comment]
Alright, closing this thread.
