### ISSUE TITLE
insufficient permissions

### ISSUE THREAD

**Issue by vortex1251** [Matoking/protontricks#280]
protontricks --gui 

response back is 
Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/jerome/.local/share/Steam
Found 9 Steam library folders
Skipping library folder /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary due to insufficient permissions
Skipping library folder /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f69/SteamLibrary due to insufficient permissions
Steam library folder /mnt/TOSHIBA/SteamLibrary not found. Protontricks might not have access to the directory.
Skipping library folder /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f67/SteamLibrary due to insufficient permissions
Skipping library folder /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f68/SteamLibrary due to insufficient permissions
Could not load manifest /home/jerome/.local/share/Steam/steamapps/appmanifest_2348590.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /home/jerome/.local/share/Steam/steamapps/appmanifest_1628350.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /home/jerome/.local/share/Steam/steamapps/appmanifest_1161040.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /home/jerome/.local/share/Steam/steamapps/appmanifest_228980.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /home/jerome/.local/share/Steam/steamapps/appmanifest_271590.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_1493710.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_205100.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_379720.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_420.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_409710.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_362890.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_550.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_8850.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_614570.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_107410.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_1238840.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_403640.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_1237970.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_380.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Could not load manifest /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f617/SteamLibrary/steamapps/appmanifest_220.acf due to insufficient permissions. Error: [Errno 13] Permission denied: '/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f616/SteamLibrary'
Skipping library folder /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f66/SteamLibrary due to insufficient permissions
Currently logged-in Steam user: foxtrot1251
Couldn't find custom shortcuts. Maybe none have been created yet?

**Comment by Matoking** [comment]
Have you installed Protontricks via Flatpak? If so, you'll need to configure Flatpak to allow access to other storage locations if you have installed games/apps on other locations besides the Steam's default location.

Protontricks should prompt you to run a command. If that message was dismissed (in which case Protontricks won't prompt you again for that path), you can try running the following command: 

```
$ flatpak override --user --filesystem=/run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f66 com.github.Matoking.protontricks
```

**Comment by vortex1251** [comment]
i'm using garuda distro . Proton was already installed i have my games on a removable ssd 

i used the command that you gave me and it got it working thanks

 however i still get the same error for  the protontricks --gui sorry new to linux i tried using flatseal and gave it the the path of /run/media/jerome/bc903c0f-b487-4d57-9459-b7de16c724f618/SteamLibrary but still get insufficient permissions
