### ISSUE TITLE
Cant get game to load. GBFVSR

### ISSUE THREAD

**Issue by VanishingBlaze** [Matoking/protontricks#282]
when trying to load granblue fantasy versus rising i get message then just an error

WINEPREFIX INFO:
Drive C: total 36
drwxr-xr-x  9 deck deck 4096 Jan 31 12:39 .
drwxr-xr-x  4 deck deck 4096 Feb  3 23:26 ..
drwxr-xr-x  6 deck deck 4096 Jan 31 12:39 Program Files
drwxr-xr-x  7 deck deck 4096 Jan 31 12:39 Program Files (x86)
drwxr-xr-x  4 deck deck 4096 Jan 31 14:24 ProgramData
drwxr-xr-x  2 deck deck 4096 Feb  3 21:56 openxr
drwxr-xr-x  4 deck deck 4096 Jan 31 12:39 users
drwxr-xr-x  3 deck deck 4096 Jan 31 12:39 vrclient
drwxr-xr-x 21 deck deck 4096 Feb  3 21:56 windows

Registry info:
/home/deck/.local/share/Steam/steamapps/compatdata/2157560/pfx/system.reg:#arch=win64
/home/deck/.local/share/Steam/steamapps/compatdata/2157560/pfx/user.reg:#arch=win64
/home/deck/.local/share/Steam/steamapps/compatdata/2157560/pfx/userdef.reg:#arch=win64

**Comment by Matoking** [comment]
What are the popup messages preceding the error? Also, have you selected a different Proton version for the game?

I assume you have installed Protontricks using Flatpak (this is the case if you used Discover to install the app).

If so, could you also try opening Konsole and running the following command:

```
$ flatpak run com.github.Matoking.protontricks -vv --gui
```

This should print a bunch of log lines. You can then copy and paste them into a gist using [gist.github.com](https://gist.github.com) which you can then post into this thread.

**Comment by VanishingBlaze** [comment]
Apparently reinstalling it fixed the issue. Sadly I couldn't find a solution for the initial reason why I installed protontricks in the first play

**Comment by Matoking** [comment]
Alright, closing this issue as this appears to be resolved.
