### ISSUE TITLE
protontricks-launch -h neither offers an option to set the working directory nor has any hints or clues which one it is

### ISSUE THREAD

**Issue by ell1e** [Matoking/protontricks#287]
**Describe the bug**
It might be that I just missed it, but it seems like `protontricks-launch -h` neither offers an option to set the working directory nor has any hints or clues which one the executable will be run in. Even when I enter any folders guaranteed to accessible even inside the sandbox, it appears that I can't run anything that is looking for files in the same folder. This makes running tools that rely on being run in some specific folder seemingly impossible.

**To Reproduce**
1. Run `protontricks-launch -h`
2. Try to find any info whatsoever on either what the working directory will be, or how to set it to some known place

**Expected behavior**
`protonticks-launch -h` has some info and/or options regarding the working directory

**System (please complete the following information):**
 - Distro: openSUSE Slowroll 20240213
 - Protontricks installation method: can't recall
 - Protontricks version:  protontricks (1.11.1.dev0+g3bb2496.d20240105)
 - Steam version: 1709846872 stable

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**

For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -vv 42 faudio` instead and copy the output here.

If the output is very long, consider creating a gist using [gist.github.com](https://gist.github.com/).

**Comment by Matoking** [comment]
The working directory is set to the selected app's installation directory, but only for custom commands and `protontricks-launch`. Winetricks commands instead use the current working directory.

`protontricks-launch --appid <APPID> <EXE>` is more or less a shorthand for `protontricks -c "wine <EXE>" <APPID>`, so depending on your use case you could use `protontricks -c "cd <PATH>; wine <EXE>" <APPID>` instead.

The current situation is admittedly confusing. It might be better to remove this functionality and let the shell/desktop environment take care of the working directory in all cases instead. I don't recall there being any specific reason for this besides it being a tad more convenient when running `protontricks -c bash <APPID>`. Some 3rd party scripts might rely on this behavior, but hopefully not.

**Comment by ell1e** [comment]
An option to control this behavior might be enough if you don't want to change the default. Maybe I'm wrong about this, but wrong working directory errors tend to be fairly obvious to any user who has used the terminal before, which seems to be the crowd that would use protontricks-launch(??). So I think most people would look in `--help` at that point to figure out how to set it. But maybe I'm underestimating the potential confusion for others, I'm not sure.

**Comment by Matoking** [comment]
Searched GitHub for how `protontricks` is used. Doesn't seem like too many scripts rely on the working directory, so I went ahead and removed it.

`--cwd-app` flag and `$STEAM_APP_PATH` environment variable (which has actually worked since 1.8.0, though it was undocumented) are available as workarounds when needing to set the working directory to the previous default or determine where the installation directory is.

**Comment by ell1e** [comment]
Really cool! :heart: Thank you so much!
