### ISSUE TITLE
After updating to 1.11.1-1 can no longer open protontricks

### ISSUE THREAD

**Issue by PickMeNow** [Matoking/protontricks#294]
**Describe the bug**
After updating to 1.11.1, I can no longer run protontricks.

**To Reproduce**
1. Open console type: protontricks
2. Command fails and error is displayed:

Traceback (most recent call last):
  File "/usr/bin/protontricks", line 5, in <module>
    from protontricks.cli.main import cli
ModuleNotFoundError: No module named 'protontricks'

Also tried the flatpak version:
1. Click "Open"
2. Nothing happens

**Expected behavior**
I should be able to see the GUI of protontricks.

**System (please complete the following information):**
 - OS: Arch Linux
- KERNEL: 6.8.7-zen1-2-zen
- CPU: AMD Ryzen 7 5800X3D 8-Core
- GPU: AMD Radeon RX 6800 XT (radeonsi, navi21, LLVM 17.0.6, DRM 3.57, 6.8.7-zen1-2-zen)
- GPU DRIVER: 4.6 Mesa 24.0.5-arch1.1
- RAM: 32 GB
 - Protontricks installation method: AUR (protontricks and protontricks-git) and flatpak
 - Protontricks version:  protontricks-1.11.1-1  ( I wasn't able to run `protontricks --version` to print the version, it gave error )
 - Steam version: Stable Client , Steam Version:  1709846872

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**

[me@ArchLinux ~]$ protontricks -w
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 5, in <module>
    from protontricks.cli.main import cli
ModuleNotFoundError: No module named 'protontricks

**Comment by RVOtakuMike** [comment]
Needs rebuilt with python 3.12. try the pipx method in the readme, it worked for me. The AUR package (which you are probably using) doesnt. Same issues as you until I did this.

**Comment by Matoking** [comment]
Closing as resolved.
