### ISSUE TITLE
protontricks doesnt work with steam beta 

### ISSUE THREAD

**Issue by stiinkyratz** [Matoking/protontricks#318]
protontricks was working perfectly, i switched to steam beta for the family share and now protontricks crashes every time. after searching all over the internet i finally got confirmation that the issue is with steam beta. If i switch back to stable then I won't be able to access my share library. When will this bug be resolved? Is there any workarounds in place already?

**Comment by stiinkyratz** [comment]
Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.


=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.6.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Currently logged-in Steam user: takingmynameoutforprivacy
Shortcut Chiaki (2505715772) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokemon Stadium 64 (3051348210) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Ultra Moon (2426769443) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi's Island  (3119633885) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kid Chameleon (3216320254) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Animal Crossing: New Leaf  (3413895462) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Wario Land 4 (2279747476) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi's Story (2320479134) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mario 64 (3876184611) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Stadium (3075956636) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Paper Mario (2509286364) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Ocarina of Time (2809665178) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Majora's Mask (3617218515) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby 64: The Crystal Shards (2207943242) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Harvest Moon 64 (4163789730) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Moshi Monsters - Moshlings Theme Park (USA) (2769763288) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Golden Sun: Dark Dawn (2708078679) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Drawn to Life: SpongeBob SquarePants Edition (3573662011) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi Topsy-Turvy (3291933633) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hamtaro: Ham-Ham Heartbreak (3572964973) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hamtaro: Ham-Ham Games (3409718340) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Golden Sun: The Lost Age (3458469487) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Golden Sun (2638480876) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Fire Emblem (3203145669) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Digimon: Battle Spirit (2673069090) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby Tilt 'n' Tumble (2547737952) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hamtaro: Ham-Hams Unite! (4072038746) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi's Cookie (3961542080) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi (2977378343) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokemon - Yellow Version - Special Pikachu Edition (USA, Europe) (CGB+SGB Enhanced) (3250455411) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Red Version (2930918636) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Blue Version (3899475476) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby's Dream Land 2 (3413658896) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby's Dream Land (4073072915) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Harvest Moon GB (3574130826) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Battletoads (4116437559) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Spyro: Enter the Dragonfly (3948073445) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Spyro: A Hero's Tail (2725229167) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sonic Heroes (2515728609) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Sims (3682285259) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pikmin (2771640225) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Luigi's Mansion (3110628175) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Twilight Princess (2334514067) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: The Wind Waker (3123152350) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Ocarina of Time / Master Quest (2779937191) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby Air Ride (2552436508) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Harvest Moon: Magical Melody (4108019585) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Harvest Moon: A Wonderful Life (3463539830) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Animal Crossing (3547291463) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Princess Peach: Showtime! (2845381549) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Luigi's Mansion 3 (4109681942) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mario RPG (3177151883) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Link's Awakening (2312310795) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby and the Forgotten Land (3473363567) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Captain Toad: Treasure Tracker (3171130223) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut ARMS (3848986262) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Astral Chain (2833834578) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Animal Crossing: City Folk (2997673661) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby's Epic Yarn (Proton) (3396627087) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby & The Amazing Mirror (Proton) (3939347993) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby: Nightmare in Dream Land (Proton) (3260082738) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby Super Star (Proton) (2952052413) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Brain Age: Train Your Brain in Minutes a Day! (Proton) (2652484527) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Animal Crossing: Wild World (Proton) (2915976058) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Kirby and the Rainbow Curse (Proton) (2829790481) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Party 10 (Proton) (3540087825) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut The Legend of Zelda: Breath of the Wild (Proton) (3113255530) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Rogue Quest: The Vault of the Lost Tyrant (Proton) (4248698128) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Grand Theft Auto: San Andreas (3600461763) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Drakengard (2286823284) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Dance Dance Revolution X2 (4105209468) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Lollipop Chainsaw (2164278701) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Persona 4 Arena Ultimax (3386714754) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Dark Souls II: Scholar of the First Sin (3981987056) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Drakengard 3 (2977201072) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Persona 5 (3447805933) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Skullgirls 2nd Encore (3878351594) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Persona 4 Arena (3003907764) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Prototype (3817724590) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Alice: Madness Returns (2913011815) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Prototype 2 (3922816237) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ratchet & Clank: Into the Nexus (2280500088) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut LittleBigPlanet 3 (4155586138) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sly 2: Band of Thieves (4167557584) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sly 3: Honor Among Thieves (2963757955) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sly Cooper: Thieves in Time Full Game Trial (2838634829) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ratchet & Clank: Up Your Arsenal (2613552302) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sly Cooper and the Thievius Raccoonus (2556414686) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ratchet & Clank 2: Going Commando (3176939534) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ratchet & Clank (2237885465) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Bullet Girls (2288456100) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hatsune Miku: Project Diva X (3884094674) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Bloodstained: Curse of the Moon (3439249387) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hyperdimension Neptunia Re;Birth3 V Generation (3680809693) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hyperdimension Neptunia Re;Birth2 Sisters Generation (2329237879) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hyperdimension Neptunia U: Action Unleashed (4003685016) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Hyperdimension Neptunia Re;Birth1 (3250935516) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut ES-DE (Program) (3451053530) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Yoshi's Island DS (4081607270) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Wario Land 4 (2272678431) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Drakengard 2 (4073940490) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 1 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider

**Comment by lzq960605** [comment]
https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470

**Comment by Matoking** [comment]
> [#304 (comment)](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470)

As @lzq960605 stated, this was reported in #304 and the comment contains a workaround.

Closing as duplicate.
