### ISSUE TITLE
Provide flatpak package

### ISSUE THREAD

**Issue by gasinvein** [Matoking/protontricks#32]
Steam flatpak now supports utility extensions flathub/com.valvesoftware.Steam/pull/507, so protontricks can be packaged as one.
This way protontricks could be used with Steam flatpak naively.

**Comment by joshua-stone** [comment]
@Matoking As noted by @gasinvein, a Protontricks flatpak could be included in flathub, so in theory the [flatpak setup guide in the README](https://github.com/Matoking/protontricks#installation) could be simplified to:

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --assumeyes flathub com.valvesoftware.Steam com.valvesoftware.Steam.Utility.protontricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```

I've also found the Protontricks flatpak to be easy to build once the conventions for flatpak-builder are understood.

**Comment by Matoking** [comment]
I'll look into this later.

I prefer to point people towards a community maintained package rather than maintaining one myself, unless it's trivial to update and test. The Flatpak manifest would have to include winetricks and other related dependencies, and those would need to be updated when needed as well.

**Comment by joshua-stone** [comment]
As far as flatpaks go, protontricks should be one of the easier ones to maintain as it doesn't depend on very many components and doesn't tie into numerous subsystems. @gasinvein also put in the upfront work setting up a builder manifest which should save a lot of effort. With the initial manifest created and tested, maintaining it shouldn't be any more involved than updating the tag number and commit hash whenever you create a new release as well as periodically checking to make sure all of the dependency versions (winetricks, p7zip, yasm, and cabextract) are recent.

Here's an example ([borrowed from an earlier comment](https://github.com/flathub/com.valvesoftware.Steam/issues/505#issuecomment-550735380)) of updating the protonworks flatpak manifest to 1.3 before building:

```
flatpak remote-add --if-not-exists flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo 
flatpak install --assumeyes flathub-beta com.valvesoftware.Steam
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.yml
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.metainfo.xml
sed -i "4ibranch: beta\nruntime-version: beta" com.valvesoftware.Steam.Utility.protontricks.yml
sed -i "s@tag: .*@tag: \"1.3\"@; s@commit: .*@commit: 5bfe33ea8bbe0c72b7c2175dcb4c7bd4f9fc9434@" com.valvesoftware.Steam.Utility.protontricks.yml
flatpak-builder --repo=protontricks --force-clean build-dir com.valvesoftware.Steam.Utility.protontricks.yml
flatpak --user remote-add --no-gpg-verify --if-not-exists protontricks protontricks
flatpak --user --assumeyes install protontricks com.valvesoftware.Steam.Utility.protontricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```
I think the end goal is to include projects like this on flathub so multiple remotes don't have to be installed, but ideally have them maintained by upstream developers.

**Comment by Matoking** [comment]
Thanks, I got the build manifest working and tested the environment for a bit.

Executables like `ar`, `perl` and `unrar` are not installed in the manifest, but winetricks either has workarounds for missing executables (`ar` and `unrar`), or the commands themselves are used so infrequently it's probably not a problem (`perl` is used in a single Steam-related verb, which wouldn't make sense to run since there's no need to install a Windows version of Steam inside a Proton prefix).

The new update for Steam was pushed to stable [a few hours ago](https://github.com/flathub/com.valvesoftware.Steam/pull/509), so I'm guessing the manifest should build without the `branch: beta` and `runtime-version: beta` options shortly and also be eligible for submission to Flathub.

**Comment by gasinvein** [comment]
@Matoking `ar` and `unrar` should be easy to add, but `perl` may be tricky.
> the manifest should build without the `branch: beta` and `runtime-version: beta`

After flathub/com.valvesoftware.Steam#509, it should be set to `stable` instead of `beta`. 

I'll push and update to the manifest. Feel free to reuse it.

**Comment by joshua-stone** [comment]
@Matoking With the latest Protontricks manifest version provided by @gasinvein, it's easier than ever to build Protontricks with extra utilities sans Perl. It's now possible to build it with the stable branch of Steam:

```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install --assumeyes flathub com.valvesoftware.Steam org.freedesktop.Sdk//19.08
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.yml
wget https://raw.githubusercontent.com/gasinvein/flatpak-apps-staging/com.valvesoftware.Steam.Utility.protontricks/master/com.valvesoftware.Steam.Utility.protontricks.metainfo.xml
sed -i "s@tag: .*@tag: \"1.3\"@; s@commit: .*@commit: 5bfe33ea8bbe0c72b7c2175dcb4c7bd4f9fc9434@" com.valvesoftware.Steam.Utility.protontricks.yml
flatpak-builder --repo=protontricks --force-clean build-dir com.valvesoftware.Steam.Utility.protontricks.yml
flatpak --user remote-add --no-gpg-verify --if-not-exists protontricks protontricks
flatpak --user --assumeyes install protontricks com.valvesoftware.Steam.Utility.protontricks
echo "alias protontricks-flat='flatpak run --command=protontricks com.valvesoftware.Steam --no-runtime'" >> ~/.bashrc
```
As for actually packaging Perl, I don't see a dedicated runtime extension or a [shared module](https://github.com/flathub/shared-modules), although there are some lines for building it in [io.github.Hexchat.Plugin.Perl.json](https://github.com/flathub/io.github.Hexchat.Plugin.Perl/blob/master/io.github.Hexchat.Plugin.Perl.json#L33). Perhaps these lines could also be used for Protontricks?

**Comment by Matoking** [comment]
I've submitted the app for inclusion into the Flathub repository:
https://github.com/flathub/flathub/pull/1259

Thanks for the help so far. :+1:
