### ISSUE TITLE
Can't install vcrun2022

### ISSUE THREAD

**Issue by meneraing** [Matoking/protontricks#321]
**Describe the bug**
Can't install vcrun2022 (MICROSOFT VISUAL C++ 2015 - 2022 RUNTIME) for a steam game (Cyberpunk 2077).

**To Reproduce**
1. Run protontricks 
2. Try to install d3dcompiler_47 and vcrun2022 (following this [guide:](https://wiki.redmodding.org/cyberpunk-2077-modding/for-mod-users/users-modding-cyberpunk-2077/modding-on-linux)
3. Installation fails with error 0x80070643 
![image](https://github.com/user-attachments/assets/e975bf96-25c7-451b-86c2-e4c54e179267)

**Expected behavior**
There should be no errors while isntalling the windows dll.

**System (please complete the following information):**
 - Distro: CachyOS (Arch based) 
 - Kernel: Linux 6.10.0-3-cachyos
 - Protontricks installation method: pacman
 - Protontricks version: 1.11.1
 - Steam version: 1721173382

**Additional context**
I have previously installed the mentioned dlls without problems. They are required to run CET (Cyber Engine Tweaks) for Cyberpunk 2077. After that I installed reshade from [here](https://github.com/kevinlekiller/reshade-steam-proton). And the CET stopped working. I decided to reinstall CET and since reshade installs its own d3dcompiler_47 I thought of running protontricks again, clear the prefix and reinstall the dlls but i run into this issue.
Here's the log from the installer: [log file](https://gist.github.com/meneraing/b5e6d8bf644491faef0fdc0f2c63d7d5)

**Comment by meneraing** [comment]
Uninstalling protontricks and reinstalling solved the issue...

**Comment by HungryHedgehog** [comment]
I have the same issue and reinstalling did not fix it

**Comment by ehjr5u** [comment]
that did NOT work

**Comment by d3aths** [comment]
still a bug now. reinstalling proton tricks doesnt help. vcrun installs fine on winetricks itself but not on protontricks. using it as part of a script to install mo2 for linux. returns error 131 for the x86 version. ive been struggling with this for 5 whole ass days now no amount of manual forcing or even extracting the dlls and shoving them into the prefix manually is working.

**Comment by whitetrashyt** [comment]
Still having this problem. Worked around by using winetricks directly:

`WINEPREFIX=/path/to/proton/prefix winetricks cmd vcrun2022`

you can find the proton prefix location at the top of the protontricks window when game is selected.
