### ISSUE TITLE
Crash after select game.

### ISSUE THREAD

**Issue by onehoon** [Matoking/protontricks#322]
i launched this and selected app.

then crash with the below log

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.15.6.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 5 Steam library folders
Steam library folder /run/media/deck/EE4S5 not found. Protontricks might not have access to the directory.
Steam library folder /run/media/deck/USB Flash Disk not found. Protontricks might not have access to the directory.
Steam library folder /run/media/deck/c3ca8c5a-fe2b-4b40-a434-adb922559032 not found. Protontricks might not have access to the directory.
Currently logged-in Steam user: onehoon
Shortcut Chiaki (3619333728) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut PS Remote Play (3706402377) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Super Mario Bros. Wonder (2875954814) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut yuzu (2394707436) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 2 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/userdata/119776288/config/grid/4035548067_icon.png has unusual size, resizing
App icon /home/deck/.local/share/Steam/userdata/119776288/config/grid/4045585621_icon.ico has unusual size, resizing

**Comment by sTiKyt** [comment]
Why did you close it, there's still a problem
