### ISSUE TITLE
Not detecting Steam Snap by default

### ISSUE THREAD

**Issue by YamiYukiSenpai** [Matoking/protontricks#337]
**Describe the bug**
Steam Snap isn't detected by the Flatpak version

**To Reproduce**
1. Launch Protontricks from GUI
2. Command fails and error is displayed
> Steam installation directory could not be found.

**Expected behavior**
Steam snap is detected

**System (please complete the following information):**
 - Distro: KDE Neon Unstable Edition (based on Ubuntu 22.04)
 - Protontricks installation method: Flatpak
 - Protontricks version: 1.11.1
 - Steam version: 1721173382

**Additional context**
Steam is running as a Snap.  ProtonUp-Qt can detect it by default.

I used `~/snap/steam/common/.local/share/Steam` as the Steam directory
```
STEAM_DIR="/home/yamiyuki/snap/steam/common/.local/share/Steam" flatpak run com.github.Matoking.protontricks --gui
```

There are 2 Steam Snap data directories:
* `~/snap/steam` - current default
* `~/.snap/data/steam` - experimental hidden Snap directory

**If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**

For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -vv 42 faudio` instead and copy the output here.

If the output is very long, consider creating a gist using [gist.github.com](https://gist.github.com/).

**Comment by Matoking** [comment]
Added support to `master` branch, and will look into merging it into `appinfo_v29` branch when I have the time, which is essentially the development branch at the moment due to the ongoing issue with the `vdf` library.
