### ISSUE TITLE
Gtk-Message: 19:39:53.090: Failed to load module "canberra-gtk-module"

### ISSUE THREAD

**Issue by changchiyou** [Matoking/protontricks#338]
**Describe the bug**

**To Reproduce**
1. run `flatpak run com.github.Matoking.protontricks --gui` and select the game

   ![image](https://github.com/user-attachments/assets/3f3b49a4-3ce3-41a4-a227-c7b50f30e2b1)

3. Error is displayed
   
   ![image](https://github.com/user-attachments/assets/8edc4a9c-78b2-4a15-89cc-7717ffbe2c3f)

4. Select `Select the default wineprefix` -> `install a font` -> `cjkfonts`
5. After seconds, another error displayed again and protontricks back to 'What would you like to do to this wineprefix?' step

   ![image](https://github.com/user-attachments/assets/a56caf88-f591-460f-8c4c-408d9839b35d)

**Expected behavior**
Install my desire fonts for specific steam game.

**System (please complete the following information):**
 - Distro: Ubuntu 22.04
 - Protontricks installation method: Flatpak
 - Protontricks version: protontricks (1.11.1)
 - Steam version: (No beta chosen) Steam Client Update - July 16th

**Additional context**

I have already followed https://askubuntu.com/questions/342202/failed-to-load-module-canberra-gtk-module-but-already-installed , but the error still exists.

> **If the error happens when trying to run a Protontricks command, run the command again using the `-vv` flag and copy the output!**
> 
> For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -vv 42 faudio` instead and copy the output here.
> 
> If the output is very long, consider creating a gist using [gist.github.com](https://gist.github.com/).

https://gist.github.com/changchiyou/96582c932f52565f17073d0ab09cd497

**Comment by Matoking** [comment]
Sorry for the delayed response.

The `Failed to load module "canberra-gtk-module"` can be ignored if nothing else goes wrong. It's annoying but harmless. The log file you posted seems to state that the installation succeeded, aside from one "unifont already installed, skipping" message at the end that also seems harmless. Was it the error message you meant with "After seconds, another error displayed again"?

The logs printed on the console contain a lot of (usually) superfluous details. Winetricks should usually pop up an error dialog if something did go wrong.

**Comment by changchiyou** [comment]
@Matoking Thanks for your reply!

> Was it the error message you meant with "After seconds, another error displayed again"?

It was my grammer mistake, it should be "After seconds, another **same** error displayed again" instead.
