### ISSUE TITLE
Proton Installation could not be found

### ISSUE THREAD

**Issue by JohnTheCoolingFan** [Matoking/protontricks#339]
**Describe the bug**
Error when selecting a game

**To Reproduce**
1. Open protontricks gui
2. Select a game

**Expected behavior**
Menu of actions to perform on the selected game

**System (please complete the following information):**
 - Distro: Gentoo
 - Protontricks installation method: Flatpak Beta
 - Protontricks version: 1.11.1
 - Steam version: Steam Beta 1726025281

**Additional context**

Using proton version GE-Proton9-13, installed using a flatpak app ProtonPlus. Steam is also installed via flatpak.

```
Protontricks was closed due to the following error:

Proton installation could not be found!

=============

Please include this entire error message when making a bug report.
Log messages:

Running inside Flatpak sandbox, version 1.14.6.
Found Steam directory at /home/jtcf/.var/app/com.valvesoftware.Steam/.local/share/Steam
Using default Steam Runtime at /home/jtcf/.var/app/com.valvesoftware.Steam/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 387990
Currently logged-in Steam user: coolercircutin
Found 0 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
$PROTON_VERSION was set but matching Proton installation could not be found.
```

**Comment by Awk34** [comment]
My issue seemed to be with protontricks finding my default Proton installation. I ran this instead and was able to get things to work:

```
$ PROTON_VERSION="GE-Proton9-14" /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protontricks com.github.Matoking.protontricks --no-term --gui
```

This uses my Proton version here: `~/.steam/steam/compatibilitytools.d/GE-Proton9-14`

**Comment by Matoking** [comment]
What is the output if you run `flatpak run com.github.Matoking.protontricks -vv --gui`?

Protontricks should print additional logs which should hopefully explain why it's detecting the wrong version of Proton. Have you set that specific version of Proton globally via Steam settings, or as a game-specific setting?

**Comment by JohnTheCoolingFan** [comment]
The output from that command is here: https://gist.github.com/JohnTheCoolingFan/8b465f97c86f4c03732efd1d9b3d86a8

Due to [a bug](https://github.com/ValveSoftware/steam-for-linux/issues/11312) in steam flatpak distribution I had to reset to stable. And protontricks installation is now from flathub stable.

**Comment by Awk34** [comment]
For me my global Steam default compat tool is `GE-Proton9-14` but for the specific game I'm currently using protontricks for I have set the compat tool to be Steam Tinker Launch which then uses `GE-Proton9-14`.

**Comment by Matoking** [comment]
> The output from that command is here: https://gist.github.com/JohnTheCoolingFan/8b465f97c86f4c03732efd1d9b3d86a8
> 
> Due to [a bug](https://github.com/ValveSoftware/steam-for-linux/issues/11312) in steam flatpak distribution I had to reset to stable. And protontricks installation is now from flathub stable.
> 
> I have set the proton version for all win games to `GE-Proton9-13`, which I installed using ProtonPlus flatpak application

I can see `$PROTON_VERSION was set but matching Proton installation could not be found.` in the logs. Did you set `$PROTON_VERSION` specifically when running `protontricks -vv --gui`?

If not, you might have set a value in `~/.bashrc`, `~/.profile`  or other similar file which is interfering and causing Protontricks to _always_ use that Proton version. Just setting the Proton version via Steam (either globally or on a per-game basis) should be adequate and Protontricks should use the correct Proton depending on the game.

Otherwise, try running the command without that variable set. This should result in additional logs since Protontricks won't bother looking through configuration if `$PROTON_VERSION` is set.

**Comment by jzabulenas** [comment]
> My issue seemed to be with protontricks finding my default Proton installation. I ran this instead and was able to get things to work:
> 
> ```
> $ PROTON_VERSION="GE-Proton9-14" /usr/bin/flatpak run --branch=stable --arch=x86_64 --command=protontricks com.github.Matoking.protontricks --no-term --gui
> ```
> 
> This uses my Proton version here: `~/.steam/steam/compatibilitytools.d/GE-Proton9-14`

What I did instead is set the `PROTON_VERSION` environment variable like this, in `.bash_profile`: `export PROTON_VERSION=GE-Proton10-10`. I think this is a bit more user friendly - Protontricks will be able to pick it up just like that.

I had to install the GE-Proton10-10 version using ProtonUp-Qt first, as it came with Bazzite.

Inside of my `~/.steam/steam/compatibilitytools.d/` directory, I only had LegacyRuntime directory - only after installing GE-Proton10-10 did I see it appear.

I wonder why is Proton Experimental not showing up here. I mean, I am using it to game on Steam...
