### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by KADA-Jeffrey** [Matoking/protontricks#343]
steam deck oled

protontricks>Black Myth: Wukong>

Protontricks was closed due to the following error:Traceback (most recent call last):  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper    return cli_func(self, *args, **kwargs)           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 277, in main    proton_app = find_proton_app(                 ^^^^^^^^^^^^^^^^  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app    tool_app = find_steam_compat_tool_app(               ^^^^^^^^^^^^^^^^^^^^^^^^^^^  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app    appinfo_sections = [                       ^  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>    appinfo_sections = [                       ^  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections    raise SyntaxError(SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.=============Please include this entire error message when making a bug report.Log messages:Running inside Flatpak sandbox, version 1.14.4.Found Steam directory at /home/deck/.local/share/SteamUsing default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtimeWINETRICKS environment variable is not available. Searching from $PATH.Found 1 Steam library foldersCurrently logged-in Steam user: short0955604Found 1 Steam shortcuts runnin

**Comment by Tygorgon** [comment]
Same issue here. Happened after the most recent Steam update. Not using Steam Beta either.

**Comment by klausman** [comment]
The README mentions this fix (even if you _don't_ use the Steam Beta). Worked for me:

https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470

**Comment by Tygorgon** [comment]
> The README mentions this fix (even if you _don't_ use the Steam Beta). Worked for me:
> 
> [#304 (comment)](https://github.com/Matoking/protontricks/issues/304#issuecomment-2220599470)

Ahh it works for non-beta too. Thanks!

**Comment by Matoking** [comment]
Closing issue as this was resolved by 1.12.0 update.
