### ISSUE TITLE
Protontricks crashing

### ISSUE THREAD

**Issue by JailAir2** [Matoking/protontricks#344]
**Describe the bug**
The app won't lauch applications. I just get the long error pasted below

**To Reproduce**
1. Run ant app via proton tricks
2. Launch fails and error is displayed

**Expected behavior**
I expect apps to open regularly

**System (please complete the following information):**
 - Distro: Steam OS 3.5 Stable on Steam Deck
 - Protontricks installation method: Flatpak from discover store
 - Protontricks version: 1.11.1
 - Steam version: 1726088054

**Additional context**

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/app/lib/python3.11/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 609, in <listcomp>
    appinfo_sections = [
                       ^
  File "/app/lib/python3.11/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/deck/.local/share/Steam
Found 2 Steam library folders
Multiple compatdata directories found for app 1493710
Multiple compatdata directories found for app 2805730
Currently logged-in Steam user: swaggerchild
Shortcut Google Chrome (4032870389) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Grand Theft Auto V (3456375018) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Discord (4083841033) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (3495118083) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (2945955094) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (3295278843) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (3436477773) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (Ryujinx) (3869211795) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe 3.0.1 [0100152000022800][v1179648][UPD] (Ryujinx) (3909725493) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Heroic Games Launcher (3857398453) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Nested Desktop (2601165838) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Prince of Persia: The Lost Crown (2876823237) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (3790827695) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (Ryujinx) (4240142567) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ludusavi (3598120668) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 10 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/userdata/106281302/config/grid/4188596612_icon.png has unusual size, resizing
Calling `protontricks` with the command: ['--no-background-wineserver', '--no-term', '-c', "wine '/run/media/deck/d4a59280-4e0a-433d-bda2-15a98b2d3ab3/Lollipop Chainsaw RePOP [DODI Repack]/Setup.exe'", '3328250033']
Running inside Flatpak sandbox, version 1.14.4.
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 1493710
Multiple compatdata directories found for app 2805730
Currently logged-in Steam user: swaggerchild
Shortcut Google Chrome (4032870389) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Grand Theft Auto V (3456375018) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Discord (4083841033) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (3495118083) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (2945955094) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (3295278843) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (3436477773) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (Ryujinx) (3869211795) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe 3.0.1 [0100152000022800][v1179648][UPD] (Ryujinx) (3909725493) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Heroic Games Launcher (3857398453) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Nested Desktop (2601165838) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Prince of Persia: The Lost Crown (2876823237) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Pokémon Scarlet (Ryujinx) (3790827695) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Mario Kart 8 Deluxe (Ryujinx) (4240142567) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ludusavi (3598120668) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 10 Steam shortcuts running using Steam compatibility tools

**Comment by Matoking** [comment]
You need to update to 1.12.0. Older versions don't have support for the newer appinfo.vdf format.
