### ISSUE TITLE
Cascade of test failures introduced by commit 08d596a

### ISSUE THREAD

**Issue by Nanotwerp** [Matoking/protontricks#346]
**Describe the bug**
I get a cascade of errors upon trying to build `protontricks` after commit 08d596a, with this being the first error. I'm not sure if this is a NixOS-specific issue or not, but the changes in the test code are what causes it. The build is successful if the commit is reverted.
```
=================================== FAILURES ===================================
________________________ TestCLIRun.test_run_executable ________________________

self = <cli.test_launch.TestCLIRun object at 0x7ffff5cb2420>
steam_app_factory = <function steam_app_factory.<locals>.func at 0x7ffff4f7d940>
default_proton = <protontricks.steam.SteamApp object at 0x7ffff53aa1a0>
command_mock = <conftest.CommandMock object at 0x7ffff4fab800>
gui_provider = <conftest.MockSubprocess object at 0x7ffff4fab7d0>
launch_cli = <function _run_cli.<locals>.func at 0x7ffff4f7dee0>

    def test_run_executable(
            self, steam_app_factory, default_proton,
            command_mock, gui_provider, launch_cli):
        """
        Run an EXE file by selecting using the GUI
        """
        steam_app = steam_app_factory("Fake game", appid=10)
    
        # Fake the user selecting the game
        gui_provider.mock_stdout = "Fake game: 10"
    
        launch_cli(["test.exe"])
    
        # 'test.exe' was executed
>       command = command_mock.commands[-1]
E       IndexError: list index out of range

/build/source/tests/cli/test_launch.py:30: IndexError
```

**To Reproduce**
1. Attempt to build `protontricks` after commit 08d596a
2. Build fails during testing stage and error is displayed

**Expected behavior**

**System (please complete the following information):**
 - Distro: [NixOS]
 - Protontricks installation method: [nixpkgs]
 - Protontricks version: 1.12.0

**Comment by Matoking** [comment]
> I'm not sure if this is a NixOS-specific issue or not, but the changes in the test code are what causes it. 

Does this mean that deleting the test function means all tests pass correctly even with the change to `cli/main.py`? If so, monkeypatching in that test function could be the culprit.

If not, one guess could be that the Python interpreter used for the NixOS package is not [truncating the first command parameters](https://docs.python.org/3/library/sys.html#sys.argv) in `sys.argv` properly.

Protontricks uses it to determine whether any arguments were provided, which should also account for cases like `protontricks`, `python -m foo.bar`, `python venv/bin/protontricks` and so forth which are all coalesced into `sys.argv[0]`, meaning `len(sys.argv) == 1` should apply in all three cases if no other parameters are provided.

**Comment by Staudey** [comment]
Seeing these errors in the Solus package build too. In this case neither reverting the test changes alone, nor the mentioned commit as a whole changes the outcome though. I'm still looking for the origin of the issue.

**Comment by Staudey** [comment]
I'm seeing the same issue in the Solus package build. Reverting just the test change, but not the `cli/main.py` one **doesn't** fix the issue. The whole change has to be reverted.

**Comment by Nanotwerp** [comment]
> I'm seeing the same issue in the Solus package build. Reverting just the test change, but not the `cli/main.py` one **doesn't** fix the issue. The whole change has to be reverted.

I think it has something to do with the `command_mock` function not being adjusted to account for protontricks now opening with the GUI by default. Each of the cascading errors are all from `command = command_mock.commands[-1]` trying to access an index out of range.

**Comment by Matoking** [comment]
As @kira-bruneau figured out in NixOS/nixpkgs#343068, something in the Nix build sandbox is causing the test `test_run_no_args` under `tests/cli/test_main.py` to fail. I can produce working packages using:

```sh
$ NIXPKGS_ALLOW_UNFREE=1 nix repl
nix-repl> :l <nixpkgs>
Added 21412 variables.

nix-repl> :b pkgs.protontricks.overrideAttrs (finalAttrs: previousAttrs: { src = fetchFromGitHub { owner = "Matoking"; repo = "protontricks"; rev = "1.12.0"; sha256 = "sha256-dCb8mcwXoxD4abJjLEwk5tGp65XkvepmOX+Kc9Dl7fQ="; }; disabledTests = [ "test_run_no_args" ]; })

This derivation produced the following outputs:
  dist -> /nix/store/gdr06kgdl5bcs4k403g6jwy6ry607z73-protontricks-1.11.1-dist
  out -> /nix/store/x73v8rw1xk57r76khbqlyj8pjs3gprcl-protontricks-1.11.1
```

The `protontricks` executable under `out` has working "GUI used by default if no args" behavior; this works on both Arch Linux + Nix and NixOS proper.

**Comment by Matoking** [comment]
Reworked the CLI entrypoints so the brittle `sys.argv` monkeypatching isn't necessary. This fixed the tests when building inside a Nix sandbox.

**Comment by Staudey** [comment]
Can confirm that tests are fixed in the Solus package build too, thanks! :+1:
