### ISSUE TITLE
Protontricks fail

### ISSUE THREAD

**Issue by Myew420** [Matoking/protontricks#348]
I think it's worth mentioning that since the pacman update, I haven't been able to upgrade AUR packages, including protontricks.
Here's what I'm seeing:

Protontricks was closed due to the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/protontricks/cli/util.py", line 159, in wrapper
    return cli_func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/cli/main.py", line 339, in main
    proton_app = find_proton_app(
                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 848, in find_proton_app
    tool_app = find_steam_compat_tool_app(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 609, in find_steam_compat_tool_app
    appinfo_sections = [
                       ^
  File "/usr/lib/python3.12/site-packages/protontricks/steam.py", line 531, in iter_appinfo_sections
    raise SyntaxError(
SyntaxError: Invalid file magic number. The appinfo.vdf version might not be supported by the current version of Protontricks - please check for updates.

=============

Please include this entire error message when making a bug report.
Log messages:

Found Steam directory at /home/andrej/.local/share/Steam
Found 3 Steam library folders
Multiple compatdata directories found for app 1382330
Currently logged-in Steam user: andrejp3cic
Couldn't find custom shortcuts. Maybe none have been created yet?
Using 'zenity' as GUI provider
Calling `protontricks` with the command: ['--no-background-wineserver', '--no-term', '-c', 'wine /mnt/intern/Reloaded-II/Reloaded-II.exe', '1687950']
Using default Steam Runtime at /home/andrej/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 3 Steam library folders
Multiple compatdata directories found for app 1382330
Currently logged-in Steam user: andrejp3cic
Couldn't find custom shortcuts. Maybe none have been created yet?

**Comment by eMPeBeYT** [comment]
Running inside Flatpak sandbox, version 1.14.4.
Found Steam directory at /home/deck/.local/share/Steam
Using default Steam Runtime at /home/deck/.local/share/Steam/ubuntu12_32/steam-runtime
WINETRICKS environment variable is not available. Searching from $PATH.
Found 2 Steam library folders
Multiple compatdata directories found for app 381210
Multiple compatdata directories found for app 635260
Multiple compatdata directories found for app 597170
Multiple compatdata directories found for app 739630
Currently logged-in Steam user: empebe
Shortcut zShaderCacheKiller.sh (3249018148) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Google Chrome (3412331543) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Discord (3195693479) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Spotify (3520296753) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Ubisoft Connect (4063097571) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Rocket League® (3450285581) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Sober (3692587251) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut NVIDIA GeForce NOW (3270718814) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Shortcut Discord (2699320377) does not have a prefix. It's either not a Proton app or it hasn't been launched yet.
Found 4 Steam shortcuts running using Steam compatibility tools
Using 'yad' as GUI provider
App icon /home/deck/.local/share/Steam/userdata/443963787/config/grid/3716789147_icon.png has unusual size, resizing
App icon /home/deck/.local/share/Steam/userdata/443963787/config/grid/2895607658_icon.ico has unusual size, resizing
User has configured app Proton version (CompatToolMapping): GE-Proton9-12
The current device is a Steam Deck
We're on a Steam Deck, checking if compatibility profile is available for the app
App has Steam Deck compatibility profile with Proton version: proton-7.0-6
App has default compatibility tool mapping in the Steam Play manifest: proton-experimental
Could not find configured Proton installation!
Active Proton installation could not be found automatically.

**Comment by Matoking** [comment]
You need to update Protontricks to 1.12.0. I don't know why specifically you cannot upgrade AUR packages, but note that you cannot upgrade AUR packages through `pacman` itself, you have to use an AUR helper such as paru or build the package manually using `makepkg`.
