### ISSUE TITLE
protontricks does not find Deadlight (211400)

### ISSUE THREAD

**Issue by NoXPhasma** [Matoking/protontricks#37]
When I try to use protontricks with a game, no longer available on the Steam Store, it will fail and give this message:

```
$ protontricks 211400 --gui
Steam app with the given app ID could not be found. Is it installed, Proton compatible and have you launched it at least once? You can search for the app ID using the following command:
$ protontricks -s <GAME NAME>
```

It would be great if protontricks would work on all installed games, not only those still available.

**Comment by Matoking** [comment]
Protontricks only deals with local files (eg. files that appear when you install a game); it shouldn't matter whether the game is in the store or not. I tested with Duke Nukem 3D: Megaton Edition, which worked just fine despite no longer having a store page.

Could you try installing the newest development version from master? It has a fix for the bug where Protontricks cannot find a game if it's inside a `SteamApps` directory instead of ` steamapps`, even though it should. This could be the reason why it's not working.

If you're using pipx, the following should install the development version:
```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@master protontricks
```

**Comment by NoXPhasma** [comment]
Even with the latest master it won't find the game (Deadlight) and it's not related to the library folder, as other games installed there will be shown in the GUI and are accessible by ID.

But I was wrong with being the game not listed on the Store anymore. It's still available and I must have been confused it with another game. Anyway, it still won't be found by protontricks. So this seems to be more an issue with [that exact game](https://steamdb.info/app/211400/). On a quick comparison it seems all other games using Proton are listed. I will change the issue title accordingly.

**Comment by Matoking** [comment]
Okay, try opening the installation directory for the game (right-click the game in Steam library -> Properties -> Local files -> Browse local files...). The game should be installed within a path such as `<library_root>/steamapps/common/Deadlight`. Please check the following:

* Is there a file called `<library_root>/steamapps/appmanifest_211400.acf`. If so, what are its contents?
* Is there a directory called `<library_root>/steamapps/compatdata/211400`? What about `<library_root>/steamapps/compatdata/211400/pfx`?

**Comment by NoXPhasma** [comment]
1) Yes, appmanifest_211400.acf:
```
"AppState"
{
	"appid"		"211400"
	"Universe"		"1"
	"name"		"Deadlight"
	"StateFlags"		"4"
	"installdir"		"Deadlight"
	"LastUpdated"		"1563823901"
	"UpdateResult"		"0"
	"SizeOnDisk"		"4679194066"
	"buildid"		"27194"
	"LastOwner"		"76561197992914963"
	"BytesToDownload"		"1772544"
	"BytesDownloaded"		"1772544"
	"AutoUpdateBehavior"		"0"
	"AllowOtherDownloadsWhileRunning"		"0"
	"ScheduledAutoUpdate"		"0"
	"InstalledDepots"
	{
		"211401"
		{
			"manifest"		"2231028220962401695"
		}
		"211419"
		{
			"manifest"		"3412488096432106295"
			"dlcappid"		"211419"
		}
	}
	"MountedDepots"
	{
		"211401"		"2231028220962401695"
		"211419"		"3412488096432106295"
	}
	"DlcDownloads"
	{
		"211419"
		{
			"BytesDownloaded"		"312273376"
			"BytesToDownload"		"312273376"
		}
	}
	"UserConfig"
	{
		"language"		"german"
	}
}
```

2) Yes, it is.

**Comment by Matoking** [comment]
Nothing unusual there.

What is the output when you run the command `protontricks -v -s deadlight`?
Is the game installed in a different location compared to all the other Proton games?

**Comment by NoXPhasma** [comment]
```
protontricks (INFO): Found Steam directory at /home/noxp/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/noxp/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 2 Steam library folders
protontricks (INFO): Currently logged-in Steam user: noxphasma
protontricks (INFO): Found 2 Steam shortcuts running under Proton
Found no games.

NOTE: A game must be launched at least once before protontricks can find the game.
```

**Comment by Matoking** [comment]
I pushed a change to `log_more` branch that prints more debug information and hopefully helps with finding the root cause for this issue. Install it with pipx like this:
```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@log_more protontricks
```

Then try running the command `protontricks -v -s deadlight` again. This time it should print a lot more information. Upload the output with [Github Gist](https://gist.github.com/) and link it here if it's long to prevent cluttering this thread.

**Comment by NoXPhasma** [comment]
I did that but it didn't had any other output as before.

However, I was curious and moved the game to the main library folder and suddenly it will be found by protontricks. When I move it back to the previous library folder it won't be found again. I can not think of any reason why this is the case, as other games installed in the same library folder will be found.

**Comment by Matoking** [comment]
> I did that but it didn't had any other output as before.
> 
> However, I was curious and moved the game to the main library folder and suddenly it will be found by protontricks. When I move it back to the previous library folder it won't be found again. I can not think of any reason why this is the case, as other games installed in the same library folder will be found.

Try reopening the terminal emulator if it's not printing anything new. pipx seems to have the issue that the update does not take effect until the shell is restarted.

**Comment by NoXPhasma** [comment]
I did that, without any success. Even switched to bash (I use ZSH) but it's the same output.

**Comment by Matoking** [comment]
Try running the command `protontricks --version` to check what version you have installed.

If you have installed Protontricks through another method (eg. an AUR package), that might be hiding the pipx installation.

**Comment by NoXPhasma** [comment]
I have it installed through pipx, as it's described in the readme. The output is `protontricks (1.3)`

**Comment by Matoking** [comment]
That means the development version nor the `log_more` were installed for some reason.

Maybe try running `~/.local/bin/protontricks --version` to check if it returns a different result?

**Comment by NoXPhasma** [comment]
For some reason it never updated the protontricks build, I had to uninstall it and then install the log_more build. Now it's showing the correct build.

Here's the output: https://gist.github.com/NoXPhasma/fab7e3c8525bba7af6df922e2f22e3cd

**Comment by Matoking** [comment]
Protontricks seems to find the app just fine, but determines that the Proton prefix hasn't been created yet.

I'm guessing the `/media/daten/SteamApps/steamapps/compatdata/211400/pfx.lock` file doesn't exist?
If it doesn't, does starting the game fix it?
Does the `compatdata/211400` directory contain other files like `tracked_files` or `version`?

**Comment by NoXPhasma** [comment]
It exists, same for the other two files:
```
drwxrwxr-x 4 noxp noxp 4,0K Nov 15 16:25 pfx
-rwxrwxr-x 1 noxp noxp    0 Nov 15 16:25 pfx.lock
-rw-rw-r-- 1 noxp noxp  93K Okt 28 21:41 tracked_files
-rw-rw-r-- 1 noxp noxp    7 Nov 15 16:25 version
```

As I said, the game is being found in a different library folder, when I simply move the compatibility folder over as well. I'm really confused as to why protontricks has problems with this game only in that particular library folder.

**Comment by Matoking** [comment]
Okay, could you check which of the following directories exist?

`/media/daten3/SteamApps/steamapps/compatdata/211400`
`/media/daten/SteamApps/steamapps/compatdata/211400`
`/home/noxp/.steam/steam/steamapps/compatdata/211400`

If there are multiple compatdata directories with the name `211400`, Protontricks might be picking one that is no longer used but which still exists for some reason.

**Comment by NoXPhasma** [comment]
This was the right track! That folder existed in the `/media/daten3/SteamApps/steamapps/compatdata/211400` as well and removing that fixed the issue!

**Comment by NoXPhasma** [comment]
Maybe it would be a good idea to let protontricks inform the user that there are more than one compatibility folder. To prevent such issues.

**Comment by Matoking** [comment]
Yeah, that is the problem and I was under the impression that Steam would remove the no-longer-used compatdata directories once the prefix is moved elsewhere.

I'll have to add a workaround for this later. Ideally Steam has the path to the correct compatdata directory somewhere, although checking modification times would likely work fine as well.

**Comment by Matoking** [comment]
Modification time for `pfx.lock` is updated every time the game is launched, so that ought to make it the most reliable option for finding the correct prefix. I've updated the master branch with this fix.
