### ISSUE TITLE
RPG Maker RTP with Protontricks?

### ISSUE THREAD

**Issue by bayazidbh** [Matoking/protontricks#46]
So, with a whole bunch of RPG Maker games on Steam now, I think it might be good to add installing its runtime package using Protontricks. I have several on my library, they tended to black screen but when I ripped the files, put it in my normal Wine prefix, and install RPGM RTP for that prefix, it works perfectly. Adding the ability to do that on Protontricks for the specific game prefix would greatly streamline the process.

Or is that more on the scope of Winetricks? I'm sorry, I'm not too familiar with the scope of this project.

**Comment by Matoking** [comment]
Protontricks is only a wrapper for Winetricks, so you'd have to do implement this either in Winetricks or use the `-c` parameter.

In the latter case, you would run a set of commands for each game like this:
```
protontricks -c "wget https://test.com/RTP.exe; wine RTP.exe" <APPID>
```

This works as well, but doesn't have the brevity you get with Winetricks.
