### ISSUE TITLE
protontricks gives error when trying to run GUI

### ISSUE THREAD

**Issue by NodokaHanamura** [Matoking/protontricks#47]
I simply tried to run Protontricks (installed via pipx), and got this.

Traceback (most recent call last):
  File "/home/nikki/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/nikki/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/cli.py", line 150, in main
    steam_lib_paths=steam_lib_paths
  File "/home/nikki/.local/pipx/venvs/protontricks/lib/python3.6/site-packages/protontricks/steam.py", line 734, in get_steam_apps
    os.path.join(path, "steamapps", "appmanifest_*.acf")
  File "/usr/lib/python3.6/glob.py", line 20, in glob
    return list(iglob(pathname, recursive=recursive))
  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.6/glob.py", line 71, in _iglob
    for dirname in dirs:
  File "/usr/lib/python3.6/glob.py", line 72, in _iglob
    for name in glob_in_dir(dirname, basename, dironly):
  File "/usr/lib/python3.6/glob.py", line 83, in _glob1
    return fnmatch.filter(names, pattern)
  File "/usr/lib/python3.6/fnmatch.py", line 52, in filter
    match = _compile_pattern(pat)
  File "/usr/lib/python3.6/fnmatch.py", line 46, in _compile_pattern
    return re.compile(res).match
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 855, in parse
    p = _parse_sub(source, pattern, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 765, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.6/sre_parse.py", line 416, in _parse_sub
    not nested and not items))
  File "/usr/lib/python3.6/sre_parse.py", line 553, in _parse
    raise source.error(msg, len(this) + 1 + len(that))
sre_constants.error: bad character range D-1 at position 7

AFAIK, Python, steam and all other dependencies are up to date.

I am running Linux Mint 19.3, based on Ubuntu 18 "Bionic" on Linux Kernel 5.3.0.

**Comment by Matoking** [comment]
That's weird; my guess is that one of your Steam library paths has weird characters that are not playing nice with the glob module?

Could you run the following two commands in a new terminal and paste what it prints? It should print a list of your Steam library directories.
```
source ~/.local/pipx/venvs/protontricks/bin/activate
python -c "from protontricks.steam import find_steam_path, get_steam_lib_paths; steam_path, _ = find_steam_path(); print(get_steam_lib_paths(steam_path))"
```

**Comment by lucifertdark** [comment]
I'm getting the same error, here's what those commands print out for me... 

['/home/rob/.steam/steam']

**Comment by Matoking** [comment]
> I'm getting the same error, here's what those commands print out for me...
> 
> ['/home/rob/.steam/steam']

What OS are you running? What is your Python version (check with `python3 --version`)?

**Comment by lucifertdark** [comment]
Those details would help. ;)
Ubuntu 19.10 with the 5.3.0 kernel & Python 3.7.5

**Comment by Matoking** [comment]
I pushed a small update to `re_debug` branch that should print more information when the exception happens.

Install the test version with the following command, reopen the terminal and then try running the command that causes the crash and paste whatever it prints:

```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@re_debug protontricks
```

**Comment by lucifertdark** [comment]
That seems to have fixed it for me...

winetricks GUI enabled, using zenity 3.32.0
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
Using winetricks 20191224-next - sha256sum: a365afd027a1729bc9334511a6c810308f4790bee31b4cd15334b1e5eb20bcb5 with wine-4.11 and WINEARCH=win64
winetricks GUI enabled, using zenity 3.32.0

**Comment by Matoking** [comment]
That's a different error, although it should also be handled properly as of 24070b0e56571bde76fe74621f03a57ad0772ff9.

You should still be getting the `sre_constants.error: bad character range D-1 at position 7` error or something similar, as the change only prints more information when that error happens.

**Comment by lucifertdark** [comment]
I think my bug was caused by an outdated version of Winetricks, now updated, apologies for muddying the waters.

**Comment by Matoking** [comment]
@NodokaHanamura Please test the following test branch as described earlier:
```
pipx install --force --spec git+https://github.com/Matoking/protontricks.git@re_debug protontricks
```

I haven't been able to reproduce the error using either my own paths or what @lucifertdark provided, so it might be unique to your environment.

**Comment by NodokaHanamura** [comment]
Sorry for the delay.

I've tried both commands you've given me and got the following output:

```
nikki@SENIORNEGI-Linux ~ $ pipx install --force --spec git+https://github.com/Matoking/protontricks.git@re_debug protontricks
usage: pipx [-h] [--version]
            {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions}
            ...
pipx: error: unrecognized arguments: --spec protontricks
nikki@SENIORNEGI-Linux ~ $ source ~/.local/pipx/venvs/protontricks/bin/activate
(protontricks) nikki@SENIORNEGI-Linux ~ $ python -c "from protontricks.steam import find_steam_path, get_steam_lib_paths; steam_path, _ = find_steam_path(); print(get_steam_lib_paths(steam_path))"
['/home/nikki/.steam/steam', '/media/nikki/[HDD-1] HOME YUE/SteamLibrary', '/media/nikki/[HDD-3] HOME ZVEZDA/SteamLinux', '/media/nikki/[HDD-4] HOME POBEDA/!Linux', '/media/nikki/[HDD-6] HOME SHUTEN/SteamLibrary']
```

**Comment by Matoking** [comment]
Thanks for the help, I was able to reproduce the error and I've now fixed it in the master branch.

You can use the command in README to install the development version with the bug fix until a new release is made.
