### ISSUE TITLE
Proton installation could not be found!

### ISSUE THREAD

**Issue by F4zii** [Matoking/protontricks#50]
Install protontricks from Aur but im getting this error - 
`protontricks (ERROR): No Proton installation found in config.vdf
protontricks (ERROR): Active Proton installation could not be found automatically.
Proton installation could not be found!
`

How can i fix this problem?

**Comment by Matoking** [comment]
Have you installed and started a Proton-enabled game? If not, the Proton installation might still be missing and there's nothing Protontricks can do yet.

Otherwise, try running the command prefixed with `protontricks -v` (eg. `protontricks -v <appid> <command>`) and paste the output.

**Comment by F4zii** [comment]
Hello, i fixed this, thanks
