### ISSUE TITLE
Game is installed but not found in both the GUI and the CLI

### ISSUE THREAD

**Issue by F4zii** [Matoking/protontricks#52]
I have rocket league installed, but it's not found in both the GUI and the CLI, what can be the problem and how can I fix that?

**Comment by Matoking** [comment]
Did you launch the game as well? Steam won't create a Wine prefix until the game is launched for the first time, so Protontricks won't have anything to work with until the Wine prefix exists.

If you did launch the game and the Wine prefix exists, try running `protontricks -v -s rocket` and copy paste the output into a reply.

**Comment by F4zii** [comment]
```
protontricks (INFO): Found Steam directory at /home/iddos/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/iddos/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: robo
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
Found no games.

NOTE: A game must be launched at least once before protontricks can find the game.
```

**Comment by Matoking** [comment]
You may still have the Linux version of the game installed. Right-click the game in the library and check the Properties; if *Force the user of a specific Steam Play compatibility tool* is *not* checked, you are running the Linux version.

The Linux support will be removed later in March, and you can still play the native version until they release a new patch. After that, you'll have to check the aforementioned setting if you want to play online using Proton.

**Comment by F4zii** [comment]
Oh, thanks! I will try that

**Comment by F4zii** [comment]
Also, should I check the latest proton version? or it doesn't matter (in the `Force the user of a specific Steam Play compatibility tool` option)

**Comment by Matoking** [comment]
If you're enabling Proton for a game that doesn't use it by default you'll usually want to use the newest version. This may not always be the case; you can check ProtonDB to see if there are version specific issues, as well as other required workarounds.

**Comment by F4zii** [comment]
Now when I run `protontricks 252950 vcrun2017`

I get 
```bash
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 32
drwxr-xr-x  8 iddos iddos 4096 Mar  3 19:31 .
drwxr-xr-x  4 iddos iddos 4096 Mar  3 19:33 ..
drwxr-xr-x  4 iddos iddos 4096 Mar  3 19:30 ProgramData
drwxr-xr-x  6 iddos iddos 4096 Mar  3 19:29 Program Files
drwxr-xr-x  9 iddos iddos 4096 Mar  3 19:31 Program Files (x86)
drwxr-xr-x  4 iddos iddos 4096 Mar  3 19:29 users
drwxr-xr-x  3 iddos iddos 4096 Mar  3 19:29 vrclient
drwxr-xr-x 19 iddos iddos 4096 Mar  3 19:30 windows

Registry info:
/home/iddos/.steam/steam/steamapps/compatdata/252950/pfx/system.reg:#arch=win64
/home/iddos/.steam/steam/steamapps/compatdata/252950/pfx/userdef.reg:#arch=win64
/home/iddos/.steam/steam/steamapps/compatdata/252950/pfx/user.reg:#arch=win64
------------------------------------------------------
------------------------------------------------------
/home/iddos/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%ProgramFiles%' returned empty string, error message "" 
------------------------------------------------------
```

**Comment by F4zii** [comment]
And when i run `protontricks -c 'wine ~/Downloads/BakkesModInjector/BakkesMod.exe' 252950`


I get 
```
0072:err:esync:esync_init Server is running with WINEESYNC but this process is not, please enable WINEESYNC or restart wineserver.
```

**Comment by F4zii** [comment]
Now when i run `protontricks -c 'wine ~/Downloads/BakkesModInjector/BakkesMod.exe' 252950`
The wine server is starting and the injector is going up, but when i start rocket league, it does now show and this is raised- 

```
Protocol error: process 003b: sendmsg: Bad file descriptor
```

**Comment by F4zii** [comment]
The rocket league window is frozen while bakkess mod window says it is not running

**Comment by Matoking** [comment]
That seems to be a bug or a limitation with either Proton or BakkesMod and out of scope for Protontricks.

You could contact the original author who found that workaround and ask them instead.
