### ISSUE TITLE
Ubuntu 20.04:  Protontricks failed to install

### ISSUE THREAD

**Issue by legluondunet** [Matoking/protontricks#53]
Hello,

I follow your guide, install necessary packages, but when I try to install Protontricks I obtained this message:

```
$ pipx install --spec git+https://github.com/Matoking/protontricks.git protontricks
usage: pipx [-h] [--version] {install,inject,upgrade,upgrade-all,uninstall,uninstall-all,reinstall-all,list,run,runpip,ensurepath,completions} ...
pipx: error: unrecognized arguments: --spec protontricks
```

If I launch PRotontricks version installed before I upgraded to Ubuntu 20.04:

```
$ protontricks
Traceback (most recent call last):
  File "/home/legluondunet/.local/bin/protontricks", line 6, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
```

My Python 3 version:

`$ python3 --version
Python 3.8.2`

Thank you for your help.

**Comment by Matoking** [comment]
pipx syntax seems to have changed in the newer versions of pipx, so the following should work instead:
```
pipx install git+https://github.com/Matoking/protontricks.git
```

If you already have protontricks installed, you'll need to use the `--force` parameter, which pipx should suggest if that's the case:
```
pipx install --force git+https://github.com/Matoking/protontricks.git
```

I've updated the instructions in README with this change.

---

If you're still getting the `pkg_resources` error after the steps above, try uninstalling protontricks and then reinstalling:
```
pipx uninstall protontricks
pipx install git+https://github.com/Matoking/protontricks.git
```

**Comment by legluondunet** [comment]
this doesn't seem to work:

```
$ pipx install --force git+https://github.com/Matoking/protontricks.git
Traceback (most recent call last):
  File "/home/legluondunet/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/main.py", line 162, in run_pipx_command
    return commands.install(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 38, in install
    package_name = _package_name_from_spec(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 100, in _package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/venv.py", line 218, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/venv.py", line 300, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
$ pipx uninstall protontricks
uninstalled protontricks! ✨ 🌟 ✨
$ pipx uninstall protontricks
Nothing to uninstall for protontricks 😴
⚠️  Note: '/usr/local/bin/protontricks' still exists on your system and is on your PATH
legluondunet@tipingouin-home:~$ pipx install git+https://github.com/Matoking/protontricks.git
Traceback (most recent call last):
  File "/home/legluondunet/.local/bin/pipx", line 8, in <module>
    sys.exit(cli())
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/main.py", line 590, in cli
    return run_pipx_command(parsed_pipx_args)
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/main.py", line 162, in run_pipx_command
    return commands.install(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 38, in install
    package_name = _package_name_from_spec(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/commands/commands.py", line 100, in _package_name_from_spec
    package_name = venv.install_package_no_deps(
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/venv.py", line 218, in install_package_no_deps
    old_package_set = self.list_installed_packages()
  File "/home/legluondunet/.local/lib/python3.8/site-packages/pipx/venv.py", line 300, in list_installed_packages
    pip_list = json.loads(cmd_run.stdout.strip())
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by legluondunet** [comment]
I found the problem, I don't know why but I had protontricks, pipx and older python3 components installed in two different paths:
- /home/legluondunet/.local/bin/pipx
- /user/local/bin/pipx
- /home/legluondunet/.local/bin/protontricks
- /user/local/bin/protontricks
- /home/legluondunet/.local/lib/python3.8
- /usr/local/lib/python3.8
.....
I needed to clean all this and I tell you if it works like it should.

**Comment by Matoking** [comment]
You can also try uninstalling pipx and removing the `~/.local/pipx` directory, and then reinstalling pipx and protontricks. The aforementioned directory contains symlinks to different Python files that could cause issues if they're no longer valid after the Ubuntu 20.04 upgrade.

**Comment by legluondunet** [comment]
my system is now cleaned.

romain@tipingouin-home:~$ pipx install --spec git+https://github.com/Matoking/protontricks.git protontricks
  ERROR: Command errored out with exit status 1:ing/protontricks.git#egg=protontricks'   
   command: /home/romain/.local/pipx/venvs/protontricks/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vyg3x9mp/protontricks/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vyg3x9mp/protontricks/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-0hajl3ym
       cwd: /tmp/pip-install-vyg3x9mp/protontricks/
  Complete output (7 lines):
  WARNING: The wheel package is not available.
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for protontricks
  installed package protontricks 1.4.2.dev3+g9809712, Python 3.8.2                       
  These binaries are now globally available
    - protontricks
done! ✨ 🌟 ✨

**Comment by legluondunet** [comment]
```
$ bdist_wheel
bdist_wheel : can not find command
```

**Comment by Matoking** [comment]
Did you try removing the `~/.local/pipx` directory and reinstalling pipx? pipx should take care of installing `wheel` for you and the fact it complains about the missing package means something is still wrong.

**Comment by legluondunet** [comment]
Ok, I can install wheel with pipx:
`pipx install wheel`

and now the error message gone.

Everything works like it should now, thank you very much for your help.

**Comment by legluondunet** [comment]
The issue was not protontricks related but Ubuntu related:
after upgrading Ubuntu 19.04 to 20.04, the local python3/pipx located in my home was obsolete.
And more than that I use one time this line in sudo and another time in simple user:
`pipx install --spec git+https://github.com/Matoking/protontricks.git protontricks`
so I had two obsolete python3/pipx/protontricks directory, one in /home/legluondunet/.local/bin and another in /usr/local/bin.

What a mess! Once again thank you for your help.

**Comment by 0x6A7232** [comment]
This is just a heads up for anyone trying to install a different version of protontricks after having the Flatpak version installed and getting this error even after uninstalling it:

```$ protontricks
error: app/com.github.Matoking.protontricks/x86_64/master not installed
```

Check your `~/.bashrc` file for:

```
alias protontricks='flatpak run com.github.Matoking.protontricks'
alias protontricks-launch='flatpak run --command=protontricks-launch com.github.Matoking.protontricks'
```

If you have those, either comment them (add # before the lines, useful in case you might re-install Flatpak version later) or just delete them, then re-launch your terminal.

(These lines were in a how-to for using Flatpak protontricks, and I had forgotten all about them, it took hours to find before an AI suggested the command `type protontricks` and that output jogged my memory.)
