### ISSUE TITLE
Protontricks can't find any games

### ISSUE THREAD

**Issue by stuaxo** [Matoking/protontricks#58]
Hi.
  I installed protontricks from the GUI, and it couldn't seem to find any games, any idea where I go from here ?

```bash
$ protontricks --gui
Found no games. You need to launch a game at least once before protontricks can find it.
```

I have Steam installed (flatpak, deb and wine) and I have launched games in the past.

**Comment by stuaxo** [comment]
Just found the other info on flatpak, closing.

**Comment by rambo919** [comment]
Well that's useful for the rest of us.....

**Comment by stuaxo** [comment]
Probably not my best feedback - I think what I didn't write there is that I hadn't noticed the info in the README.md that says:

> If you're using the Flatpak version of Steam, follow the [Flatpak-specific installation instructions](https://github.com/flathub/com.github.Matoking.protontricks) instead.

I then followed that link and the instructions there.
