### ISSUE TITLE
Asciinema recording archived (README.md)

### ISSUE THREAD

**Issue by simons-public** [Matoking/protontricks#6]
The link to [asciinema](https://asciinema.org/a/i2uqz1uZXYACl9NAHYbuZ3TCT) on the readme at [line 41](https://github.com/Matoking/protontricks/blame/master/README.md#L41) is to a recording that has been archived.

```
This recording has been archived
All unclaimed recordings (the ones not linked to any user account) are automatically archived 7 days after upload.
```

**Comment by Matoking** [comment]
Good catch, I've replaced it with a new recording.
