### ISSUE TITLE
--gui shows 'returned empty string error message' then exits

### ISSUE THREAD

**Issue by zaggynl** [Matoking/protontricks#60]
```
az@master3900x:~> /home/az/.local/bin/protontricks --gui
winetricks GUI enabled, using zenity 3.32.0
Executing mkdir -p /home/az/.steam/steam/steamapps/compatdata/393380
------------------------------------------------------
You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.
------------------------------------------------------
------------------------------------------------------
WINEPREFIX INFO:
Drive C: total 0
drwxr-xr-x 1 az users 126 May 26 22:52 .
drwxr-xr-x 1 az users 126 May 26 22:53 ..
drwxr-xr-x 1 az users  44 May 26 22:52 ProgramData
drwxr-xr-x 1 az users 118 May 26 22:52 Program Files
drwxr-xr-x 1 az users 154 May 26 22:52 Program Files (x86)
drwxr-xr-x 1 az users  30 May 26 22:52 users
drwxr-xr-x 1 az users   6 May 26 22:52 vrclient
drwxr-xr-x 1 az users 462 May 26 22:52 windows

Registry info:
/home/az/.steam/steam/steamapps/compatdata/393380/pfx/system.reg:#arch=win64
/home/az/.steam/steam/steamapps/compatdata/393380/pfx/userdef.reg:#arch=win64
/home/az/.steam/steam/steamapps/compatdata/393380/pfx/user.reg:#arch=win64
------------------------------------------------------
This option is not available. Please see --help for all possible usages.
------------------------------------------------------
/home/az/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 
------------------------------------------------------
```

**Comment by Matoking** [comment]
I'm guessing the dialog that allows you to select the command (eg. "Install an application", "Install DLL", etc.) doesn't pop up after you select the game?

The `This option is not available. Please see --help for all possible usages.`  message seems to originate from zenity, and [the changelog](https://steamcommunity.com/groups/SteamClientBeta/announcements/detail/2188132457791184895) for the latest Steam beta release on May 25th has the following line:

> Fixes bundled zenity binary

Could you try toggling Steam beta to see if it fixes the issue? You can change beta participation in _Steam_ -> _Settings_ -> _Account_ -> _Beta participation_, after which you need to restart Steam. If this fixes the issue, please reply with what version of Steam works.

---

If that doesn't fix the issue, could you try running the following command and see what it prints?

```
protontricks -c 'whereis zenity' 393380
```

**Comment by zaggynl** [comment]
Thanks for the reply, I'm already on Steam Beta.

```
az@master3900x:~> /home/az/.local/bin/protontricks -c 'whereis zenity' 393380
zenity: /usr/bin/zenity /usr/share/zenity /usr/share/man/man1/zenity.1.g
```

I also get these popups when running:

/home/az/.local/bin/protontricks --gui

You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

/home/az/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 

After the last message I'm back at the terminal prompt.
```
zenity --version
3.32.0
```

**Comment by Matoking** [comment]
Since you have a system-wide zenity installed, it looks like Protontricks/Winetricks shouldn't be affected by the Steam's bundled zenity.

The message about 64-bit WINEPREFIX is to be expected and it's always displayed by Winetricks since Proton only uses 64-bit prefixes.

---

What Linux distro are you running? Does the error happen if you try running Protontricks for a different game? What does Protontricks print if you try running `protontricks -v --gui` instead?

You could also try updating your Winetricks if you're running an older version, see the instructions for that [here](https://github.com/Winetricks/winetricks#installing).

**Comment by zaggynl** [comment]
OpenSUSE Tumbleweed, for some reason protontricks -v --gui seems to work now!

**Comment by Matoking** [comment]
Closing this issue since the issue seems to be solved.

**Comment by BeStillAsBright** [comment]
Hi,

I'm having the same issue as zaggynl had, except protontricks -v --gui is not working for me either. This is for Rise of Nations Extended Edition on Ubuntu 20.04. I tried both the command line and gui and they both return the same error message. I've also tried selecting another game, which actually worked, so it seems to be an issue with just this game potentially?

Please let me know if you have any further troubleshooting that I can do.

**Comment by yaomtc** [comment]
I also can't get protontricks working because of this. I've attached the output.
[protontricks-appdata.txt](https://github.com/Matoking/protontricks/files/4963557/protontricks-appdata.txt)

**Comment by Bus42** [comment]
Same thing, running Fallout New Vegas. 

- Ran `protontrics --gui` to make sure I had the correct .dlls installed and got the following message:

> `/home/greg/.cache/protontricks/proton/Proton 4.11/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message ""`

- I reinstalled Protontricks with `pipx install protontricks --force`, still getting the same error

**Comment by woontoon** [comment]
did any of you have the game open while running it? in my case it was the witcher 3 and after closing it and running `protontricks -v --gui` and it worked fine without the error message

**Comment by notqualia** [comment]
warning: /home/qualia/.cache/protontricks/proton/Proton 6.3/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 

`[qualia@qualia proton]$ /home/qualia/.cache/protontricks/proton/Proton 6.3/bin/wine cmd.exe /c echo '%AppData%' 
bash: /home/qualia/.cache/protontricks/proton/Proton: No such file or directory
`

`[qualia@qualia proton]$ /home/qualia/.cache/protontricks/proton/'Proton 6.3'/bin/wine cmd.exe /c echo '%AppData%' 
/home/qualia/.cache/protontricks/proton/Proton 6.3/bin/wine: line 69: /run: Is a directory`

**Comment by debian-user-france1** [comment]
There's a problem with Proton 5 on my system with protontricks. Proton 6 works but proton5 has following output:

`warning: /home/france1/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message ""`

Then I noticed that the game was still running on steam (but was closed) so I stopped it and now it works

**Comment by debian-user-france1** [comment]
the option -v shouldn't have any effect
