### ISSUE TITLE
Doesn't allow non-integer App ID's

### ISSUE THREAD

**Issue by Krutonium** [Matoking/protontricks#62]
**Describe the bug**
It's not possible to use protontricks to modify an application using a non integer appid.

**To Reproduce**
1. Install a game to a non-integer prefix (like I did)
2. Command fails and error is displayed

**Expected behavior**
It should check if the appid is valid before assuming that it isn't because it's not an integer.

**System (please complete the following information):**
 - Distro: Arch Linux
 - Protontricks version: protontricks (1.4.1)

 - Steam version: Not Beta
**Additional context**
I wrote a script that allows me to install arbitrary applications into Steam Prefixes, and didn't restrict AppID's to integers, since there's technically no reason to do so - Any ID is a valid ID. I installed UPlay into Steam, and it works, but I want to run winecfg, and I can't because protontricks won't allow me to do so, because it's expecting an integer ID.

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

For example, if the command that causes the error is `protontricks 42 faudio`, run `protontricks -v 42 faudio` instead and copy the output here.
```
protontricks uplay winecfg
usage: protontricks [-h] [--verbose] [-s SEARCH [SEARCH ...]] [-c COMMAND]
                    [--gui] [--no-runtime] [-V]
                    [appid] ...
protontricks: error: argument appid: invalid int value: 'uplay'
```

**Comment by Matoking** [comment]
[App ID is defined](https://partner.steamgames.com/doc/api/steam_api#AppId_t) by Steam API to be an unsigned integer and other applications and libraries seem to follow this definition, so accepting non-integer values here could muddy the waters.

I also don't know if Steam client is accepting non-integer app IDs on purpose or due to an oversight, so I'd rather not implement this if there's a chance this could break later on.

**Comment by Krutonium** [comment]
Maybe if you put it behind a `--unsupported` flag or something similar to allow for it, without making it a default behaviour - and making it clear that it's not supported?

**Comment by Matoking** [comment]
App ID is assumed to be an integer in many parts of the code, and adding a feature flag to change this behaviour doesn't seem justified right now given the additional complexity.

I'll close the feature request for the time being. I'll reconsider this if the situation changes: right now, I don't know of any applications that deal with non-integer app IDs.
