### ISSUE TITLE
'%AppData%' returned empty string, error message 

### ISSUE THREAD

**Issue by Wintere107** [Matoking/protontricks#63]
**Describe the bug**
[wintere@wintere-nuc8i5beh ~]$ protontricks 35140 mdx d3dx9 d3dcompiler_43 win10
Github down? version '' doesn't appear to be a valid version

Executing mkdir -p /home/wintere/.steam/steam/steamapps/compatdata/35140

You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

WINEPREFIX INFO:
Drive C: 总用量 32
drwxr-xr-x  8 wintere wintere 4096  8月 23 17:00 .
drwxr-xr-x  4 wintere wintere 4096  8月 23 17:07 ..
drwxr-xr-x  3 wintere wintere 4096  8月 23 17:00 ProgramData
drwxr-xr-x  6 wintere wintere 4096  8月 23 17:00 Program Files
drwxr-xr-x  8 wintere wintere 4096  8月 23 17:01 Program Files (x86)
drwxr-xr-x  4 wintere wintere 4096  8月 23 17:00 users
drwxr-xr-x  3 wintere wintere 4096  8月 23 17:00 vrclient
drwxr-xr-x 19 wintere wintere 4096  8月 23 17:01 windows

Registry info:
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/system.reg:#arch=win64
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/userdef.reg:#arch=win64
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/user.reg:#arch=win64

/home/wintere/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message "" 

**System :**
 - Distro: Manjaro 20.1 Mikah
 - Protontricks version: protontricks (1.4.1)
 - Steam version: Steam_ Beta_Update(steam-manjaro 1.0.0.64-1)

**Additional context**
[wintere@wintere-nuc8i5beh ~]$ protontricks -v 35140 mdx d3dx9 d3dcompiler_43 win10
protontricks (INFO): Found Steam directory at /home/wintere/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/wintere/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: drunkenbell
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
protontricks (INFO): Found active Proton installation: Proton 5.0
protontricks (INFO): WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
protontricks (INFO): WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
protontricks (INFO): Created Steam Runtime Wine binary directory at /home/wintere/.cache/protontricks/proton/Proton 5.0/bin
protontricks (INFO): Attempting to run command ['/usr/bin/winetricks', 'mdx', 'd3dx9', 'd3dcompiler_43', 'win10']

Github down? version '' doesn't appear to be a valid version

Executing mkdir -p /home/wintere/.steam/steam/steamapps/compatdata/35140

You are using a 64-bit WINEPREFIX. Note that many verbs only install 32-bit versions of packages. If you encounter problems, please retest in a clean 32-bit WINEPREFIX before reporting a bug.

WINEPREFIX INFO:
Drive C: 总用量 32
drwxr-xr-x  8 wintere wintere 4096  8月 23 17:00 .
drwxr-xr-x  4 wintere wintere 4096  8月 23 18:06 ..
drwxr-xr-x  3 wintere wintere 4096  8月 23 17:00 ProgramData
drwxr-xr-x  6 wintere wintere 4096  8月 23 17:00 Program Files
drwxr-xr-x  8 wintere wintere 4096  8月 23 17:01 Program Files (x86)
drwxr-xr-x  4 wintere wintere 4096  8月 23 17:00 users
drwxr-xr-x  3 wintere wintere 4096  8月 23 17:00 vrclient
drwxr-xr-x 19 wintere wintere 4096  8月 23 17:01 windows

Registry info:
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/system.reg:#arch=win64
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/userdef.reg:#arch=win64
/home/wintere/.steam/steam/steamapps/compatdata/35140/pfx/user.reg:#arch=win64

/home/wintere/.cache/protontricks/proton/Proton 5.0/bin/wine cmd.exe /c echo '%AppData%' returned empty string, error message ""

**Comment by Wintere107** [comment]
> This seems to be a Winetricks-related issue:
> 
> https://github.com/Winetricks/winetricks/blob/e1531b867ee0ae9ddb67adc7ecce2dc42f477cc1/src/winetricks#L3327
> 
> You could try updating Winetricks. If that doesn't work, you can try reporting the bug at the [Winetricks repository](https://github.com/Winetricks/winetricks).

Thank you for your reply, switch to proton 4.11-13 got this fixed ,it seems protontricks/winetricks doesnt work on proton 5.0-9

**Comment by Matoking** [comment]
Protontricks and Winetricks *should* work with Proton 5.0 just fine. This could be an issue related to your Winetricks installation, the Wine prefix for your game that Steam created for you becoming broken for some reason, or some other reason.

If it works using Proton 4.11, you could try using Proton 5.0 for some other game and seeing if the problem persists.

**Comment by Wintere107** [comment]
ok, i will try it out sometime,thanks for your project.
