### ISSUE TITLE
Error with every protontricks command

### ISSUE THREAD

**Issue by bobaxxx** [Matoking/protontricks#64]
**Describe the bug**
Cant launch any protontricks command without issue

**To Reproduce**
Steps to reproduce the behavior
run protontricks --gui

error displayed : 
[INFO] Found Steam directory at /home/seb/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
[INFO] WINETRICKS environment variable is not available. Falling back to /usr/bin/winetricks
[INFO] Found 1 Steam library folders
[INFO] Found active Proton installation: Proton 5.0
[INFO] Using Proton installation at /media/seb/DATA2/SteamLibrary/steamapps/common/Proton 5.0
[INFO] WINE environment variable is not available. Setting WINE environment variable to Proton bundled version
[INFO] WINESERVER environment variable is not available. Setting WINESERVER environment variable to Proton bundled version
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 405, in <module>
    game_appid = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: '--gui'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 153, in apport_excepthook
    with os.fdopen(os.open(pr_filename,
FileNotFoundError: [Errno 2] No such file or directory: '/var/crash/_usr_bin_protontricks.1000.crash'

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 405, in <module>
    game_appid = int(sys.argv[1])
ValueError: invalid literal for int() with base 10: '--gui'

**System (please complete the following information):**
 - Distro: Linux mint 20
 - Protontricks version: 5.0
 - Steam version: The last known version 

It found 1 steam library folder, but i have 2 library for steam, i aldreay done an export of the 2nd library folder (without success)

**Comment by Matoking** [comment]
You're running the [old version of Protontricks](https://github.com/sirmentio/protontricks).

Assuming you haven't tried to install the new version, you'll want to remove the old version of Protontricks by running the following command:

```
sudo rm /usr/bin/protontricks
```

After that, you can follow [the installation instructions](https://github.com/Matoking/protontricks#installation).

**Comment by bobaxxx** [comment]
hi

thx for help, i did what you say, protontricks is installed but not in /usr/bin/protontricks, its in $HOME/.local/pipx/venvs/protontricks/bin/protontricks

i tried this command to install wmp11 through protontricks for a specific game :

sudo /home/seb/.local/pipx/venvs/protontricks/bin/protontricks $STEAMID wmp11

result : Steam installation directory could not be found.

**Comment by bobaxxx** [comment]
Running again the command without sudo make wmp11 installed for the steam game

its works now !!

thx for help
