### ISSUE TITLE
No such file or directory: /.steam/steam/appcache/appinfo.vdf

### ISSUE THREAD

**Issue by JokerGermany** [Matoking/protontricks#71]
**Describe the bug**
Protontricks crashes because it can't find the appinfo.vdf
/.steam/steam/appcache/appinfo.vdf
I don't have a folder called appcache.
(I want to install bakkesMod for RocketLeague and try to follow this instructions:
https://bakkesmod.fandom.com/wiki/Running_in_Linux_/_Steam_Proton )

**To Reproduce**
Try 1:
`protontricks -v 252950 vcrun2017`
=>
protontricks (INFO): Found Steam directory at /home/jokergermany/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/jokergermany/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: ***
protontricks (INFO): Found 0 Steam shortcuts running under Proton
Traceback (most recent call last):
  File "/home/jokergermany/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli.py", line 234, in main
    proton_app = find_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 513, in find_proton_app
    proton_app = find_steam_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 425, in find_steam_proton_app
    proton_appid = get_proton_appid(compat_tool_name, appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 310, in get_proton_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 255, in get_appinfo_sections
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jokergermany/.steam/steam/appcache/appinfo.vdf'

Try 2:
protontricks -v --gui
Pick "Rocket League: 252950"
=>
protontricks (INFO): Found Steam directory at /home/jokergermany/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/jokergermany/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
protontricks (INFO): Currently logged-in Steam user: ***
protontricks (INFO): Found 0 Steam shortcuts running under Proton
Traceback (most recent call last):
  File "/home/jokergermany/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli.py", line 186, in main
    proton_app = find_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 513, in find_proton_app
    proton_app = find_steam_proton_app(
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 425, in find_steam_proton_app
    proton_appid = get_proton_appid(compat_tool_name, appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 310, in get_proton_appid
    vdf_sections = get_appinfo_sections(appinfo_path)
  File "/home/jokergermany/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 255, in get_appinfo_sections
    with open(path, "rb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/jokergermany/.steam/steam/appcache/appinfo.vdf'

**System (please complete the following information):**
 - Distro: Ubuntu Mate 20.04
 - Protontricks version: 1.4.2
 - Steam version: stable, no beta

**Comment by Matoking** [comment]
Try running the following commands and check if one of the `find` command finds the `appinfo.vdf` file somewhere. If so, please copy the output.

```
cd ~/.steam
find steam/ . -iname "appinfo.vdf"
cd ~/.local/share/Steam
find . -iname "appinfo.vdf"
```

**Comment by JokerGermany** [comment]
```
cd ~/.steam
find steam/ . -iname "appinfo.vdf"
```
=>
`./steam/steamapps/common/rocketleague/appinfo.vdf`
```
cd ~/.local/share/Steam
find . -iname "appinfo.vdf"
```
=>
``
bash: cd: /home/jokergermany/.local/share/Steam: Datei oder Verzeichnis nicht gefunden
``

**Comment by JokerGermany** [comment]
I use different libraries, perhaps this is the problem:
![LibarySteam](https://user-images.githubusercontent.com/30293477/98095379-c7b85a80-1e8a-11eb-8012-4b9e1eebfe4e.png)

I tried:
`cd /media/HDD/Steam
find steamapps/ . -iname "appinfo.vdf"
`
He found nothing.

**Comment by Matoking** [comment]
Very weird; I booted up an Ubuntu 20.04 VM and the appinfo.vdf file appears at `~/.steam/steam/appcache/appinfo.vdf` as expected. Protontricks supports multiple Steam libraries, so I doubt that is the problem.

---

You could try making a tree of your Steam installation directory and the external Steam library using the following commands:

```
sudo apt install tree
tree ~/.steam > ~/steam_tree.txt
tree /media/HDD/Steam > ~/steam_tree_hdd.txt
```

This will create two trees of file names and directories under the Steam installation directory and the external Steam library, with the resulting files `steam_tree.txt` and `steam_tree_hdd.txt` located in your home directory. They shouldn't contain anything sensitive, but just in case you can send them to the email address in my GitHub profile so I can check if the files Protontricks is looking for are in different places. Alternatively, you can post them publicly into [gist.github.com](https://gist.github.com/) and post the links into this thread.

**Comment by JokerGermany** [comment]
Thanks, i will send them to you, but first i will check it.
 
But i Found already that one:
```
jokergermany@huppyryzen:~/.steam/steam$ ll
insgesamt 420
drwxrwxr-x 10 jokergermany jokergermany   4096 Nov  4 09:18 ./
drwxrwxr-x 25 jokergermany jokergermany   4096 Nov  4 22:17 ../
lrwxrwxrwx  1 jokergermany jokergermany     45 Mai  5  2020 appcache -> /media/hdd/jokergermany/.steam/steam/appcache
drwxrwxr-x  2 jokergermany jokergermany  36864 Okt  8 11:07 cached/
drwxrwxr-x  5 jokergermany jokergermany   4096 Nov  4 22:08 config/
-rw-rw-r--  1 jokergermany jokergermany      0 Nov  4 09:18 .crash
drwxrwxr-x  2 jokergermany jokergermany 126976 Nov  4 22:07 depotcache/
drwxrwxr-x  2 jokergermany jokergermany   4096 Okt 16 16:08 games/
-rwxrwxr-x  1 jokergermany jokergermany 219330 Jan 20  2014 legacydepotdata.vdf*
drwxrwxr-x  2 jokergermany jokergermany   4096 Nov  4 22:17 logs/
drwxrwxr-x  3 jokergermany jokergermany   4096 Mai 31  2017 music/
-rw-rw-r--  1 jokergermany jokergermany   2048 Mai 31  2017 ssfn3760224215420356348
-rw-rw-r--  1 jokergermany jokergermany   2048 Jul 16  2016 ssfn6345571876085003751
drwxrwxr-x  9 jokergermany jokergermany   4096 Sep 23 08:44 steamapps/
drwxrwxr-x  8 jokergermany jokergermany   4096 Sep 11 21:45 userdata/
jokergermany@huppyryzen:~/.steam/steam$ cd appcache
bash: cd: appcache: Datei oder Verzeichnis nicht gefunden
```

**Comment by JokerGermany** [comment]
@Matoking You have Mail

**Comment by Matoking** [comment]
If the symlink points to an empty directory (`/media/hdd/jokergermany/.steam/steam/appcache`), could you try removing the symlink entirely, making a new directory and then restarting Steam?

I checked the file listings you sent, but didn't find anything related to this issue.

**Comment by JokerGermany** [comment]
I quit steam, deleted the symlink and restarted steam again. Then he made the directory at the SSD.
