### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by czajnik2137** [Matoking/protontricks#73]
**Describe the bug**
Protontricks won't install through pipx

**To Reproduce**
1. Run command 'pipx install protontricks'
2. Command fails and error is displayed

czajnik@ShitpostMachinaV3 ~> pipx install protontricks
Not installing to existing directory '/home/czajnik/.local/pipx/venvs/protontricks'. Pass '--force' to force installation
czajnik@ShitpostMachinaV3 ~ [1]> pipx install protontricks --force
Installing to existing directory '/home/czajnik/.local/pipx/venvs/protontricks'
Traceback (most recent call last):
  File "/usr/bin/pipx", line 11, in <module>
    load_entry_point('pipx==0.12.3.1', 'console_scripts', 'pipx')()
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 496, in cli
    exit(run_pipx_command(parsed_pipx_args, binary_args))
  File "/usr/lib/python3/dist-packages/pipx/main.py", line 147, in run_pipx_command
    commands.install(
  File "/usr/lib/python3/dist-packages/pipx/commands.py", line 312, in install
    if venv.get_venv_metadata_for_package(package).package_version is None:
  File "/usr/lib/python3/dist-packages/pipx/Venv.py", line 65, in get_venv_metadata_for_package
    data = json.loads(
  File "/usr/lib/python3.9/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
TypeError: __init__() got an unexpected keyword argument 'encoding'
czajnik@ShitpostMachinaV3 ~ [1]> 

**System (please complete the following information):**
 - Distro: Debian Sid

**Comment by Matoking** [comment]
Looks like an issue with the `pipx` installation not being up-to-date with [a change made in Python 3.9](https://docs.python.org/3/library/json.html?highlight=json#json.loads), which was released recently.

Try updating pipx with the following command:
```
python3 -m pip install --upgrade --user pipx
```

If that doesn't work, pipx probably hasn't been updated to be Python 3.9 compatible yet, in which case an issue report to the [pipx repository](https://github.com/pipxproject/pipx) would be appropriate.

**Comment by czajnik2137** [comment]
Problem solved, thanks!

**Comment by arucard21** [comment]
For anyone that still has problems after trying the fix proposed above, make sure to uninstall the Debian repo version of pipx (if you had that installed). Otherwise, it doesn't use the one that is updated with the fix above.
