### ISSUE TITLE
protontricks fails to find game

### ISSUE THREAD

**Issue by ScrambleTheRamble** [Matoking/protontricks#75]
**Describe the bug**
When trying to use protontricks to locate any game i get an error

**To Reproduce**
1. Run command `protontricks -s Ys`
2. Command fails and error is displayed

**Expected behavior**
The game id would be displayed

**System (please complete the following information):**
 - Distro: Pop Os 20.04
 - Protontricks version: 1.4.3
 - Steam version: Built: Dec 7 2020

**Additional context**

protontricks --verbose -s Ys
protontricks (INFO): Found Steam directory at /home/xxxx/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/xxxx/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 0 Steam library folders
protontricks (INFO): Currently logged-in Steam user: xxxx
protontricks (INFO): Couldn't find custom shortcuts. Maybe none have been created yet?
Traceback (most recent call last):
  File "/home/xxxx/.local/bin/protontricks", line 8, in <module>
    sys.exit(main())
  File "/home/xxxx/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/cli.py", line 160, in main
    steam_apps = get_steam_apps(
  File "/home/xxxx/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 834, in get_steam_apps
    _link_tool_apps(steam_apps)
  File "/home/xxxx/.local/pipx/venvs/protontricks/lib/python3.8/site-packages/protontricks/steam.py", line 784, in _link_tool_apps
    appid2steam_app[steam_app.required_tool_appid]
KeyError: 1391110

**Comment by ScrambleTheRamble** [comment]
Seems the 'Soldier' runtime was not yet installed, works now.

**Comment by Matoking** [comment]
Thanks for the report. I've pushed a change to master that prints a more informative error message when Proton is installed but the required Steam Runtime is missing.
