### ISSUE TITLE
Presumed update issue - python related

### ISSUE THREAD

**Issue by bradley-r** [Matoking/protontricks#79]
**Describe the bug**
After a system update (Fedora 32 to 33) and version update (1.4.2 to 1.4.3), protontricks no longer runs, stating that _'The 'protontricks==1.4.2' distribution was not found and is required by the application'_.

**To Reproduce**
1. Run command `protontricks --gui', for example.
2. Command fails and error is displayed:

> 
> `Traceback (most recent call last):
>   File "/home/bradleyr/.local/bin/protontricks", line 6, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
>     def _initialize_master_working_set():
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
>     f(*args, **kwargs)
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'protontricks==1.4.2' distribution was not found and is required by the application.`

**Expected behavior**
Protontricks would run, and in this case create a GUI window.

**System (please complete the following information):**
 - Distro: Fedora 33 KDE
 - Protontricks version: Presumably 1.4.3 as it seems to install successfully with pipx, but error means I cannot check.
 - Steam version: Steam Beta Update

**Additional context**

**If the error happens when trying to run a Protontricks command, run the command again using the `-v` flag and copy the output!**

Protontricks fails to run outright, so no commands can be executed. Both pip and pipx are able to install it though, and this error persists even after said installation and a restart. Help welcomed.

**Comment by Matoking** [comment]
Chances are Protontricks has been installed using more than one method, and that one installation is now overriding the other(s). The pipx installation for Protontricks might also be outdated following the Fedora 32 -> 33 update. In either case, you can try uninstalling Protontricks by running the following commands:

```
$ pipx uninstall protontricks
$ pip uninstall protontricks # User-specific pip installation
$ sudo pip uninstall protontricks # System-wide pip installation
```

After that try installing it again using the pipx method.

**Comment by bradley-r** [comment]
Uninstalled as expected with pipx, fails with pip and sudo pip; reporting that it was never installed in the first place. Reinstalling and attempting to run results in the same issue, I'm afraid.

**Comment by Matoking** [comment]
OK, can you check if the following command prints a path to a possible Protontricks installation:

```
$ python3 -c "import pkg_resources; print(repr(pkg_resources.get_distribution('protontricks')))"
```

It should print a "distribution not found" error if you've installed Protontricks using pipx, as pipx isolates Protontricks from the rest of Python packages whether they're installed system-wide or not.

You could also try if updating pipx does the trick:

```
$ python3 -m pip install --user --upgrade pipx
```

**Comment by bradley-r** [comment]
`$ python3 -c "import pkg_resources; print(repr(pkg_resources.get_distribution('protontricks')))"` does indeed return a 'not found' error, and while upgrading pipx did update to version 0.15.6.0, reinstalling protontricks made no difference once again.

There is a protontricks script in .local/bin/protontricks that **isn't** deleted when pipx reportedly uninstalls - could try manipulating that? My grasp of Python is focused simply on code, so I'm of little use when it comes to identifying advanced issues.

**Comment by Matoking** [comment]
You can try deleting `.local/bin/protontricks`. From my own testing it should be removed when it's uninstalled using pipx. User-specific pip installation also places an executable in some location, so maybe a conflict happened at one point leaving the file there?

**Comment by bradley-r** [comment]
That fixed it! I'm not quite sure why or how such a conflict could have arisen (unless F33 changed some directory structures) but it's back to how it was before. Thanks for the help!

**Comment by bradley-r** [comment]
For posterity, I'll also say that reinstalling with pipx created link in `.local/bin/protontricks` targeting `.local/pipx/venvs/protontricks/bin/` for whatever reason. Hopefully this helps anyone who encounters a similar scenario.
