### ISSUE TITLE
Can't install wmp11

### ISSUE THREAD

**Issue by nicoco59** [Matoking/protontricks#81]
**Describe the bug**
I can't install wmp11

**To Reproduce**
1. Run command `protontricks 743890 wmp11`
2. Command fails and error is displayed : Using winetricks 20180217 - sha256sum: 1b156c616174f41df79d72a90c52eb2b110c63a6e8ecb865d303a8f9f0908924 with wine-5.13-716-g7f9f4285c2d and WINEARCH=win64
Unknown arg wmp11

**Expected behavior**
Being able to install wmp11 to watch Megaman's cutscenes

**System (please complete the following information):**
 - Distro: Zorin OS 15.3 Core
 - Protontricks version: protontricks (1.4.3)
 - Steam version: 1608507519

**Comment by Matoking** [comment]
You seem to have an older version of Winetricks which doesn't have the `wmp11` verb. You can find the instructions for updating Winetricks [here](https://github.com/Winetricks/winetricks#installing).

**Comment by nicoco59** [comment]
Thanks for your answer, I'm currently on Zorin OS and it's stucked on the Bionic release, maybe that's why I can't update to the last version. At last I just downloaded a deb file and installed it, now I can see wmp11 :)
