### ISSUE TITLE
Can't Open Proton Tricks at all after some updates.

### ISSUE THREAD

**Issue by LuckyLuigiX4** [Matoking/protontricks#82]
I simply can't launch Proton Tricks at all. 

1. Run command protontricks
2. Command fails and error says this:
3. Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.4.dev4+g0fab781', 'console_scripts', 'protontricks')())
  File "/usr/bin/protontricks", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/protontricks/__init__.py", line 1, in <module>
    from .steam import *
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 8, in <module>
    import vdf
ModuleNotFoundError: No module named 'vdf'

**Expected behavior**
Proton Tricks should Launch

**System (please complete the following information):**
 - Distro: Manjaro
 - Protontricks version: 1.4.4.dev4+g0fab781
 - Steam version: Release
**Additional context**
I thought it was something to do with not having python-vdf due to the error above, but after reinstalling python-vdf it still came up with the same error.
I was previously able to use proton tricks around October, so My guess is that some update broke something.

**Comment by D33M0N** [comment]
Have same issue.

**Comment by Seegras** [comment]
Nearly the same. On Debian Sid (probably Bullseye too) I ran into this: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=970809
There is no `venv` anymore for pipx, as it seems, so the install-howto is probably outdated and the pipx method won't work on modern distributions anymore. 

However

`$ python -m pip install protontricks `

seemed to work. No sudo, and python is anyway:

```
$ python --version 
Python 3.9.1
```

**Comment by Matoking** [comment]
Did you install [protontricks-git](https://aur.archlinux.org/packages/protontricks-git/) from AUR? It seems that you may need to reinstall python-vdf manually in that case, since Protontricks is installed under `/usr/lib/python3.9` while python-vdf still uses `/usr/lib/python3.8`. In my case the following did the trick:

```
trizen -S python-vdf  # or use whatever AUR helper you have
```

**Comment by LuckyLuigiX4** [comment]
I tried reinstalling python-vdf manually, and nothing changed, same error message

**Comment by Matoking** [comment]
Have you ensured that python-vdf is rebuilt instead of being reinstalled from cache?

I don't know what AUR helper you're using (although pamac seems to pop up a lot in Manjaro docs), but you could try cleaning the cache and rebuilding python-vdf as opposed to just reinstalling it. If you're using pamac the command `pamac build python-vdf` might do the trick.

**Comment by D33M0N** [comment]
For me on Manjaro yay worked perfectly. Just in case did clean build also.

**Comment by LuckyLuigiX4** [comment]
Nothing has changed after completely removing protontricks and python-vdf and reinstalling both of them. I tried this once before as well and still nothing.

**Comment by D33M0N** [comment]
How did you completely remove them?
What program did you use to completely remove them?
What program did you use to reinstall them?

**Comment by LuckyLuigiX4** [comment]
I used my terminal via yay. I used yay -R protontricks-git, then yay -R python-vdf. Then I reinstalled python-vdf first, then protontricks-git.

**Comment by D33M0N** [comment]
do you have python 3.9.1-1 installed? When yes, then ...

```
[deemon@Zen scripts]$ yay -S protontricks-git python-vdf
:: Checking for conflicts...
:: Checking for inner conflicts...
[Aur:2]  python-vdf-3.3-2  protontricks-git-1.4-1

  2 python-vdf                       (Installed) (Build Files Exist)
  1 protontricks-git                 (Installed) (Build Files Exist)
==> Packages to cleanBuild?
==> [N]one [A]ll [Ab]ort [I]nstalled [No]tInstalled or (1 2 3, 1-3, ^4)
==> 
```
did you choose A here -- to CleanBuild All??

**Comment by LuckyLuigiX4** [comment]
I used my terminal via yay. I used yay -R protontricks-git, then yay -R python-vdf. Then I reinstalled python-vdf first, then protontricks-git.

**Comment by LuckyLuigiX4** [comment]
It is finally working again, thank you so much!
