### ISSUE TITLE
protontricks --gui doesn't work

### ISSUE THREAD

**Issue by lol28** [Matoking/protontricks#85]
protontricks --gui doesn't work, it was working around month ago, but then it stopped

protontricks (INFO): Found Steam directory at /home/alan/.steam/steam. You can also define Steam directory manually using $STEAM_DIR
protontricks (INFO): Using default Steam Runtime at /home/alan/.steam/root/ubuntu12_32/steam-runtime
protontricks (INFO): WINETRICKS environment variable is not available. Searching from $PATH.
protontricks (INFO): Found 1 Steam library folders
Traceback (most recent call last):
  File "/usr/bin/protontricks", line 33, in <module>
    sys.exit(load_entry_point('protontricks==1.4.3', 'console_scripts', 'protontricks')())
  File "/usr/lib/python3.9/site-packages/protontricks/cli.py", line 160, in main
    steam_apps = get_steam_apps(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 816, in get_steam_apps
    steam_app = SteamApp.from_appmanifest(
  File "/usr/lib/python3.9/site-packages/protontricks/steam.py", line 177, in from_appmanifest
    tool_manifest["manifest"].get("require_tool_appid", None)
KeyError: 'manifest'

 - Distro: Arch linux, KDE if it matters
 - Protontricks version: 1.4.3
 - Steam version: Not beta steam

**Comment by Matoking** [comment]
The contents for at least one of the `toolmanifest.vdf` files seems to have changed. Could you try running the following commands and post the output? You can use [gist.github.com](https://gist.github.com/).

```
find ~/.steam/steam/steamapps/common -type f -name "toolmanifest.vdf" -print -exec cat {} \;
find <STEAM_LIBRARY>/steamapps/common -type f -name "toolmanifest.vdf" -print -exec cat {} \;
```

**In the second command**, replace <STEAM_LIBRARY> with the path to the Steam library you've added yourself; you can find it under Settings -> Downloads -> Steam Library Folders. In my case, if the folder is listed as `/mnt/LinuxDataSSD_B/SteamLibrary`, I would run the command `find /mnt/LinuxDataSSD_B/SteamLibrary/steamapps/common -type f -name "toolmanifest.vdf" -print -exec cat {} \;`

**Comment by kleshas** [comment]
I get a similar error.  Here's mine:
https://gist.github.com/kleshas/1767a7808b6c3bdd28b1685c831a2e60

**Comment by Matoking** [comment]
@kleshas I couldn't reproduce the issue with the gist you posted. Did you run the `find` command for every Steam library you have added?

**Comment by kleshas** [comment]
Yup, I only have the one extra library.

**Comment by lol28** [comment]
https://gist.github.com/lol28/367e47b9cdd3f5f4b27cc77a183a4f7f

**Comment by Matoking** [comment]
@lol28 According to the gist you posted, `/mnt/games/SteamLibrary/steamapps/common/SteamLinuxRuntime/toolmanifest.vdf` appears to be an empty file. This would explain the error you're seeing.

Can you check that `/mnt/games/SteamLibrary/steamapps/common/SteamLinuxRuntime/toolmanifest.vdf` is indeed empty and if there are other similar files in the same directory (eg. `toolmanifest.v1.vdf` and `toolmanifest.v2.vdf`). What are the contents of those files?

**Comment by lol28** [comment]
Yes, it's empty file. toolmanifest.v1.vdf and toolmanifest.v2.vdf are also empty. Ok so i fixed the problem by validating Steam linux runtime cache in steam. 
![image](https://user-images.githubusercontent.com/29731178/106391272-b560a500-6416-11eb-802c-193303208cd7.png)

**Comment by Matoking** [comment]
Thanks for the help. I've pushed a fix to master so that a proper warning is shown when the tool manifest is empty.
