### ISSUE TITLE
Instructions: Forgets to mention requiring zenity

### ISSUE THREAD

**Issue by Ruedii** [Matoking/protontricks#86]
**Describe the bug**
The instructions fail to mention that Zenity needs to be installed to run
Fails to run with --gui as a result giving cryptic python crash error.

**To Reproduce**
1. Install ProtonTricks by instructions provided in README.md on a fresh Kubuntu installation
2. Attempt to run with the --gui option

**Expected behavior**
The instructions should include Zenity in the needed packages, or the program should have a proper error for this case.

**System (please complete the following information):**
 - Distro: Kubuntu 19.04.1
 - Protontricks version: protontricks (1.4.3)
 - Steam version: current standard (not beta)

**Comment by Matoking** [comment]
Thanks, I've updated the README and made the error message clearer.
